The BioCro C++ Library: /github/workspace/source/src/module_library/canac_with_collatz.hpp File Reference
canac_with_collatz.hpp File Reference
#include "../modules.h"
#include "../system.h"
#include "../standalone_ss.h"
#include "water_vapor_properties_from_air_temperature.hpp"
#include "penman_monteith_transpiration.hpp"
#include "collatz_leaf.hpp"
#include "AuxBioCro.h"
#include "BioCro.h"
Classes
class canac_with_collatz
Functions
struct Can_Str newCanAC (double LAI, int DOY, double hr, double solarR, double temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &nitroP, double leafwidth, double specific_heat_of_air, double atmospheric_pressure, int eteq, double StomataWS, int water_stress_approach, double leaf_transmittance, double leaf_reflectance, double absorptivity_par)
Function Documentation
newCanAC()
struct Can_Str newCanAC (double LAI, int DOY, double hr, double solarR, double temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms & nitroP, double leafwidth, double specific_heat_of_air, double atmospheric_pressure, int eteq, double StomataWS, int water_stress_approach, double leaf_transmittance, double leaf_reflectance, double absorptivity_par)
Definition at line 1 of file canac_with_collatz.hpp.
References Can_Str::Assim, Can_Str::canopy_conductance, Light_model::cosine_zenith_angle, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, lightME(), LNprof(), RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, and WINDprof().
Referenced by canac_with_collatz::do_operation().