The BioCro C++ Library: module_library Class Reference
module_library Class Reference
A factory class that creates module_creator objects; more colloquially, we say that a module or module_creator is "retrieved" from the module library.
#include <module_library.h>
Static Public Member Functions
static module_creator * retrieve (std::string const &module_name)
static string_vector get_all_modules ()
static std::unordered_map< std::string, string_vector > get_all_quantities ()
Private Types
using creator_fcn = module_creator *(*)()
using creator_map = std::map< std::string, creator_fcn >
Static Private Attributes
static creator_map library_entries
Detailed Description
A factory class that creates module_creator objects; more colloquially, we say that a module or module_creator is "retrieved" from the module library.
The module_library provides the main route for module creation by linking module names (strings) to module_creator objects via its retrieve() function. Once a module_creator representing a particular module class has been retrieved from the library, it can be used to identify the module's input and output quantities, and eventually to instantiate the module class, making it available for calculations.
Definition at line 23 of file module_library.h.
Member Typedef Documentation
creator_fcn
using creator_fcn = module_creator* (*)() private
Definition at line 31 of file module_library.h.
creator_map
using creator_map = std::map<std::string, creator_fcn> private
Definition at line 32 of file module_library.h.
Member Function Documentation
get_all_modules()
string_vector get_all_modules () static
Definition at line 255 of file module_library.cpp.
References library_entries.
Referenced by get_all_quantities().
get_all_quantities()
std::unordered_map< std::string, string_vector > get_all_quantities () static
Definition at line 280 of file module_library.cpp.
References get_all_modules(), ed_c4_leaf_photosynthesis_stuff::module_name, and retrieve().
retrieve()
module_creator * retrieve (std::string const & module_name) static
Definition at line 122 of file module_library.cpp.
References library_entries, and ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by get_all_quantities().
Member Data Documentation
library_entries
module_library::creator_map library_entries static private
Definition at line 33 of file module_library.h.
Referenced by get_all_modules(), and retrieve().
The documentation for this class was generated from the following files:
/github/workspace/source/src/module_library/module_library.h
/github/workspace/source/src/module_library/module_library.cpp