The BioCro C++ Library: ed_ten_layer_c4_canopy Class Reference
ed_ten_layer_c4_canopy Class Reference
A child class of multilayer_canopy_photosynthesis where:
#include <ed_multilayer_c4_canopy.h>
Public Member Functions
ed_ten_layer_c4_canopy (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from multilayer_canopy_photosynthesis< ed_ten_layer_canopy_properties, ed_c4_leaf_photosynthesis4 >
multilayer_canopy_photosynthesis (const std::string &module_name, const int &nlayers, state_map const &input_quantities, state_map *output_quantities)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
Private Member Functions
void do_operation () const
Static Private Attributes
static int const nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_photosynthesis< ed_ten_layer_canopy_properties, ed_c4_leaf_photosynthesis4 >
void run () const
Static Protected Member Functions inherited from multilayer_canopy_photosynthesis< ed_ten_layer_canopy_properties, ed_c4_leaf_photosynthesis4 >
static string_vector generate_inputs (int nlayers)
static string_vector generate_outputs (int nlayers)
Detailed Description
A child class of multilayer_canopy_photosynthesis where:
The canopy module is set to the ed_ten_layer_canopy_properties module
The leaf module is set to the ed_c4_leaf_photosynthesis4 module
The number of layers is set to 10 Instances of this class can be created using the module factory.
Definition at line 18 of file ed_multilayer_c4_canopy.h.
Constructor & Destructor Documentation
ed_ten_layer_c4_canopy()
ed_ten_layer_c4_canopy (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 21 of file ed_multilayer_c4_canopy.h.
Member Function Documentation
do_operation()
void do_operation () const private
Definition at line 55 of file ed_multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::run().
get_inputs()
string_vector get_inputs () static
Definition at line 43 of file ed_multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), and nlayers.
get_outputs()
string_vector get_outputs () static
Definition at line 49 of file ed_multilayer_c4_canopy.h.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), and nlayers.
Member Data Documentation
nlayers
int const nlayers = 10 static private
Definition at line 36 of file ed_multilayer_c4_canopy.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_multilayer_c4_canopy.h