The BioCro C++ Library: ed_ten_layer_canopy_properties Class Reference
ed_ten_layer_canopy_properties Class Reference
A child class of ed_multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory.
#include <ed_multilayer_canopy_properties.h>
Public Member Functions
ed_ten_layer_canopy_properties (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from ed_multilayer_canopy_properties
ed_multilayer_canopy_properties (int const &nlayers, state_map const &input_quantities, state_map *output_quantities)
Static Public Member Functions
static string_vector get_inputs ()
static string_vector define_leaf_classes ()
static string_vector define_multiclass_multilayer_outputs ()
static string_vector define_pure_multilayer_outputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Static Private Attributes
static const int nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from ed_multilayer_canopy_properties
void run () const
Static Protected Member Functions inherited from ed_multilayer_canopy_properties
static string_vector get_inputs (int nlayers)
Define all inputs required by the module.
static string_vector define_leaf_classes ()
Define the different leaf classes included by the module.
static string_vector define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static string_vector define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static string_vector get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Detailed Description
A child class of ed_multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory.
Definition at line 278 of file ed_multilayer_canopy_properties.h.
Constructor & Destructor Documentation
ed_ten_layer_canopy_properties()
ed_ten_layer_canopy_properties (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 281 of file ed_multilayer_canopy_properties.h.
Member Function Documentation
define_leaf_classes()
string_vector define_leaf_classes () static
Definition at line 311 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_leaf_classes().
define_multiclass_multilayer_outputs()
string_vector define_multiclass_multilayer_outputs () static
Definition at line 316 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_multiclass_multilayer_outputs().
define_pure_multilayer_outputs()
string_vector define_pure_multilayer_outputs () static
Definition at line 322 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_pure_multilayer_outputs().
do_operation()
void do_operation () const private
Definition at line 333 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::run().
get_inputs()
string_vector get_inputs () static
Definition at line 306 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::get_inputs(), and ed_ten_layer_canopy_properties::nlayers.
get_name()
static std::string get_name () inline static
Definition at line 295 of file ed_multilayer_canopy_properties.h.
get_outputs()
string_vector get_outputs () static
Definition at line 328 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::get_outputs(), and ed_ten_layer_canopy_properties::nlayers.
Member Data Documentation
nlayers
const int nlayers = 10 static private
Definition at line 299 of file ed_multilayer_canopy_properties.h.
Referenced by ed_ten_layer_canopy_properties::get_inputs(), and ed_ten_layer_canopy_properties::get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_multilayer_canopy_properties.h