The BioCro C++ Library: ed_multilayer_canopy_properties Class Reference
ed_multilayer_canopy_properties Class Reference
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part).
#include <ed_multilayer_canopy_properties.h>
Public Member Functions
ed_multilayer_canopy_properties (std::string const &module_name, int const &nlayers, state_map const *input_parameters, state_map *output_parameters)
Protected Member Functions
void run () const
Static Protected Member Functions
static std::vector< std::string > get_inputs (int nlayers)
Define all inputs required by the module.
static std::vector< std::string > define_leaf_classes ()
Define the different leaf classes included by the module.
static std::vector< std::string > define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static std::vector< std::string > define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static std::vector< std::string > get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes.
Private Attributes
int const nlayers
double const & par_energy_fraction_of_sunlight
double const & par_energy_content
double const & par_incident_direct
double const & par_incident_diffuse
double const & lai
double const & cosine_zenith_angle
double const & kd
double const & chil
double const & heightf
double const & rh
double const & windspeed
double const & LeafN
double const & kpLN
std::vector< double * > const sunlit_incident_par_ops
std::vector< double * > const sunlit_collatz_PAR_flux_ops
std::vector< double * > const sunlit_fraction_ops
std::vector< double * > const shaded_incident_par_ops
std::vector< double * > const shaded_collatz_PAR_flux_ops
std::vector< double * > const shaded_fraction_ops
std::vector< double * > const incident_scattered_par_ops
std::vector< double * > const incident_average_par_ops
std::vector< double * > const solar_energy_absorbed_leaf_ops
std::vector< double * > const height_ops
std::vector< double * > const rh_ops
std::vector< double * > const windspeed_ops
std::vector< double * > const LeafN_ops
Detailed Description
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part).
Also includes multiple leaf classes (sunlit & shaded). Leaf class is added to output parameters as a prefix, while layer number is added as a suffix. Note that this module has a non-standard constructor, so it cannot be created using the module_wrapper_factory.
For compatibility with the multilayer canopy photosynthesis module, the outputs of this module must be split into the following categories:
multiclass_multilayer outputs: these outputs are different for each leaf class and canopy layer
pure_multilayer outputs: these outputs are different for each canopy layer but not for each leaf class
other outputs: these outputs do not depend on the leaf class or canopy layer (there are currently no outputs of this type) The base names for the multiclass_multilayer and pure_multilayer outputs will be used by the multilayer canopy photosynthesis module to pass them to a leaf photosynthesis module.
Definition at line 30 of file ed_multilayer_canopy_properties.h.
Constructor & Destructor Documentation
ed_multilayer_canopy_properties()
ed_multilayer_canopy_properties (std::string const & module_name, int const & nlayers, state_map const * input_parameters, state_map * output_parameters) inline
Definition at line 33 of file ed_multilayer_canopy_properties.h.
Member Function Documentation
define_leaf_classes()
std::vector< std::string > define_leaf_classes () static protected
Define the different leaf classes included by the module.
Definition at line 144 of file ed_multilayer_canopy_properties.h.
Referenced by ed_ten_layer_canopy_properties::define_leaf_classes(), and get_outputs().
define_multiclass_multilayer_outputs()
std::vector< std::string > define_multiclass_multilayer_outputs () static protected
Define all outputs that have different values for each leaf class and layer.
Definition at line 155 of file ed_multilayer_canopy_properties.h.
Referenced by ed_ten_layer_canopy_properties::define_multiclass_multilayer_outputs(), and get_outputs().
define_pure_multilayer_outputs()
std::vector< std::string > define_pure_multilayer_outputs () static protected
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
Definition at line 168 of file ed_multilayer_canopy_properties.h.
Referenced by ed_ten_layer_canopy_properties::define_pure_multilayer_outputs(), and get_outputs().
get_inputs()
std::vector< std::string > get_inputs (int nlayers) static protected
Define all inputs required by the module.
Definition at line 122 of file ed_multilayer_canopy_properties.h.
Referenced by ed_ten_layer_canopy_properties::get_inputs().
get_outputs()
std::vector< std::string > get_outputs (int nlayers) static protected
Define all output names by appending leaf class prefixes and layer number suffixes.
Here we should make use of the define_XXX functions to reduce code duplication.
Definition at line 185 of file ed_multilayer_canopy_properties.h.
References define_leaf_classes(), define_multiclass_multilayer_outputs(), define_pure_multilayer_outputs(), and nlayers.
Referenced by ed_ten_layer_canopy_properties::get_outputs().
run()
void run () const protected
Definition at line 202 of file ed_multilayer_canopy_properties.h.
References chil, cosine_zenith_angle, Light_profile::diffuse_irradiance, Light_profile::direct_irradiance, Light_profile::height, height_ops, heightf, incident_average_par_ops, incident_scattered_par_ops, kd, kpLN, lai, LeafN, LeafN_ops, LNprof(), nlayers, par_energy_content, par_energy_fraction_of_sunlight, par_incident_diffuse, par_incident_direct, rh, rh_ops, RHprof(), Light_profile::scattered_irradiance, shaded_collatz_PAR_flux_ops, Light_profile::shaded_fraction, shaded_fraction_ops, shaded_incident_par_ops, solar_energy_absorbed_leaf_ops, sunlit_collatz_PAR_flux_ops, Light_profile::sunlit_fraction, sunlit_fraction_ops, sunlit_incident_par_ops, sunML(), Light_profile::total_irradiance, WINDprof(), windspeed, and windspeed_ops.
Referenced by ed_ten_layer_canopy_properties::do_operation().
Member Data Documentation
chil
double const& chil private
Definition at line 88 of file ed_multilayer_canopy_properties.h.
Referenced by run().
cosine_zenith_angle
double const& cosine_zenith_angle private
Definition at line 86 of file ed_multilayer_canopy_properties.h.
Referenced by run().
height_ops
std::vector<double*> const height_ops private
Definition at line 105 of file ed_multilayer_canopy_properties.h.
Referenced by run().
heightf
double const& heightf private
Definition at line 89 of file ed_multilayer_canopy_properties.h.
Referenced by run().
incident_average_par_ops
std::vector<double*> const incident_average_par_ops private
Definition at line 103 of file ed_multilayer_canopy_properties.h.
Referenced by run().
incident_scattered_par_ops
std::vector<double*> const incident_scattered_par_ops private
Definition at line 102 of file ed_multilayer_canopy_properties.h.
Referenced by run().
kd
double const& kd private
Definition at line 87 of file ed_multilayer_canopy_properties.h.
Referenced by run().
kpLN
double const& kpLN private
Definition at line 93 of file ed_multilayer_canopy_properties.h.
Referenced by run().
lai
double const& lai private
Definition at line 85 of file ed_multilayer_canopy_properties.h.
Referenced by run().
LeafN
double const& LeafN private
Definition at line 92 of file ed_multilayer_canopy_properties.h.
Referenced by run().
LeafN_ops
std::vector<double*> const LeafN_ops private
Definition at line 108 of file ed_multilayer_canopy_properties.h.
Referenced by run().
nlayers
int const nlayers private
Definition at line 78 of file ed_multilayer_canopy_properties.h.
Referenced by get_outputs(), and run().
par_energy_content
double const& par_energy_content private
Definition at line 82 of file ed_multilayer_canopy_properties.h.
Referenced by run().
par_energy_fraction_of_sunlight
double const& par_energy_fraction_of_sunlight private
Definition at line 81 of file ed_multilayer_canopy_properties.h.
Referenced by run().
par_incident_diffuse
double const& par_incident_diffuse private
Definition at line 84 of file ed_multilayer_canopy_properties.h.
Referenced by run().
par_incident_direct
double const& par_incident_direct private
Definition at line 83 of file ed_multilayer_canopy_properties.h.
Referenced by run().
rh
double const& rh private
Definition at line 90 of file ed_multilayer_canopy_properties.h.
Referenced by run().
rh_ops
std::vector<double*> const rh_ops private
Definition at line 106 of file ed_multilayer_canopy_properties.h.
Referenced by run().
shaded_collatz_PAR_flux_ops
std::vector<double*> const shaded_collatz_PAR_flux_ops private
Definition at line 100 of file ed_multilayer_canopy_properties.h.
Referenced by run().
shaded_fraction_ops
std::vector<double*> const shaded_fraction_ops private
Definition at line 101 of file ed_multilayer_canopy_properties.h.
Referenced by run().
shaded_incident_par_ops
std::vector<double*> const shaded_incident_par_ops private
Definition at line 99 of file ed_multilayer_canopy_properties.h.
Referenced by run().
solar_energy_absorbed_leaf_ops
std::vector<double*> const solar_energy_absorbed_leaf_ops private
Definition at line 104 of file ed_multilayer_canopy_properties.h.
Referenced by run().
sunlit_collatz_PAR_flux_ops
std::vector<double*> const sunlit_collatz_PAR_flux_ops private
Definition at line 97 of file ed_multilayer_canopy_properties.h.
Referenced by run().
sunlit_fraction_ops
std::vector<double*> const sunlit_fraction_ops private
Definition at line 98 of file ed_multilayer_canopy_properties.h.
Referenced by run().
sunlit_incident_par_ops
std::vector<double*> const sunlit_incident_par_ops private
Definition at line 96 of file ed_multilayer_canopy_properties.h.
Referenced by run().
windspeed
double const& windspeed private
Definition at line 91 of file ed_multilayer_canopy_properties.h.
Referenced by run().
windspeed_ops
std::vector<double*> const windspeed_ops private
Definition at line 107 of file ed_multilayer_canopy_properties.h.
Referenced by run().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_multilayer_canopy_properties.h