The BioCro C++ Library: standardBML Namespace Reference
standardBML Namespace Reference
This is the standard BioCro module library; it includes the essential modules used in typical BioCro crop growth simulations.
Namespaces
ed_nikolov_conductance_free_solve_stuff
ed_p_m_temperature_solve_stuff
Classes
class aba_decay
class ball_berry_module
class biomass_leaf_n_limitation
class buck_swvp
Determines the saturation water vapor pressure of atmospheric air using the saturation_vapor_pressure() function, which implements the Arden Buck equation.
class bucket_soil_drainage
class c3_assimilation
Calculates net assimilation, stomatal conductance, and intercellular CO2 concentration for a C3 leaf using c3photoC().
class c3_canopy
class c3_leaf_photosynthesis
Uses the method from c3CanAC() to calculate leaf photosynthesis parameters for C3 plants.
class c4_assimilation
Calculates net assimilation, stomatal conductance, and intercellular CO2 concentration for a C4 leaf using c4photoC().
class c4_canopy
class c4_leaf_photosynthesis
Uses the method from CanAC() to calculate leaf photosynthesis parameters for C4 plants.
class development_index
Calculates the development index (DVI) corresponding to plant growth rate.
class ed_abc_blc
This module is a wrapper for the leaf_boundary_layer_conductance_nikolov() (BLC) function in AuxBioCro (ABC). Currently only intended for use by Ed.
class ed_apply_stomatal_water_stress_via_conductance
Sets the water stress adjustment factors to apply the stomatal water stress only to the stomatal conductance. Currently only intended for use by Ed.
class ed_apply_stomatal_water_stress_via_assimilation
Sets the water stress adjustment factors to apply the stomatal water stress only to the stomatal conductance.
class ed_ball_berry
Uses the Ball-Berry equation to calculate stomatal conductance to water vapor. Currently only intended for use by Ed.
class ed_boundary_conductance_quadrature
Determines an overall value for the boundary layer conductance from the free and forced conductances. Currently only intended for use by Ed.
class ed_boundary_conductance_max
Determines an overall value for the boundary layer conductance from the free and forced conductances. Currently only intended for use by Ed.
class ed_c4_leaf_photosynthesis
Solves a set of modules for the unknown quantities assimilation_net, conductance_boundary_h2o_free, conductance_stomatal_h2o, and temperature_leaf. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
class ed_c4_leaf_photosynthesis2
Solves a set of modules for the unknown quantities assimilation_net, conductance_stomatal_h2o, and temperature_leaf. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
class ed_c4_leaf_photosynthesis3
Solves a set of modules for the unknown quantities assimilation_net and conductance_boundary_h2o_free. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
class ed_c4_leaf_photosynthesis4
Solves a set of modules for the unknown quantities assimilation_net, conductance_stomatal_h2o, and temperature_leaf. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
class ed_c4photo
Just a module wrapper for the c4photo() function. Currently only intended for use by Ed.
class ed_canac_leaf
Currently only intended for use by Ed.
class ed_collatz_c4_assimilation
Uses the equations from Collatz et. al (1992) to calculate the CO2 assimilation rate. Currently only intended for use by Ed.
class ed_evapotrans2
Just a module wrapper for the EvapoTrans2 function. Currently only intended for use by Ed.
class ed_gas_concentrations
Determines mole fractions of CO2 and H2O at several important locations. Currently only intended for use by Ed.
class ed_leaf_temperature
Calculates leaf temperature from energy balance without using the Penman-Monteith approximation. Currently only intended for use by Ed.
class ed_long_wave_energy_loss
Uses the Stefan-Boltzmann law to calculate long-wave energy losses from the leaf to the air. Currently only intended for use by Ed.
class ed_ten_layer_c4_canopy
A child class of multilayer_canopy_photosynthesis where:
class ed_multilayer_canopy_integrator
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part). Also includes multiple leaf classes (sunlit & shaded). Leaf class is added to output parameters as a prefix, while layer number is added as a suffix.
class ed_ten_layer_canopy_integrator
A child class of ed_multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory.
class ed_multilayer_canopy_properties
Calculates properties of each canopy layer using functions found in AuxBioCro (for the most part). Also includes multiple leaf classes (sunlit & shaded). Leaf class is added to output parameters as a prefix, while layer number is added as a suffix. Note that this module has a non-standard constructor, so it cannot be created using the module_factory.
class ed_ten_layer_canopy_properties
A child class of ed_multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory.
class ed_nikolov_conductance_forced
Calculates forced boundary layer conductance for water according to the model in Nikolov et al. Ecological Modelling 80, 205–235 (1995). Currently only intended for use by Ed.
class ed_nikolov_conductance_free
Calculates free boundary layer conductance for water according to the model in Nikolov et al. Ecological Modelling 80, 205–235 (1995). Note that this module has conductance_boundary_h2o_free as both an input and an output. Therefore, it can be used by a simultanous_equations object but not a dynamical_system object. Currently only intended for use by Ed.
class ed_nikolov_conductance_free_solve
Calculates free boundary layer conductance for water according to the model in Nikolov et al. Ecological Modelling 80, 205–235 (1995). Note that this module has conductance_boundary_h2o_free as both an input and an output. Therefore, it can be used by a simultanous_equations object but not a dynamical_system object. Currently only intended for use by Ed.
class ed_penman_monteith_leaf_temperature
Uses the Penman-Monteith equation to determine leaf temperature (see eq. 14.11e from Thornley (1990), p. 418). Currently only intended for use by Ed.
class ed_p_m_temperature_solve
Calculates leaf temperature using the Penman-Monteith equation, where boundary layer conductance is determined using the model from Nikolov et al. Currently only intended for use by Ed.
class ed_penman_monteith_transpiration
Uses the Penman-Monteith equation to determine leaf transpiration (see eq. 14.4k from Thornley (1990), p. 408). Currently only intended for use by Ed.
class ed_rh_to_mole_fraction
Just converts relative humidity values from weather data into atmospheric mole fractions of water vapor. Currently only intended for use by Ed.
class ed_stomata_water_stress_linear
Determine the stomata water stress factor. If the soil water content is below the wilting point, the stress factor takes its minimum value. If the water content is at or above the field capacity, the stress factor reaches its maximum of 1. Between the wilting point and the field capacity, the stress factor is determined by a straight line.
class ed_water_vapor_properties
Determines water vapor properties from the air temperature and atmospheric H2O mole fraction. Currently only intended for use by Ed.
class example_model_mass_gain
An example for the BioCro II manuscript.
class example_model_partitioning
An example for the BioCro II manuscript.
class fake_solar
Class created by EBL for testing and experimentation ... not meant for real simulations!
class FvCB
class grimm_soybean_flowering
Model for soybean development and flowering based on Grimm et al. (1993).
class grimm_soybean_flowering_calculator
Model for soybean development and flowering based on Grimm et al. (1993)
class harmonic_oscillator
class harmonic_energy
class golden_ratio_hyperbola
Represents a simple hyperbola defined by f(x) = 1 + 1 / x. Intended to be used as a simple test case for simultaneous eqation solvers. The solution to f(x) = x is x = (1 + sqrt(5))/2, the "golden ratio.".
class hyperbola_2d
Represents two 2D hyperbolas defined by f(x,y) = 1 + 1 / (x + y) and g(x,y) = 1 + 1 / (2x - y). Intended to be used as a simple test case for simultaneous equation solvers. One solution to f(x,y) = x, g(x,y) = y exists at x = -1.126529, y = 0.656279 (determined numerically).
class incident_shortwave_from_ground_par
Uses a value for total PAR flux density measured at the Earth's surface to calculate the total light flux density in the direct beam and as diffuse radiation in both the PAR and NIR bands.
class leaf_gbw_nikolov
Calculates the boundary layer conductance using the leaf_boundary_layer_conductance_nikolov() function.
class leaf_gbw_thornley
Calculates the boundary layer conductance using the leaf_boundary_layer_conductance_thornley() function.
class leaf_shape_factor
Determines the leaf shape factor k from the solar zenith angle and the leaf shape chi_l (expressed as the ratio between horizontal and vertical leaf elements, where chi = 0, 1, and infinity for horizontal, spherical, and vertical leaf distributions, respectively).
class leaf_water_stress_exponential
class light_from_solar
class linear_vmax_from_leaf_n
class magic_clock
class Module_1
class Module_2
class Module_3
class module_library
class ten_layer_c3_canopy
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Farquhar-von-Cammerer-Berry model for C3 photosynthesis; see the c3_leaf_photosynthesis class for more information about this model.
class ten_layer_c4_canopy
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Collatz et al. model for C4 photosynthesis; see the c4_leaf_photosynthesis class for more information about this model.
class multilayer_canopy_integrator
Calculates canopy-level values for assimilation and other quantities by adding the individual values from the sunlit and shaded leaves in each canopy layer, weighted by the relative fractions of sunlit and shaded leaves in each layer.
class ten_layer_canopy_integrator
A child class of multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_integrator.
class multilayer_canopy_photosynthesis
Applies a leaf photosynthesis module to each layer and leaf class of a multilayer canopy.
class multilayer_canopy_properties
Calculates environmental properties for sunlit and shaded leaves in each layer of a multilayer canopy, mostly using functions found in AuxBioCro.cpp.
class ten_layer_canopy_properties
A child class of multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_properties.
class ten_layer_rue_canopy
Represents a ten layer canopy where leaf-level photosynthesis is calculated using a simple radiation use efficiency (RUE) model; see the rue_leaf_photosynthesis class for more information about this model.
class night_and_day_trackers
class no_leaf_resp_neg_assim_partitioning_growth_calculator
Uses a set of partitioning coefficients to determine net assimilation rates due to photosynthesis and respiration for several plant organs.
class no_leaf_resp_partitioning_growth_calculator
Uses a set of partitioning coefficients to determine net assimilation rates due to photosynthesis and respiration for several plant organs.
class nr_ex
class one_layer_soil_profile
class one_layer_soil_profile_derivatives
class oscillator_clock_calculator
class parameter_calculator
class partitioning_coefficient_logistic
Calculates carbon partitioning coefficients based on logistic-based functions and development index using the logistic-based functions from Osborne et al 2015.
class partitioning_coefficient_selector
class partitioning_growth
This module determines the growth rate for several plant organs from the net rate of carbon assimilation due to photosynthesis (determined by a "partitioning growth calculator" module) and any additional carbon that may come from retranslocation.
class partitioning_growth_calculator
Uses a set of partitioning coefficients to determine net assimilation rates due to photosynthesis and respiration for several plant organs.
class penman_monteith_leaf_temperature
class penman_monteith_transpiration
class phase_clock
class poincare_clock
class pokhilko_circadian_clock
class priestley_transpiration
class rasmussen_specific_heat
Determines the specific heat capacity of atmospheric air at constant pressure using the rasmussen_specific_heat_of_air() function.
class rh_to_mole_fraction
Converts atmospheric relative humidity into a water vapor concentration expressed as a dimensionless mole fraction.
class rue_leaf_photosynthesis
Calculates leaf photosynthesis parameters using a simple radiation use efficiency (RUE) model where gross CO2 assimilation is assumed to be directly proportional to the incident photosynthetically active photon flux density (PPFD).
class senescence_coefficient_logistic
Calculates coefficients representing fraction of biomass senesced for each organ; coefficents are represented as a logistic functions depending on development index.
class senescence_logistic
Calculates the change in plant organ biomasses due to senescence.
class shortwave_atmospheric_scattering
Calculates the amount of sunlight scattered out of the direct beam by the atmosphere. The result is expressed in two ways: as atmospheric transmittances (which would be appropriate for calculating the intensity of direct and diffuse light at the surface given a value for the solar constant) or as a fraction (which would be appropriate for calculating the intensity of direct and diffuse light given an experimental measurement of light intensity at the surface).
class soil_evaporation
class solar_position_michalsky
Calculates the solar position using the model described in <a href="https://doi.org/10.1016/0038-092X(88)90045-X".
class song_flowering
class soybean_development_rate_calculator
Determines hourly soybean developments rate using photothermal functions.
class stomata_water_stress_exponential
class stomata_water_stress_linear
class stomata_water_stress_linear_and_aba_response
class stomata_water_stress_sigmoid
class thermal_time_and_frost_senescence
Determines senescence rates for several plant organs based on thermal time thresholds, the occurrence of frost, and magical time travel; only compatible with a fixed-step Euler solver.
class thermal_time_beta
Calculates the rate of thermal time accumulation using a beta distribution function.
class thermal_time_bilinear
Calculates the rate of thermal time accumulation using a bilinear model.
class thermal_time_development_rate_calculator
Calculates hourly plant development rate based on thermal time ranges of emergence, vegetative, and reproductive growth stages.
class thermal_time_linear
Calculates the rate of thermal time accumulation using a linear model.
class thermal_time_linear_extended
Calculates the rate of thermal time accumulation using an extended linear model.
class thermal_time_senescence
Determines senescence rates for several plant organs based on thermal time thresholds and magical time travel; only compatible with a fixed-step Euler solver.
class thermal_time_trilinear
Calculates the rate of thermal time accumulation using a trilinear model.
class total_biomass
Calculates the total biomass by adding together the masses of the Leaf, Stem, Root, Rhizome, and Grain tissues.
class two_layer_soil_profile
class utilization_growth
The utilization growth model is based on several papers published by Thornley and is implemented in BioCro via two separate modules; this module returns derivatives for the plant tissue mass state variables.
class utilization_growth_calculator
The utilization growth model is based on several papers published by Thornley and is implemented in BioCro via two separate modules; this module calculates utilization and transport rates for different plant tissue types.
class utilization_senescence
class utilization_senescence_calculator
class water_vapor_properties_from_air_temperature
Typedefs
using ten_layer_c3_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c3_leaf_photosynthesis >
using ten_layer_c4_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis >
using ten_layer_rue_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, rue_leaf_photosynthesis >
Functions
double range_adjusted_atan2 (double y, double x)
double kcoeff (double alpha, double beta, double DVI, double denom)
double ksene (double rate, double alpha, double beta, double DVI)
double photoFunc (double P, double Popt, double Pcrit)
double tempFunc (double T, double Tmin, double Topt, double Tmax)
double utilization_hill (double KM, double n, double concentration)
Detailed Description
This is the standard BioCro module library; it includes the essential modules used in typical BioCro crop growth simulations.
Typedef Documentation
ten_layer_c3_canopy_parent
using ten_layer_c3_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c3_leaf_photosynthesis>
Definition at line 11 of file multilayer_c3_canopy.h.
ten_layer_c4_canopy_parent
using ten_layer_c4_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, c4_leaf_photosynthesis>
Definition at line 11 of file multilayer_c4_canopy.h.
ten_layer_rue_canopy_parent
using ten_layer_rue_canopy_parent = multilayer_canopy_photosynthesis< ten_layer_canopy_properties, rue_leaf_photosynthesis>
Definition at line 11 of file multilayer_rue_canopy.h.
Function Documentation
kcoeff()
double kcoeff (double alpha, double beta, double DVI, double denom)
Definition at line 158 of file partitioning_coefficient_logistic.h.
References partitioning_coefficient_logistic::DVI.
Referenced by partitioning_coefficient_logistic::do_operation().
ksene()
double ksene (double rate, double alpha, double beta, double DVI)
Definition at line 154 of file senescence_coefficient_logistic.h.
References senescence_coefficient_logistic::DVI.
Referenced by senescence_coefficient_logistic::do_operation().
photoFunc()
double photoFunc (double P, double Popt, double Pcrit)
Definition at line 240 of file soybean_development_rate_calculator.h.
Referenced by soybean_development_rate_calculator::do_operation().
range_adjusted_atan2()
double standardBML::range_adjusted_atan2 (double y, double x) inline
This is like atan2 but with a range of [0, 2pi) instead of (-pi, pi]: When the point (x, y) is in the third or fourth quadrant (i.e., when y < 0), add 2pi to the value in (-pi, 0) returned by atan2 so that dawn_phase is always in the interval [0, 2pi).
Definition at line 118 of file oscillator_clock_calculator.hpp.
Referenced by oscillator_clock_calculator::do_operation().
tempFunc()
double tempFunc (double T, double Tmin, double Topt, double Tmax)
Definition at line 222 of file soybean_development_rate_calculator.h.
Referenced by soybean_development_rate_calculator::do_operation().
utilization_hill()
double standardBML::utilization_hill (double KM, double n, double concentration) inline
Definition at line 179 of file utilization_growth_calculator.hpp.
Referenced by utilization_growth_calculator::do_operation().