The BioCro C++ Library: /github/workspace/src/module_library/CanAC.cpp File Reference
CanAC.cpp File Reference
#include "CanAC.h"
#include "BioCro.h"
#include "c4photo.h"
#include "lightME.h"
#include "sunML.h"
#include "../framework/constants.h"
Functions
canopy_photosynthesis_outputs CanAC (double LAI, double cosine_zenith_angle, double solarR, double ambient_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const nitroParms &nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw)
Function Documentation
CanAC()
canopy_photosynthesis_outputs CanAC (double LAI, double cosine_zenith_angle, double solarR, double ambient_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double leafN, double kpLN, int lnfun, double upperT, double lowerT, const nitroParms & nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw)
Definition at line 8 of file CanAC.cpp.
References nitroParms::alphab0, nitroParms::alphab1, canopy_photosynthesis_outputs::Assim, photosynthesis_outputs::Assim, Light_profile::average_absorbed_shortwave, ET_Str::boundary_layer_conductance, c4photoC(), canopy_photosynthesis_outputs::canopy_conductance, canopy_photosynthesis_outputs::canopy_transpiration_penman, canopy_photosynthesis_outputs::canopy_transpiration_priestly, ET_Str::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, ET_Str::EPenman, ET_Str::EPriestly, EvapoTrans2(), canopy_photosynthesis_outputs::GrossAssim, photosynthesis_outputs::GrossAssim, photosynthesis_outputs::Gs, lightME(), LNprof(), physical_constants::molar_mass_of_glucose, physical_constants::molar_mass_of_water, nitroParms::Rdb0, nitroParms::Rdb1, canopy_photosynthesis_outputs::Rp, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, sunML(), canopy_photosynthesis_outputs::Trans, ET_Str::TransR, nitroParms::Vmaxb0, nitroParms::Vmaxb1, and WINDprof().
Referenced by c4_canopy::do_operation().