The BioCro C++ Library: /github/workspace/src/R_run_biocro.cpp File Reference
R_run_biocro.cpp File Reference
#include <string>
#include <exception>
#include <Rinternals.h>
#include "framework/R_helper_functions.h"
#include "framework/state_map.h"
#include "framework/module_creator.h"
#include "framework/biocro_simulation.h"
#include "R_run_biocro.h"
Functions
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Function Documentation
R_run_biocro()
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Definition at line 14 of file R_run_biocro.cpp.
References biocro_simulation::generate_report(), list_from_map(), map_from_list(), map_vector_from_list(), mc_vector_from_list(), and biocro_simulation::run_simulation().