The BioCro C++ Library: /github/workspace/src/R_module_library.h File Reference
R_module_library.h File Reference
#include <Rinternals.h>
Functions
SEXP R_module_creators (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_creator object; this function provides a route for creating C++ objects from R strings.
SEXP R_get_all_modules ()
A wrapper for module_factory::get_all_modules() that returns the output as an R vector of R strings.
SEXP R_get_all_quantities ()
A wrapper for module_factory::get_all_quantities() that returns the output as an R list of named R strings.
Function Documentation
R_get_all_modules()
SEXP R_get_all_modules ()
A wrapper for module_factory::get_all_modules() that returns the output as an R vector of R strings.
Definition at line 91 of file R_module_library.cpp.
References module_factory< T >::get_all_modules(), and r_string_vector_from_vector().
R_get_all_quantities()
SEXP R_get_all_quantities ()
A wrapper for module_factory::get_all_quantities() that returns the output as an R list of named R strings.
Definition at line 108 of file R_module_library.cpp.
References module_factory< T >::get_all_quantities(), and list_from_map().
R_module_creators()
SEXP R_module_creators (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_creator object; this function provides a route for creating C++ objects from R strings.
See http://www.hep.by/gnu/r-patched/r-exts/R-exts_122.html for more details about R external pointers.
When creating an R external pointer using R_MakeExternalPtr(), it is possible to specify tag and prot arguments for identifying the pointer and protecting its memory. However, it is common to bypass both of these arguments by setting them to R_NilValue (the R null pointer). We follow that route here.
Once an R external pointer has been created, it is also possible to specify a "finalizer" function via R_RegisterFinalizerEx(). This function will be called when garbage is collected and should clear the pointer. By setting the onexit argument of R_RegisterFinalizerEx() to be TRUE, we ensure that the pointer will be cleared when its R session closes.
After its creation, the R external pointer takes ownership of the module_creator object, so there is no need to use smart pointers here.
The output from this function can be converted into a std::vector of module_creator pointers (in other words, an mc_vector) for use in C/C++ code using the mc_vector_from_list() function.
Parameters
[in] module_names The names of the modules for which module_creator objects should be created
Returns
A vector of "R external pointer" objects
Definition at line 54 of file R_module_library.cpp.
References finalize_module_creator(), make_vector(), and module_factory< T >::retrieve().