The BioCro C++ Library: /github/workspace/src/framework/R_helper_functions.h File Reference
R_helper_functions.h File Reference
#include <Rinternals.h>
#include <string>
#include "module_creator.h"
#include "state_map.h"
Functions
state_map map_from_list (SEXP const &list)
state_vector_map map_vector_from_list (SEXP const &list)
string_vector make_vector (SEXP const &r_string_vector)
mc_vector mc_vector_from_list (SEXP const &list)
Creates a std::vector of pointers to module_creator objects from an R vector of R external pointer objects.
SEXP list_from_map (state_map const &m)
SEXP list_from_map (state_vector_map const &m)
SEXP list_from_map (std::unordered_map< std::string, string_vector > const &m)
SEXP list_from_module_info (std::string const &module_name, string_vector const &module_inputs, string_vector const &module_outputs, bool const &is_differential, bool const &requires_euler_ode_solver, std::string const &creation_error_message)
SEXP vector_from_map (state_map const &m)
SEXP r_string_vector_from_vector (string_vector const &v)
SEXP r_logical_from_boolean (bool b)
void output_map (state_map const &m)
void output_list (SEXP const &list)
void finalize_module_creator (SEXP mw_ptr)
Deletes a module_creator object that is pointed to by an "R external pointer" object.
Function Documentation
finalize_module_creator()
void finalize_module_creator (SEXP mw_ptr)
Deletes a module_creator object that is pointed to by an "R external pointer" object.
See http://www.hep.by/gnu/r-patched/r-exts/R-exts_122.html for more details.
Parameters
[in] m_ptr an "R external pointer" object that points to a module_creator object
Definition at line 311 of file R_helper_functions.cpp.
Referenced by R_module_creators().
list_from_map() [1/3]
SEXP list_from_map (state_map const & m)
Definition at line 119 of file R_helper_functions.cpp.
Referenced by R_evaluate_module(), R_get_all_quantities(), R_run_biocro(), and R_system_derivatives().
list_from_map() [2/3]
SEXP list_from_map (state_vector_map const & m)
Definition at line 134 of file R_helper_functions.cpp.
list_from_map() [3/3]
SEXP list_from_map (std::unordered_map< std::string, string_vector > const & m)
list_from_module_info()
SEXP list_from_module_info (std::string const & module_name, string_vector const & module_inputs, string_vector const & module_outputs, bool const & is_differential, bool const & requires_euler_ode_solver, std::string const & creation_error_message)
Definition at line 181 of file R_helper_functions.cpp.
References r_string_vector_from_vector().
Referenced by R_module_info().
make_vector()
string_vector make_vector (SEXP const & r_string_vector)
Definition at line 77 of file R_helper_functions.cpp.
Referenced by R_module_creators().
map_from_list()
state_map map_from_list (SEXP const & list)
Definition at line 46 of file R_helper_functions.cpp.
Referenced by R_evaluate_module(), R_run_biocro(), R_system_derivatives(), and R_validate_dynamical_system_inputs().
map_vector_from_list()
state_vector_map map_vector_from_list (SEXP const & list)
Definition at line 58 of file R_helper_functions.cpp.
Referenced by R_run_biocro(), R_system_derivatives(), and R_validate_dynamical_system_inputs().
mc_vector_from_list()
mc_vector mc_vector_from_list (SEXP const & list)
Creates a std::vector of pointers to module_creator objects from an R vector of R external pointer objects.
Parameters
[in] list An R vector of R external pointer objects, typically created by a call to R_module_creators()
Returns
A std::vector of pointers to module_creator objects
Definition at line 97 of file R_helper_functions.cpp.
Referenced by R_evaluate_module(), R_module_info(), R_run_biocro(), R_system_derivatives(), and R_validate_dynamical_system_inputs().
output_list()
void output_list (SEXP const & list)
Definition at line 283 of file R_helper_functions.cpp.
output_map()
void output_map (state_map const & m)
Definition at line 267 of file R_helper_functions.cpp.
r_logical_from_boolean()
SEXP r_logical_from_boolean (bool b)
Definition at line 259 of file R_helper_functions.cpp.
Referenced by R_validate_dynamical_system_inputs().
r_string_vector_from_vector()
SEXP r_string_vector_from_vector (string_vector const & v)
Definition at line 108 of file R_helper_functions.cpp.
Referenced by list_from_module_info(), R_get_all_modules(), and R_get_all_ode_solvers().
vector_from_map()
SEXP vector_from_map (state_map const & m)
Definition at line 243 of file R_helper_functions.cpp.