The BioCro C++ Library: multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type > Class Template Reference
multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type > Class Template Reference
Applies a leaf photosynthesis module to each layer and leaf class of a multilayer canopy.
#include <multilayer_canopy_photosynthesis.h>
Public Member Functions
multilayer_canopy_photosynthesis (const int &nlayers, state_map const &input_quantities, state_map *output_quantities)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Protected Member Functions
void run () const
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
virtual void update (double *output_ptr, const double &value) const =0
Static Protected Member Functions
static string_vector generate_inputs (int nlayers)
static string_vector generate_outputs (int nlayers)
Private Attributes
const int nlayers
state_map leaf_module_quantities
state_map leaf_module_output_map
std::unique_ptr< module > leaf_module
std::vector< std::vector< std::pair< double *, const double * > > > leaf_input_ptr_pairs
std::vector< std::vector< std::pair< double *, const double * > > > leaf_output_ptr_pairs
Detailed Description
template<typename canopy_module_type, typename leaf_module_type>
class standardBML::multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
Applies a leaf photosynthesis module to each layer and leaf class of a multilayer canopy.
Basic overview
Two modules must be specified as template arguments:
canopy properties module: a module that calculates properties for each canopy layer and leaf class
leaf photosynthesis module: a module that determines assimilation values (among other values)
The canopy properties module must have the following public static methods:
define_leaf_classes()
define_multiclass_multilayer_outputs()
define_pure_multilayer_outputs()
More operational details
In general, a canopy can be divided into different layers and leaf classes, which could be based on factors such as angle or age. The canopy properties module should determine the values of any properties (e.g. air temperature or incident light intensity) that may vary between layers and/or leaf classes.
The values of these quantities must be subsequently passed to a leaf-level photosynthesis module in order to determine assimilation rates for each type of leaf in the canopy. In order to correctly pair a photosynthesis input quantity (such as incident_par) with a corresponding value for a layer and leaf class (such as sunlit_incident_par_layer_0), this module needs to know which quantities depend on canopy layer and leaf class. For that reason, the canopy properties module must have the following methods defined:
define_leaf_classes(): specifies each leaf class
define_multiclass_multilayer_outputs(): specifies the base names for quantities that change with canopy layer and leaf class
define_pure_multilayer_outputs(): specifies the base names for quantities that change with canopy layer but not leaf class
The layer- and class-dependent names of these quantities are formed from a base name (e.g. incident_par), a prefix that indicates the leaf class (e.g. sunlit_), and a suffix that indicates the layer number (e.g. _layer_0).
Note that this module has a non-standard constructor, so it cannot be created using the module_factory. Rather, it is expected that directly-usable classes will be derived from this class.
Definition at line 156 of file multilayer_canopy_photosynthesis.h.
Constructor & Destructor Documentation
multilayer_canopy_photosynthesis()
multilayer_canopy_photosynthesis (const int & nlayers, state_map const & input_quantities, state_map * output_quantities)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Definition at line 191 of file multilayer_canopy_photosynthesis.h.
References add_class_prefix_to_quantity_name(), add_layer_suffix_to_quantity_name(), get_ip(), get_op(), multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::leaf_input_ptr_pairs, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::leaf_module, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::leaf_module_output_map, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::leaf_module_quantities, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::leaf_output_ptr_pairs, and multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::nlayers.
Member Function Documentation
generate_inputs()
string_vector generate_inputs (int nlayers) static protected
Definition at line 296 of file multilayer_canopy_photosynthesis.h.
References generate_multiclass_quantity_names(), and generate_multilayer_quantity_names().
Referenced by ten_layer_c3_canopy::get_inputs(), ten_layer_c4_canopy::get_inputs(), and ten_layer_rue_canopy::get_inputs().
generate_outputs()
string_vector generate_outputs (int nlayers) static protected
Definition at line 327 of file multilayer_canopy_photosynthesis.h.
References generate_multiclass_quantity_names(), and generate_multilayer_quantity_names().
Referenced by ten_layer_c3_canopy::get_outputs(), ten_layer_c4_canopy::get_outputs(), and ten_layer_rue_canopy::get_outputs().
run()
void run protected
Definition at line 338 of file multilayer_canopy_photosynthesis.h.
Referenced by ten_layer_c3_canopy::do_operation(), ten_layer_c4_canopy::do_operation(), and ten_layer_rue_canopy::do_operation().
Member Data Documentation
leaf_input_ptr_pairs
std::vector<std::vector<std::pair<double*, const double*> > > leaf_input_ptr_pairs private
Definition at line 174 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
leaf_module
std::unique_ptr<module> leaf_module private
Definition at line 171 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
leaf_module_output_map
state_map leaf_module_output_map private
Definition at line 170 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
leaf_module_quantities
state_map leaf_module_quantities private
Definition at line 169 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
leaf_output_ptr_pairs
std::vector<std::vector<std::pair<double*, const double*> > > leaf_output_ptr_pairs private
Definition at line 177 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
nlayers
const int nlayers private
Definition at line 166 of file multilayer_canopy_photosynthesis.h.
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/multilayer_canopy_photosynthesis.h