The BioCro C++ Library: ten_layer_c3_canopy Class Reference
ten_layer_c3_canopy Class Reference
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Farquhar-von-Cammerer-Berry model for C3 photosynthesis; see the c3_leaf_photosynthesis class for more information about this model.
#include <multilayer_c3_canopy.h>
Public Member Functions
ten_layer_c3_canopy (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
multilayer_canopy_photosynthesis (const int &nlayers, state_map const &input_quantities, state_map *output_quantities)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Static Private Attributes
static int const nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
void run () const
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
virtual void update (double *output_ptr, const double &value) const =0
Static Protected Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
static string_vector generate_inputs (int nlayers)
static string_vector generate_outputs (int nlayers)
Detailed Description
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Farquhar-von-Cammerer-Berry model for C3 photosynthesis; see the c3_leaf_photosynthesis class for more information about this model.
More specifically, this is a child class of multilayer_canopy_photosynthesis where:
The canopy module is set to the ten_layer_canopy_properties module
The leaf module is set to the c3_leaf_photosynthesis module
The number of layers is set to 10
Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_photosynthesis.
Definition at line 35 of file multilayer_c3_canopy.h.
Constructor & Destructor Documentation
ten_layer_c3_canopy()
ten_layer_c3_canopy (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 38 of file multilayer_c3_canopy.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements module.
Definition at line 24 of file multilayer_c3_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::run().
get_inputs()
string_vector get_inputs () static
Definition at line 8 of file multilayer_c3_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), and ten_layer_c3_canopy::nlayers.
get_name()
static std::string get_name () inline static
Definition at line 49 of file multilayer_c3_canopy.h.
get_outputs()
string_vector get_outputs () static
Definition at line 16 of file multilayer_c3_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), and ten_layer_c3_canopy::nlayers.
Member Data Documentation
nlayers
int const nlayers = 10 static private
Definition at line 53 of file multilayer_c3_canopy.h.
Referenced by ten_layer_c3_canopy::get_inputs(), and ten_layer_c3_canopy::get_outputs().
The documentation for this class was generated from the following files:
/github/workspace/src/module_library/multilayer_c3_canopy.h
/github/workspace/src/module_library/multilayer_c3_canopy.cpp