The BioCro C++ Library: /github/workspace/src/framework/degree_trigonometry.h File Reference
degree_trigonometry.h File Reference
#include <cmath>
#include "constants.h"
Functions
double sin_deg (double angle)
double cos_deg (double angle)
double tan_deg (double angle)
double asin_deg (double arg)
double acos_deg (double arg)
double atan2_deg (double y, double x)
Function Documentation
acos_deg()
double acos_deg (double arg)
Definition at line 29 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
asin_deg()
double asin_deg (double arg)
Definition at line 24 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
atan2_deg()
double atan2_deg (double y, double x)
Definition at line 34 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
cos_deg()
double cos_deg (double angle)
Definition at line 14 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
sin_deg()
double sin_deg (double angle)
Definition at line 9 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
tan_deg()
double tan_deg (double angle)
Definition at line 19 of file degree_trigonometry.h.