The BioCro C++ Library: /github/workspace/src/framework/module_helper_functions.h File Reference
module_helper_functions.h File Reference
#include <stdexcept>
#include <map>
#include <vector>
#include "state_map.h"
Classes
class quantity_access_error
Custom error class to indicate problems when accessing a quantity.
Functions
double * get_op (state_map *output_quantities, std::string const &name)
Returns a pointer to an element of a module output map, i.e., an output pointer (op)
std::vector< double * > get_op (state_map *output_quantities, string_vector const &names)
Returns a vector of pointers to elements of a module output map, i.e., a vector of output pointers (op)
const double * get_ip (state_map const &input_quantities, std::string const &name)
Returns a pointer to an element of a module input map, i.e., an input pointer (ip)
std::vector< const double * > get_ip (state_map const &input_quantities, string_vector const &names)
Returns a vector of pointers to elements of a module input map, i.e., a vector of input pointers (ip)
double const & get_input (state_map const &input_quantities, const std::string &name)
Returns a reference to an element of a module input map.
std::string add_class_prefix_to_quantity_name (std::string class_name, std::string quantity_name)
Adds a class name prefix to the quantity name indicating it was calculated for a certain leaf class, e.g. sunlit or shaded.
string_vector generate_multiclass_quantity_names (string_vector class_names, string_vector quantity_names)
Adds class name prefixes to each quantity name indicating that it was calculated for a certain class. E.g., a multilayer canopy model may calculate different incident light irradiance values for sunlit and shaded leaves. In this case, "sunlit" and "shaded" would be the two leaf classes.
std::string add_layer_suffix_to_quantity_name (int nlayers, int current_layer, std::string quantity_name)
Adds a suffix to a quantity name indicating that it was calculated for a certain layer.
string_vector generate_multilayer_quantity_names (int nlayers, string_vector quantity_names)
For each entry in the quantity_names vector, multiple copies are produced, each of which has a suffix indicating the corresponding layer.
std::vector< double * > get_multilayer_op (state_map *output_quantities, int nlayers, std::string const &name)
Analagous to get_op but returns a vector of output pointers, as required for a multilayer module.
std::vector< const double * > get_multilayer_ip (state_map const &input_quantities, int nlayers, std::string const &name)
Analagous to get_ip but returns a vector of output pointers, as required for a multilayer module.
void check_error_conditions (std::map< std::string, bool > errors_to_check, std::string module_name)
Checks over an error_map for problems. The error_map should pair a string description of an important criterion which must be met, e.g. "Parameter_A must be non-zero", with a boolean indicating whether it has been met. If the condition was not met, an appropriate error message will be generated indicating both the problem and the module in which it occurred.
Function Documentation
add_class_prefix_to_quantity_name()
std::string add_class_prefix_to_quantity_name (std::string class_name, std::string quantity_name)
Adds a class name prefix to the quantity name indicating it was calculated for a certain leaf class, e.g. sunlit or shaded.
Definition at line 80 of file module_helper_functions.cpp.
Referenced by generate_multiclass_quantity_names(), and multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
add_layer_suffix_to_quantity_name()
std::string add_layer_suffix_to_quantity_name (int nlayers, int current_layer, std::string quantity_name)
Adds a suffix to a quantity name indicating that it was calculated for a certain layer.
Definition at line 109 of file module_helper_functions.cpp.
Referenced by generate_multilayer_quantity_names(), and multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
check_error_conditions()
void check_error_conditions (std::map< std::string, bool > errors_to_check, std::string module_name)
Checks over an error_map for problems. The error_map should pair a string description of an important criterion which must be met, e.g. "Parameter_A must be non-zero", with a boolean indicating whether it has been met. If the condition was not met, an appropriate error message will be generated indicating both the problem and the module in which it occurred.
Definition at line 190 of file module_helper_functions.cpp.
Referenced by incident_shortwave_from_ground_par::do_operation(), and rh_to_mole_fraction::do_operation().
generate_multiclass_quantity_names()
string_vector generate_multiclass_quantity_names (string_vector class_names, string_vector quantity_names)
Adds class name prefixes to each quantity name indicating that it was calculated for a certain class. E.g., a multilayer canopy model may calculate different incident light irradiance values for sunlit and shaded leaves. In this case, "sunlit" and "shaded" would be the two leaf classes.
Definition at line 92 of file module_helper_functions.cpp.
References add_class_prefix_to_quantity_name().
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), and multilayer_canopy_properties::get_outputs().
generate_multilayer_quantity_names()
string_vector generate_multilayer_quantity_names (int nlayers, string_vector quantity_names)
For each entry in the quantity_names vector, multiple copies are produced, each of which has a suffix indicating the corresponding layer.
Definition at line 131 of file module_helper_functions.cpp.
References add_layer_suffix_to_quantity_name().
Referenced by multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), multilayer_canopy_integrator::get_inputs(), get_multilayer_ip(), get_multilayer_op(), and multilayer_canopy_properties::get_outputs().
get_input()
double const & get_input (state_map const & input_quantities, const std::string & name)
Returns a reference to an element of a module input map.
Definition at line 65 of file module_helper_functions.cpp.
get_ip() [1/2]
const double * get_ip (state_map const & input_quantities, std::string const & name)
Returns a pointer to an element of a module input map, i.e., an input pointer (ip)
Definition at line 38 of file module_helper_functions.cpp.
Referenced by get_ip(), get_multilayer_ip(), and multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
get_ip() [2/2]
std::vector< const double * > get_ip (state_map const & input_quantities, string_vector const & names)
Returns a vector of pointers to elements of a module input map, i.e., a vector of input pointers (ip)
Definition at line 52 of file module_helper_functions.cpp.
References get_ip().
get_multilayer_ip()
std::vector< const double * > get_multilayer_ip (state_map const & input_quantities, int nlayers, std::string const & name)
Analagous to get_ip but returns a vector of output pointers, as required for a multilayer module.
Definition at line 168 of file module_helper_functions.cpp.
References generate_multilayer_quantity_names(), and get_ip().
get_multilayer_op()
std::vector< double * > get_multilayer_op (state_map * output_quantities, int nlayers, std::string const & name)
Analagous to get_op but returns a vector of output pointers, as required for a multilayer module.
Definition at line 149 of file module_helper_functions.cpp.
References generate_multilayer_quantity_names(), and get_op().
get_op() [1/2]
double * get_op (state_map * output_quantities, std::string const & name)
Returns a pointer to an element of a module output map, i.e., an output pointer (op)
Definition at line 10 of file module_helper_functions.cpp.
Referenced by get_multilayer_op(), get_op(), and multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::multilayer_canopy_photosynthesis().
get_op() [2/2]
std::vector< double * > get_op (state_map * output_quantities, string_vector const & names)
Returns a vector of pointers to elements of a module output map, i.e., a vector of output pointers (op)
Definition at line 24 of file module_helper_functions.cpp.
References get_op().