The BioCro C++ Library: /github/workspace/src/module_library/c3photo.h File Reference
c3photo.h File Reference
#include "photosynthesis_outputs.h"
Functions
photosynthesis_outputs c3photoC (double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const bb0, double const bb1, double const Gs_min, double Ca, double const AP, double const O2, double const thet, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw)
double solc (double LeafT)
double solo (double LeafT)
Function Documentation
c3photoC()
photosynthesis_outputs c3photoC (double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const bb0, double const bb1, double const Gs_min, double Ca, double const AP, double const O2, double const thet, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw)
Definition at line 17 of file c3photo.cpp.
References FvCB_outputs::An, arrhenius_exponential(), photosynthesis_outputs::Assim, ball_berry_gs(), conductance_limited_assim(), stomata_outputs::cs, FvCB_assim(), stomata_outputs::gsw, stomata_outputs::hs, solo(), and FvCB_outputs::Vc.
Referenced by c3CanAC(), c3_assimilation::do_operation(), and c3_leaf_photosynthesis::do_operation().
solc()
double solc (double LeafT)
solo()
double solo (double LeafT)
Definition at line 198 of file c3photo.cpp.
Referenced by c3photoC().