The BioCro C++ Library: /github/workspace/src/module_library/conductance_limited_assim.h File Reference
conductance_limited_assim.h File Reference
#include "../framework/constants.h"
Functions
double conductance_limited_assim (double Ca, double gbw, double gsw)
Computes the conductance-limited net CO2 assimilation rate.
Function Documentation
conductance_limited_assim()
double conductance_limited_assim (double Ca, double gbw, double gsw) inline
Computes the conductance-limited net CO2 assimilation rate.
The flow of CO2 from the atmosphere to the intercellular air spaces is modeled using a simple one-dimensional flux equation:
\[ A_n = g_{tc} \cdot \left(C_a - C_i \right), \qquad \text{(1)} \]
where \(A_n \) is the net CO2 assimilation rate, \(g_{tc} \) is the total conductance to CO2 diffusion across the boundary layer and through the stomata, \(C_a \) is the atmospheric CO2 concentration, and \(C_i \) is the CO2 concentration in the intercellular air spaces. Here, \(C_i \) cannot be negative, since it is not possible to have a negative number of CO2 molecules in a gas mixture; this places a restriction on the maximum value that \(A_n \) can take, since very large values would require \(C_i < 0 \) in Equation (1).
To derive this restriction, we first solve Equation (1) for \(Ci \):
\[ C_i = C_a - A_n / g_{tc}. \qquad \text{(2)} \]
Now, if \(C_i = 0 \) when \(A_n = A_n^{max} \), where \(A_n^{max} \) is the maximum assimilation rate limited by CO2 conductance, we can use Equation (2) to solve for \(A_n^{max} \):
\[ A_n^{max} = C_a \cdot g_{tc}. \qquad \text{(3)} \]
Finally, we note that the total conductance to CO2 diffusion can be calculated from the boundary layer conductance to H2O diffusion (\(g_{bw} \)) and the stomatal conductance to H2O diffusion (\(g_{sw} \)) according to
\[ \frac{1}{g_{tc}} = \frac{DR_b}{g_{bw}} + \frac{DR_s}{g_{sw}}, \qquad \text{(4)} \]
where \(DR_b \) is the ratio of diffusivities of H20 and CO2 in the boundary layer and \(DR_s \) is the same ratio in the stomata. Combining Equations (3) and (4), we have:
\[ A_n^{max} = \frac{C_a}{\frac{DR_b}{g_{bw}} + \frac{DR_s}{g_{sw}}}. \qquad \text{(5)} \]
This function implements Equation (5).
Parameters
[in] Ca The atmospheric CO2 concentration expressed as a mole fraction with units of micromol / mol.
[in] gbw The conductance to H2O diffusion in the boundary layer with units of mol / m^2 / s. For an isolated leaf, this should be the leaf boundary layer conductance; for a leaf within a canopy, this should be the total conductance including the leaf and canopy boundary layer conductances.
[in] gsw The conductance to H2O diffusion in the stomata with units of mol / m^2 / s.
Returns
The conductance-limited net CO2 assimilation rate in units of micromol / m^2 / s.
Definition at line 69 of file conductance_limited_assim.h.
Referenced by c3photoC(), c4photoC(), and rue_photo().