The BioCro C++ Library: /github/workspace/src/module_library/rue_leaf_photosynthesis.cpp File Reference
rue_leaf_photosynthesis.cpp File Reference
#include <algorithm>
#include <cmath>
#include "ball_berry_gs.h"
#include "BioCro.h"
#include "AuxBioCro.h"
#include "photosynthesis_outputs.h"
#include "conductance_limited_assim.h"
#include "../framework/constants.h"
#include "rue_leaf_photosynthesis.h"
Functions
photosynthesis_outputs rue_photo (double Qp, double alpha_rue, double Tleaf, double RH, double Rd0, double bb0, double bb1, double Ca, double gbw)
Function Documentation
rue_photo()
photosynthesis_outputs rue_photo (double Qp, double alpha_rue, double Tleaf, double RH, double Rd0, double bb0, double bb1, double Ca, double gbw)
Definition at line 22 of file rue_leaf_photosynthesis.cpp.
References arrhenius_exponential(), photosynthesis_outputs::Assim, ball_berry_gs(), conductance_limited_assim(), stomata_outputs::cs, stomata_outputs::gsw, and stomata_outputs::hs.
Referenced by rue_leaf_photosynthesis::do_operation().