The BioCro C++ Library: /github/workspace/src/module_library/AuxBioCro.h File Reference
AuxBioCro.h File Reference
#include <map>
#include "../framework/constants.h"
Classes
struct ET_Str
struct ws_str
struct soilML_str
struct dbp_str
struct seqRD_str
struct rd_str
struct frostParms
struct nitroParms
struct crop_phenology
struct crop_phenology::minerals1
Macros
#define MAXLAY 200 /* Maximum number of layers */
Functions
seqRD_str seqRootDepth (double to, int lengthOut)
rd_str rootDist (int layer, double rootDepth, double *depths, double rfl)
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Nikolov, Massman, and Schoettle (1995).
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Thornley and Johnson (1990).
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double *leafNla)
double arrhenius_exponential (double c, double activation_energy, double temperature)
Calculates the exponential term of the Arrhenius equation.
Macro Definition Documentation
MAXLAY
#define MAXLAY 200 /* Maximum number of layers */
Definition at line 12 of file AuxBioCro.h.
Function Documentation
arrhenius_exponential()
double arrhenius_exponential (double c, double activation_energy, double temperature) inline
Calculates the exponential term of the Arrhenius equation.
The Arrhenius equation gives the dependence of the rate constant of a chemical reaction on the absolute temperature and is often written as
‍k = A * e^(-E_a / R / T) (1)
where k is the rate constant, E_a is the activation energy, R is the ideal gas constant, and T is the absolute temperature. As T approaches infinity, E_a / R / T approaches zero and so k approaches A. Thus, A represents the rate constant in the limit of infinite temperature. From a practical standpoint, A is not a particularly useful parameter and for this reason it is often written as
‍A = k_0 * e^c (2)
where k_0 is the rate constant measured at a reference temperature (e.g. 25 degrees C) and c is a dimensionless parameter chosen so that k = k_0 at the reference temperature.
In order to make this function reusable, it only calculates the exponential factor, which is always dimensionless. I.e., it calculates e^(c - E_a / R / T).
Parameters
[in] c Dimensionless parameter related to the reference temperature at which the rate constant was measured
[in] activation_energy Activation energy of the reaction in J / mol
[in] temperature Absolute temperature in Kelvin
Returns
Return The Arrhenius exponential e^(c - E_a / R / T)
Definition at line 153 of file AuxBioCro.h.
Referenced by c3photoC(), and rue_photo().
leaf_boundary_layer_conductance_nikolov()
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Nikolov, Massman, and Schoettle (1995).
Note that for an isolated leaf, this conductance characterizes the entire path from the leaf surface to the ambient air. For a leaf within a canopy, there is an additional boundary layer separating the canopy from the atmosphere; this canopy boundary layer conductance must be calculated using a separate model.
In this model, two types of gas flow are considered: "forced" flow driven by wind-created eddy currents and "free" flow driven by temperature-related buoyancy effects. The overall conductance is determined to be the larger of the free and forced conductances.
In this function, we use equations 29, 33, 34, and 35 to calculate boundary layer conductance. This is the same approach taken in the MLcan model of Drewry et al. (2010).
In this model, the minimum possible boundary layer conductance that could occur is zero. This would happen if wind speed is zero and the air and leaf temperatures are the same. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
References:
[Nikolov, N. T., Massman, W. J. & Schoettle, A. W. "Coupling biochemical and biophysical processes at the leaf level: an equilibrium photosynthesis model for leaves of C3 plants" Ecological Modelling 80, 205–235 (1995)] (https://doi.org/10.1016/0304-3800(94)00072-P)
[Drewry, D. T. et al. "Ecohydrological responses of dense canopies to environmental variability: 1. Interplay between vertical structure and photosynthetic pathway" Journal of Geophysical Research: Biogeosciences 115, (2010)] (https://doi.org/10.1029/2010JG001340)
Parameters
[in] windspeed The wind speed in m / s
[in] leafwidth The characteristic leaf dimension in m
[in] air_temperature The air temperature in degrees C
[in] delta_t The temperature difference between the leaf and air in degrees C
[in] stomcond The stomatal conductance in m / s
[in] water_vapor_pressure The partial pressure of water vapor in the atmosphere in Pa
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
Returns
The boundary layer conductance in m / s
Definition at line 383 of file AuxBioCro.cpp.
References saturation_vapor_pressure().
Referenced by leaf_gbw_nikolov::do_operation(), and EvapoTrans2().
leaf_boundary_layer_conductance_thornley()
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Thornley and Johnson (1990).
Note that for an isolated leaf, this conductance characterizes the entire path from the leaf surface to the ambient air. For a leaf within a canopy, there is an additional boundary layer separating the canopy from the atmosphere; this canopy boundary layer conductance must be calculated using a separate model.
This model considers gas flow due to wind-driven eddy currents. Here, the conductance is calculated using Equation 14.9 from pages 414 - 416 of the Thornley textbook. Unfortunately, an electronic version of this reference is not available.
In this model, the minimum possible boundary layer conductance that could occur is zero, which would correspond to zero wind speed or canopy height. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
This model contains two singularities, which occur when either of the following conditions are met:
WindSpeedHeight + Zeta - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaCoef) = WindSpeedHeight * 1.34
WindSpeedHeight + ZetaM - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaMCoef) = WindSpeedHeight * 1.56
So, as the canopy height approaches or exceeds the height at which wind speed was measured, the calculated boundary layer conductance becomes unbounded. For even larger canopy heights, the conductance eventually begins to decrease. For tall crops, this is a severe limitation to this model. Here we address this issue by limiting the canopy height to 0.98 * WindSpeedHeight.
References:
Thornley, J. H. M. & Johnson, I. R. "Plant and Crop Modelling: A Mathematical Approach to Plant and Crop Physiology" (1990)
Parameters
[in] CanopyHeight The height of the canopy above the ground in m
[in] WindSpeed The wind speed in m / s as measured above the canopy at a reference height of five meters
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
[in] WindSpeedHeight The height in m at which the wind speed was measured
Returns
The boundary layer conductance in m / s
Definition at line 481 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), and leaf_gbw_thornley::do_operation().
LNprof()
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double * leafNla)
Definition at line 182 of file AuxBioCro.cpp.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
rootDist()
rd_str rootDist (int layer, double rootDepth, double * depths, double rfl)
Definition at line 1076 of file AuxBioCro.cpp.
References poisson_density(), rootDist(), and rd_str::rootDist.
Referenced by rootDist(), and soilML().
seqRootDepth()
seqRD_str seqRootDepth (double to, int lengthOut)
Definition at line 1065 of file AuxBioCro.cpp.
References seqRD_str::rootDepths.