The BioCro C++ Library: /github/workspace/src/module_library/c3CanAC.cpp File Reference
c3CanAC.cpp File Reference
#include "c3CanAC.h"
#include "BioCro.h"
#include "c3photo.h"
#include "lightME.h"
#include "sunML.h"
#include "../framework/constants.h"
Functions
canopy_photosynthesis_outputs c3CanAC (double LAI, double cosine_zenith_angle, double solarR, double ambient_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering, double growth_respiration_fraction, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight, double beta_PSII)
Function Documentation
c3CanAC()
canopy_photosynthesis_outputs c3CanAC (double LAI, double cosine_zenith_angle, double solarR, double ambient_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering, double growth_respiration_fraction, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight, double beta_PSII)
Definition at line 8 of file c3CanAC.cpp.
References canopy_photosynthesis_outputs::Assim, photosynthesis_outputs::Assim, Light_profile::average_absorbed_shortwave, ET_Str::boundary_layer_conductance, c3EvapoTrans(), c3photoC(), canopy_photosynthesis_outputs::canopy_conductance, canopy_photosynthesis_outputs::canopy_transpiration_penman, canopy_photosynthesis_outputs::canopy_transpiration_priestly, ET_Str::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, ET_Str::EPenman, ET_Str::EPriestly, canopy_photosynthesis_outputs::GrossAssim, photosynthesis_outputs::GrossAssim, photosynthesis_outputs::Gs, Light_profile::height, lightME(), LNprof(), canopy_photosynthesis_outputs::Rp, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_ppfd, Light_profile::shaded_fraction, Light_profile::sunlit_absorbed_ppfd, Light_profile::sunlit_fraction, sunML(), canopy_photosynthesis_outputs::Trans, ET_Str::TransR, and WINDprof().
Referenced by c3_canopy::do_operation().