The BioCro C++ Library: /github/workspace/src/module_library/lightME.cpp File Reference
lightME.cpp File Reference
#include "lightME.h"
#include "../framework/constants.h"
Functions
Light_model lightME (double cosine_zenith_angle, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering)
Calculates the "light macro environment"; in other words, the amount of sunlight scattered out of the direct beam by the atmosphere.
Function Documentation
lightME()
Light_model lightME (double cosine_zenith_angle, double atmospheric_pressure, double atmospheric_transmittance, double atmospheric_scattering)
Calculates the "light macro environment"; in other words, the amount of sunlight scattered out of the direct beam by the atmosphere.
The result is expressed in two ways:
As atmospheric transmittances, which are the ratios of direct light or diffuse light at the Earth's surface to incident light at the upper atmosphere. These would be appropriate for calculating the intensity of direct and diffuse light at the surface given a value for the solar constant. Note that these transmittances are different than the input parameter atmospheric_transmittance, which represents the transmittance of either type of light through a small volume of atmosphere.
As fractions of direct and diffuse light at the Earth's surface, which would be appropriate for calculating the intensity of direct and diffuse light given an experimental measurement of light intensity at the surface.
The basis for this function is given in chapter 11 of Norman and Campbell, An Introduction to Environmental Biophysics, 2nd edition. The book states that this model is technically only applicable for solar zenith angles less than 80 degrees (which approximately corresponds to cosine_zenith_angle greater than 0.173). When the Sun is closer to the horizon (or even below it), atmospheric refraction plays a large role in determining the relative amounts of direct and diffuse light at the Earth's surface. The effect of refraction depends strongly on dust, air temperature, and clouds, making it difficult or impossible to accurately model. Here, we choose to use the model outside this range, extending it to cosine_zenith_angle = 0. For even smaller values, we simply use the limits as cosine_zenith_angle approaches zero. The resulting inaccuracies are expected to play a small role in a biological simulation, because light intensities at the surface tend to be low when the Sun is near the horizon.
Parameters
[in] cosine_zenith_angle The cosine of the solar zenith angle; when the Sun is directly overhead, the angle is 0 and its cosine is 1; when the Sun's center is at the horizon, the angle is 90 and its cosine is 0.
[in] atmospheric_pressure Local atmospheric pressure in Pa
[in] atmospheric_transmittance Fraction of light transmitted through a small volume of atmosphere (dimensionless)
[in] atmospheric_scattering Atmospheric scattering factor (dimensionless)
Returns
A structure containing values of the transmittances and fractions of direct and diffuse light just above the canopy.
Definition at line 56 of file lightME.cpp.
References Light_model::direct_transmittance.
Referenced by c3CanAC(), CanAC(), and shortwave_atmospheric_scattering::do_operation().