The BioCro C++ Library: module_creator Class Reference
module_creator Class Reference abstract
Facilitates module creation.
#include <module_creator.h>
Public Member Functions
virtual string_vector get_inputs ()=0
virtual string_vector get_outputs ()=0
virtual std::string get_name ()=0
virtual std::unique_ptr< module > create_module (state_map const &input_quantities, state_map *output_quantities)=0
virtual ~module_creator ()=0
Detailed Description
Facilitates module creation.
This class addresses a difficulty associated with the creation of concrete module objects. The constructor of a concrete module class must store pointers to elements of state_map objects that correspond to its input and output quantities. Thus, in order to ensure that the state_map objects include the elements required by the module, the module's input and output quantities must be known before it is created. Naively, we would want the module class to have static virtual methods for reporting inputs and outputs prior to instantiation. However, C++ does not allow static virtual methods.
Instead, we use the module_creator class to provide similar functionality to hypothetical static virtual methods. This class provides essential information about a module that is required before creating it (its inputs, outputs, and name), as well as a method for creating it. Its key features are that (1) the module class's inputs and outputs can be accessed before creating an instance of it and (2) it defines a common signature for a concrete module class constuctor.
This class is pure abstract, defining a common type that can be created using a factory class (the module_factory). Its implementation for a particular concrete module is achieved using the derived template class module_creator_impl.
Definition at line 37 of file module_creator.h.
Constructor & Destructor Documentation
~module_creator()
~module_creator () inline pure virtual
Definition at line 52 of file module_creator.h.
Member Function Documentation
create_module()
virtual std::unique_ptr< module > create_module (state_map const & input_quantities, state_map * output_quantities) pure virtual
Implemented in module_creator_impl< T >.
Referenced by R_evaluate_module(), and R_module_info().
get_inputs()
virtual string_vector get_inputs () pure virtual
Implemented in module_creator_impl< T >.
Referenced by get_module_inputs(), and R_module_info().
get_name()
virtual std::string get_name () pure virtual
Implemented in module_creator_impl< T >.
Referenced by R_module_info().
get_outputs()
virtual string_vector get_outputs () pure virtual
Implemented in module_creator_impl< T >.
Referenced by get_module_outputs(), R_evaluate_module(), and R_module_info().
The documentation for this class was generated from the following file:
/github/workspace/src/framework/module_creator.h