The BioCro C++ Library: /github/workspace/src/framework/numerical_jacobian.h File Reference
numerical_jacobian.h File Reference
#include <cmath>
#include <algorithm>
#include <memory>
#include "constants.h"
Functions
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, time_type t, vector_type const &f_current, matrix_type &jacobi)
Numerically compute the Jacobian matrix of a vector valued function.
template<typename equation_ptr_type , typename vector_type , typename time_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, time_type t, matrix_type &jacobi)
A wrapper for the five-argument version of calculate_jacobian() that automatically evaluates f_current.
template<typename equation_ptr_type , typename vector_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, vector_type const &f_current, matrix_type &jacobi)
A wrapper for the five-argument version of calculate_jacobian() for equations that have no time dependence.
template<typename equation_ptr_type , typename vector_type , typename matrix_type >
void calculate_jacobian (equation_ptr_type const &equation_ptr, vector_type const &x, matrix_type &jacobi)
A wrapper for the five-argument version of calculate_jacobian() that automatically evaluates f_current for equations that have no time dependence.
template<typename equation_ptr_type , typename time_type , typename vector_type >
void calculate_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, vector_type const &x, time_type t, vector_type const &f_current, vector_type &dfdt)
Numerically compute the explicit time derivatives of a vector valued function.
template<typename equation_ptr_type , typename time_type , typename vector_type >
void calculate_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, vector_type const &x, time_type t, vector_type &dfdt)
A wrapper for the six-argument version of calculate_time_derivative() that automatically calculates f_current.
template<typename equation_ptr_type , typename time_type , typename vector_type , typename matrix_type >
void calculate_jacobian_and_time_derivative (equation_ptr_type const &equation_ptr, time_type max_time, vector_type const &x, time_type t, matrix_type &jacobi, vector_type &dfdt)
Numerically compute the Jacobian matrix and the explicit time derivative of a vector valued function.
Function Documentation
calculate_jacobian() [1/4]
void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, matrix_type & jacobi)
A wrapper for the five-argument version of calculate_jacobian() that automatically evaluates f_current for equations that have no time dependence.
Definition at line 197 of file numerical_jacobian.h.
References calculate_jacobian().
calculate_jacobian() [2/4]
void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, time_type t, matrix_type & jacobi)
A wrapper for the five-argument version of calculate_jacobian() that automatically evaluates f_current.
Definition at line 162 of file numerical_jacobian.h.
References calculate_jacobian(), and evaluate_equations().
calculate_jacobian() [3/4]
void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, time_type t, vector_type const & f_current, matrix_type & jacobi)
Numerically compute the Jacobian matrix of a vector valued function.
The Jacobian \(\mathbf{J} \) of a vector-valued function \(\vec{f} (\vec{x}, t) \) is a matrix whose elements are defined by \(J_{i,j} = \frac{\partial f_i}{\partial x_j} \), where \(f_i \) is the \(i^{th} \) component of \(\vec{f} \) and \(x_j \) is the \(j^{th} \) component of \(\vec{x} \). (Here, \(t \) is a scalar.) In other words, each element of \(\mathbf{J} \) is itself a function of \(\vec{x} \) and \(t \) defined by one of the possible partial derivatives of \(\vec{f} \) with respect to the elements of \(\vec{x} \). For more information, see the Wikpedia page for the Jacobian matrix.
Here, we numerically calculate the value of the Jacobian matrix at particular values of \(\vec{x} \) and \(t \). To do this, we use the simplest (but not the most accurate) method for estimating the value of each partial derivative in the matrix. This can be classified as the "forward perturbation method" and is defined as follows:
\[ \frac{\partial f_i}{\partial x_j} \approx \frac{f_i(\vec{x} + h \cdot \vec{e}_j) - f_i(\vec{x})}{h}, \]
where \(h \) is a small number and \(\vec{e}_j \) is the unit vector in the \(j \) direction. \(h \) is calculated to be a small fraction of \(x_j \), or a minimal value when \(x_j = 0 \).
By using this method, we are avoiding more complex options that determine an optimal value for \(h \), that consider forward and backward perturbations, or that consider additional terms in the Taylor series for \(\vec{f} \). For our purposes, the additional computational costs inherent to these methods do not justify the marginal increases in accuracy. For example, see this discussion of step size from Nadim Khalil's thesis:
‍It is also known that numerical differentiation is an unstable procedure prone to truncation and subtractive cancellation errors. Decreasing the step size [ \(h \) in the equation above] will reduce the truncation error. Unfortunately a smaller step has the opposite effect on the cancellation error. Selecting the optimal step size for a certain problem is computationally expensive and the benefits achieved are not justifiable as the effect of small errors in the values of the elements of the Jacobian matrix is minor. For this reason, the sizing of the finite difference step is not attempted and a constant increment size is used in evaluating the gradient.
Also note that in general, if \(\vec{x} \) has \(N \) elements, then calculating the Jacobian using the forward pertubration scheme requires \(N + 1 \) function evaluations, while using forward and backward perturbations requires \(2 N \). Likewise, higher-order alternatives also add a large number of function evaluations. Function evaluations are expensive in BioCro, so it is important to use them sparingly.
When calculating numerical derivatives, roundoff error in the value of the step size \(h \) can have a significant effect. For that reason, it is important to ensure that \(h \) is exactly representable in the computer architecture. This can be accomplished using a simple scheme like
‍double volatile temp = x + h;
h = temp - x;
The volatile keyword ensures that the compiler's optimizer does not eliminate this reassignment process. For more information about this issue, see Section 5.7 of Numerical Recipes in C, 2nd Edition or 3rd Edition.
In BioCro, the Jacobian is almost always calculated for the case where \(\vec{f}(\vec{x}, t) = d \vec{x} / dt \). In this case, \(\vec{x} \) and \(\vec{y} = \vec{f}(\vec{x}, t) \) have the same dimension. Even in other BioCro applications where \(\vec{f}(\vec{x}, t) \) is not the time derivative of \(\vec{x} \), this restriction on dimensionality still holds. Because of this, here we assume that the output from \(\vec{f} \) always has the same length as \(\vec{x} \).
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f(x, t). There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] x an input vector to be passed to f.
[in] t an input time to be passed to f.
[in] f_current the output of f evaluated at x and t
[out] jacobi the calculated Jacobian matrix (containing the partial derivatives \(\partial{f_i}/\partial{x_j} \) evaluated at x and t)
Definition at line 108 of file numerical_jacobian.h.
References calculation_constants::eps_deriv, and evaluate_equations().
Referenced by calculate_jacobian(), and calculate_jacobian_and_time_derivative().
calculate_jacobian() [4/4]
void calculate_jacobian (equation_ptr_type const & equation_ptr, vector_type const & x, vector_type const & f_current, matrix_type & jacobi)
A wrapper for the five-argument version of calculate_jacobian() for equations that have no time dependence.
Definition at line 180 of file numerical_jacobian.h.
References calculate_jacobian().
calculate_jacobian_and_time_derivative()
void calculate_jacobian_and_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, vector_type const & x, time_type t, matrix_type & jacobi, vector_type & dfdt)
Numerically compute the Jacobian matrix and the explicit time derivative of a vector valued function.
This function simply calls calculate_jacobian() and calculate_time_derivative().
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f(x, t). There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] max_time the largest time value that can be passed to f.
[in] x an input vector to be passed to f.
[in] t an input time to be passed to f.
[out] jacobi the calculated Jacobian matrix (containing the partial derivatives \(\partial{f_i}/\partial{x_j} \) evaluated at x and t)
[out] dfdt the calculated time derivative, i.e., the vector of derivatives \(df_i / dt \) evaluated at x and t.
Definition at line 365 of file numerical_jacobian.h.
References calculate_jacobian(), calculate_time_derivative(), and evaluate_equations().
Referenced by dynamical_system_pointer_wrapper::operator()().
calculate_time_derivative() [1/2]
void calculate_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, vector_type const & x, time_type t, vector_type & dfdt)
A wrapper for the six-argument version of calculate_time_derivative() that automatically calculates f_current.
Definition at line 322 of file numerical_jacobian.h.
References calculate_time_derivative(), and evaluate_equations().
calculate_time_derivative() [2/2]
void calculate_time_derivative (equation_ptr_type const & equation_ptr, time_type max_time, vector_type const & x, time_type t, vector_type const & f_current, vector_type & dfdt)
Numerically compute the explicit time derivatives of a vector valued function.
Here, the explicit time derivative of a vector-valued function \(\vec{f}(\vec{x}, t) \) is calculated numerically using
\[ \frac{d f_i}{dt} \approx \frac{f_i(\vec{x}, t + h) - f_i(\vec{x}, t)}{h}, \]
where \(f_i \) is the \(i^{th} \) component of \(\vec{f} \). As is the case with the partial derivatives of calculate_jacobian(), this method is fast but not the most accurate, and requires that \(h \) be exactly representable in the computer architecture. With this definition, we ignore any possible implicit time dependence of \(\vec{x} \), which is why we refer to this derivative as the "explicit" time derivative.
One consideration unique to the time derivative is that the time domain is usually finite. If \(t \) is close to the maximum possible value, then this forward perturbation approach is not applicable. In that case, we instead calculate the derivative as
\[ \frac{d f_i}{dt} \approx \frac{f_i(\vec{x}, t) - f_i(\vec{x}, t - h)}{h}. \]
This is a backwards perturbation.
In BioCro, the explicit time derivative is almost always calculated for the case where \(\vec{f}(\vec{x}, t) = d \vec{x} / dt \). In this case, \(\vec{x} \) and \(\vec{y} = \vec{f}(\vec{x}, t) \) have the same dimension. Even in other BioCro applications where \(\vec{f}(\vec{x}, t) \) is not the time derivative of \(\vec{x} \), this restriction on dimensionality still holds. Because of this, here we assume that the output from \(\vec{f} \) always has the same length as \(\vec{x} \).
Parameters
[in] equation_ptr a pointer to an object that can be used to represent a vector valued function f(x, t). There must be an associated evaluate_equations(*equation_ptr_type, x, t, y) function defined for equation_ptr_type. It is assumed that the output vector produced by the equations has the same length as the input vector.
[in] max_time the largest time value that can be passed to f.
[in] x an input vector to be passed to f.
[in] t an input time to be passed to f.
[in] f_current the output of f evaluated at x and t.
[out] dfdt the calculated time derivative, i.e., the vector of derivatives \(df_i / dt \) evaluated at x and t.
Definition at line 264 of file numerical_jacobian.h.
References calculation_constants::eps_deriv, and evaluate_equations().
Referenced by calculate_jacobian_and_time_derivative(), and calculate_time_derivative().