var searchData=
[
  ['c3_5fassimilation_1547',['c3_assimilation',['../classc3__assimilation.html#a5a0dff890013571b995ee3cc09d03f9e',1,'c3_assimilation']]],
  ['c3_5fcanopy_1548',['c3_canopy',['../classc3__canopy.html#af90d78d048115ea86b02a3d2183756d8',1,'c3_canopy']]],
  ['c3_5fleaf_5fphotosynthesis_1549',['c3_leaf_photosynthesis',['../classc3__leaf__photosynthesis.html#ae71f3cdfe179f53d0ea5785475d10dca',1,'c3_leaf_photosynthesis']]],
  ['c3canac_1550',['c3CanAC',['../_bio_cro_8h.html#a71b6ec7f186989eadc9d6196f7514c53',1,'c3CanAC(double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance):&#160;c3CanAC.cpp'],['../c3_can_a_c_8cpp.html#a2dd72ef34926c3dad5d9f62069a5060b',1,'c3CanAC(double LAI, int DOY, double hr, double solarR, double air_temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance):&#160;c3CanAC.cpp']]],
  ['c3evapotrans_1551',['c3EvapoTrans',['../c3_evapo_trans_8cpp.html#aff67a46646ccb9ba3ea1c0f1f2e1e3e4',1,'c3EvapoTrans(double absorbed_shortwave_radiation, double air_temperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomatal_conductance):&#160;c3EvapoTrans.cpp'],['../_bio_cro_8h.html#a191f03165ae677daef878bf61f3d118e',1,'c3EvapoTrans(double Itot, double Airtemperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomtal_conductance):&#160;c3EvapoTrans.cpp']]],
  ['c3photoc_1552',['c3photoC',['../c3photo_8hpp.html#a433bc4f80df9626b7a12a7b993b58741',1,'c3photoC(double Qp, double Tleaf, double RH, double Vcmax0, double Jmax0, double tpu_rate_max, double Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double O2, double theta, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation):&#160;c3photo.cpp'],['../c3photo_8cpp.html#a3993a75c6ee7f15cf42a0df4e1abe287',1,'c3photoC(double _Qp, double _Tleaf, double RH, double _Vcmax0, double _Jmax0, double _TPU_rate_max, double _Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double _O2, double thet, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation):&#160;c3photo.cpp']]],
  ['c3photocdb_1553',['c3photoCdb',['../c3photo_8hpp.html#a0b86527c7334316aa162fd723faac3b3',1,'c3photo.hpp']]],
  ['c4_5fassimilation_1554',['c4_assimilation',['../classc4__assimilation.html#adc6d82ea8fdc264efdb6ea20f943738c',1,'c4_assimilation']]],
  ['c4_5fcanopy_1555',['c4_canopy',['../classc4__canopy.html#a94d23dfe2a067f56b731d38f379f2d9c',1,'c4_canopy']]],
  ['c4_5fleaf_5fphotosynthesis_1556',['c4_leaf_photosynthesis',['../classc4__leaf__photosynthesis.html#ab4a252ecfb25a713e36d6af419915e79',1,'c4_leaf_photosynthesis']]],
  ['c4photoc_1557',['c4photoC',['../c4photo_8cpp.html#a2613ca2f3d1f34c768aacfbd0de1dd3e',1,'c4photoC(double Qp, double leaf_temperature, double relative_humidity, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT):&#160;c4photo.cpp'],['../c4photo_8h.html#a21ffc36b1b0fa5d152ca787d71d9283b',1,'c4photoC(double Qp, double Tl, double RH, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT):&#160;c4photo.cpp']]],
  ['canac_1558',['CanAC',['../_bio_cro_8h.html#a0ca3e6e5da99573ff15996069755ba97',1,'CanAC(double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &amp;nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance):&#160;CanAC.cpp'],['../_can_a_c_8cpp.html#ade4cd57e186108a02a241ecf67015a5a',1,'CanAC(double LAI, int DOY, double hr, double solarR, double temperature, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &amp;nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance):&#160;CanAC.cpp']]],
  ['collatz_5fphoto_1559',['collatz_photo',['../collatz__photo_8cpp.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp'],['../collatz__photo_8hpp.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp']]],
  ['compute_5fwsphoto_1560',['compute_wsPhoto',['../_aux_bio_cro_8cpp.html#a058be0e6ed718b377d7c6056cceb09a8',1,'AuxBioCro.cpp']]],
  ['cos_5fzenith_5fangle_1561',['cos_zenith_angle',['../_aux_bio_cro_8cpp.html#a81eccf5a903a575f17d799d959397f61',1,'cos_zenith_angle(const double latitude, const int day_of_year, const double hour_of_day):&#160;AuxBioCro.cpp'],['../_bio_cro_8h.html#a81eccf5a903a575f17d799d959397f61',1,'cos_zenith_angle(const double latitude, const int day_of_year, const double hour_of_day):&#160;AuxBioCro.cpp']]],
  ['create_1562',['create',['../classmodule__wrapper__factory.html#a88c7e6e99de6589d718c74152040e94d',1,'module_wrapper_factory']]],
  ['create_5fwrapper_1563',['create_wrapper',['../module__wrapper__factory_8cpp.html#ac56d2dfcd999b585c6f90555d7aed5ca',1,'module_wrapper_factory.cpp']]]
];
