The BioCro C++ Library: /github/workspace/source/src/module_library/BioCro.h File Reference
BioCro.h File Reference
#include "AuxBioCro.h"
Classes
struct Light_model
Functions
double cos_zenith_angle (const double latitude, const int day_of_year, const double hour_of_day)
Computation of the cosine of the zenith angle from latitute (lat), day of the year (DOY), and time of day (td).
struct Can_Str CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms &nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par)
struct Can_Str c3CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par)
double resp (double comp, double mrc, double temp)
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double phi1, double phi2, double soil_saturation_capacity, double soil_sand_content, double Ks, double air_entry, double b)
double SoilEvapo (double LAI, double k, double AirTemp, double DirectRad, double awc, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double stefan_boltzman)
struct soilML_str soilML (double precipit, double transp, double *cws, double soildepth, double *depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double stefan_boltzman)
void RHprof (double RH, int nlayers, double *relative_humidity_profile)
Calculates a relative humidity profile throughout a multilayer canopy.
void WINDprof (double WindSpeed, double LAI, int nlayers, double *wind_speed_profile)
RH and Wind profile function.
struct Light_profile sunML (double Idir, double Idiff, double LAI, int nlayers, double cosTheta, double kd, double chil, double absorptivity, double heightf)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
struct Light_model lightME (double lat, int DOY, double td, double atmospheric_pressure)
Calculates some properties of the "light macro environment," i.e., the light just above the top of the canopy.
struct FL_str FmLcFun (double Lig, double Nit)
struct flow_str flow (double *SC, double CNratio, double A, double Lc, double Tm, double resp, int kno, double Ks[8])
double AbiotEff (double smoist, double stemp)
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, double specific_heat_of_air, int eteq)
struct ET_Str c3EvapoTrans (double Itot, double Airtemperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomtal_conductance)
Function Documentation
AbiotEff()
double AbiotEff (double smoist, double stemp)
c3CanAC()
struct Can_Str c3CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par)
Definition at line 1 of file c3CanAC.cpp.
References Can_Str::Assim, c3_str::Assim, c3EvapoTrans(), c3photoC(), Light_model::cosine_zenith_angle, ET_Str::Deltat, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, Can_Str::GrossAssim, c3_str::GrossAssim, c3_str::Gs, Light_profile::height, lightME(), LNprof(), RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, ET_Str::TransR, and WINDprof().
Referenced by c3_canopy::do_operation().
c3EvapoTrans()
struct ET_Str c3EvapoTrans (double Itot, double Airtemperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomtal_conductance)
Definition at line 1 of file c3EvapoTrans.cpp.
References ET_Str::Deltat, ET_Str::EPenman, ET_Str::EPriestly, physical_constants::molar_mass_of_water, saturation_vapor_pressure(), TempToDdryA(), TempToLHV(), TempToSFS(), and ET_Str::TransR.
Referenced by c3CanAC(), and c3_leaf_photosynthesis::do_operation().
CanAC()
struct Can_Str CanAC (double LAI, int DOY, double hr, double solarR, double Temp, double RH, double WindSpeed, double lat, int nlayers, double Vmax, double Alpha, double Kparm, double beta, double Rd, double Catm, double b0, double b1, double Gs_min, double theta, double kd, double chil, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double upperT, double lowerT, const struct nitroParms & nitroP, double leafwidth, int eteq, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, int water_stress_approach, double absorptivity_par)
Definition at line 1 of file CanAC.cpp.
References Can_Str::Assim, c4_str::Assim, c4photoC(), Can_Str::canopy_conductance, Can_Str::canopy_transpiration_penman, Can_Str::canopy_transpiration_priestly, Light_model::cosine_zenith_angle, ET_Str::Deltat, Light_profile::diffuse_irradiance, Light_model::diffuse_irradiance_fraction, Light_profile::direct_irradiance, Light_model::direct_irradiance_fraction, ET_Str::EPenman, ET_Str::EPriestly, EvapoTrans2(), Can_Str::GrossAssim, c4_str::GrossAssim, c4_str::Gs, Light_profile::height, lightME(), LNprof(), MAXLAY, Can_Str::result_matrix, RHprof(), Light_profile::shaded_fraction, Light_profile::sunlit_fraction, sunML(), Light_profile::total_irradiance, Can_Str::Trans, ET_Str::TransR, and WINDprof().
Referenced by c4_canopy::do_operation().
cos_zenith_angle()
double cos_zenith_angle (const double latitude, const int day_of_year, const double hour_of_day)
Computation of the cosine of the zenith angle from latitute (lat), day of the year (DOY), and time of day (td).
For the values of angles in radians, we'll use the common practice of denoting the latitude by phi (\(\phi\)), the declination by delta (\(\delta\)), and the hour angle by tau (\(\tau\)). NDS denotes the number of days after December solstice and omega (\(\omega\)) denotes the angle (in radians) of the orbital position of the earth around the sun relative to its position at the December solstice.
Denoting the axial tilt of the earth by \(\varepsilon\), the equation used for declination (delta) is
\[ \delta = -\varepsilon \cos(\omega) \]
which is an approximation (always accurate to within 0.26 degrees) of the more accurate formula
\[ \sin(\delta) = -\sin(\varepsilon) \cos(\omega) \]
The cosine of the solar zenith angle \(\theta_s\) may be calculated from the declination \(\delta\), the latitude \(\phi\), and the hour angle \(\tau\) by the formula
\[ \cos(\theta_s) = \sin(\delta) \sin(\phi) + \cos(\delta) \cos(\phi) \cos(\tau) \]
which is a straight-forward application of the law of cosines for spherical triangles, substituting cofunctions of coangles in the case of latitude and declination.
Definition at line 72 of file AuxBioCro.cpp.
Referenced by solar_zenith_angle::do_operation(), and lightME().
EvapoTrans2()
struct ET_Str EvapoTrans2 (double Rad, double Iave, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double stomatacond, double leafw, double specific_heat_of_air, int eteq)
Definition at line 469 of file AuxBioCro.cpp.
flow()
struct flow_str flow (double * SC, double CNratio, double A, double Lc, double Tm, double resp, int kno, double Ks[8])
FmLcFun()
struct FL_str FmLcFun (double Lig, double Nit)
lightME()
struct Light_model lightME (const double latitude, const int day_of_year, const double hour_of_day, const double atmospheric_pressure)
Calculates some properties of the "light macro environment," i.e., the light just above the top of the canopy.
Parameters
[in] latitude Latitude of a position on Earth (in degrees)
[in] day_of_year Local day of the year (1-366)
[in] hour_of_day Local hour of the day expressed on a 24-hour basis
[in] atmospheric_pressure Local atmospheric pressure (in Pa)
The return value from this function is a customized structure (light_model) with the following members:
light_model.direct_irradiance_fraction: The fraction of irradiance that is direct radiation (dimensionless)
light_model.diffuse_irradiance_fraction: The fraction of irradiance that is diffuse radiation (dimensionless)
light_model.cosine_zenith_angle: The cosine of the zenith angle of the Sun. When the Sun is directly overhead, the angle is 0 and cos(angle) is 1 (dimensionless)
The basis for this function is given in chapter 11 of Norman and Campbell, An Introduction to Environmental Biophysics, 2nd edition.
Definition at line 117 of file AuxBioCro.cpp.
References physical_constants::atmospheric_pressure_at_sea_level, cos_zenith_angle(), Light_model::cosine_zenith_angle, Light_model::diffuse_irradiance_fraction, and Light_model::direct_irradiance_fraction.
Referenced by c3CanAC(), CanAC(), big_leaf_multilayer_canopy::do_operation(), and newCanAC().
resp()
double resp (double comp, double mrc, double temp)
Definition at line 1044 of file AuxBioCro.cpp.
Referenced by no_leaf_resp_partitioning_growth_calculator::do_operation(), and partitioning_growth_calculator::do_operation().
RHprof()
void RHprof (double RH, int nlayers, double * relative_humidity_profile)
Calculates a relative humidity profile throughout a multilayer canopy.
Parameters
[in] RH relative humidity just above the canopy (0 <= RH <= 1)
[in] nlayers number of layers in the canopy (1 <= nlayers <= MAXLAY)
[out] relative_humidity_profile array of relative humidity values expressed as fractions between 0 and 1, where the value at index i represents relative humidity at the bottom of canopy layer i and i = 0 corresponds to the top canopy layer.
One can derive an expression for the relative humidity (h) throughout a plant canopy by making the following assumptions:
h at the top of the canopy is the same as the ambient value (h = h0)
h at the bottom of the canopy is one hundred percent (h = 1)
h follows an exponential profile throughout the canopy
To enforce the exponential profile, we can write
h(x) = A * exp(B * x) [Equation (1)]
where x is a normalized expression of depth within the canopy (x = 0 at the canopy top and x = 1 at the bottom) and the values of A and B are yet to be determined.
To enforce the h value at the canopy top, we require h0 = h(0) = A; in other words, A = h0. To enforce the h value at the canopy bottom, we require 1 = h(1) = h0 * exp(B); in other words, B = -ln(h0). Putting it all together, we see that under these assumptions, h throughout the canopy is given by
h(x) = h0 * exp(-ln(h0) * x) [Equation (2)]
If we additionally assume that h0 is close to 1, we can simplify B = -ln(h0) by taking just the linear part of the Taylor series for -ln(h0) centered at h0 = 1, which is B = -(h0 - 1). With this modification, we have
h(x) = h0 * exp((1 - h0) * x) [Equation (3)]
When h0 = 1, Equations (2) and (3) are in perfect agreement, reducing to h(x) = 1. However, as h0 deviates further from h0 = 1, the linearization for B becomes less accurate and the two versions diverge, especially deeper in the canopy. For example, when h0 = 0.7, Equation (2) becomes h(x) = 0.7 * exp(0.357 * x) while Equation (3) becomes h(x) = 0.7 * exp(0.300 * x). Both versions agree at the top of the canopy where x = 0 and h(x) = 1, but are different at the bottom: 1.00 vs. 0.94. For lower h0 values, the difference at the canopy bottom becomes even more pronounced, significantly violating one of the original assumptions. However, there isn't a strong scientific justification for assuming humidity is 1 at the bottom of every canopy, so the error due to the approximation for B is deemed to be acceptable.
In BioCro, we divide the canopy into equally sized layers; i.e., the interval 0 <= x <= 1 is divided into n segments of length 1 / n by n + 1 boundaries occurring at x = 0, x = 1 / n, x = 2 / n, ..., x = 1. Here we wish to find the h value at the bottom of each layer, so we use Equation (3) with x = 1 / n, x = 2 / n, ..., x = 1.
In the code below, the RH input argument corresponds to h0, the exponential growth constant kh corresponds to B, and nlayers corresponds to n.
Note 1: the explanation for this code was "reverse engineered" by EBL from some crytpic documentation found in earlier versions of this function and from Stephen Humphries's thesis, which is not available online:
Humphries, S. "Will mechanistically rich models provide us with new insights into the response of plant production to climate change?: development and experiments with WIMOVAC: (Windows Intuitive Model of Vegetation response to Atmosphere & Climate Change)" (University of Essex, 2002).
Note 2: Equation (2) can be rewritten by noting that h0 = exp(ln(h0)). With this replacement, the equation becomes
h(x) = exp(ln(h0) - ln(h0) * x) = exp(-B * (1 - x))
The equation takes this form in Humphries's thesis.
Definition at line 381 of file AuxBioCro.cpp.
References MAXLAY.
Referenced by c3CanAC(), CanAC(), newCanAC(), ed_multilayer_canopy_properties::run(), and multilayer_canopy_properties::run().
SoilEvapo()
double SoilEvapo (double LAI, double k, double AirTemp, double DirectRad, double awc, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double stefan_boltzman)
Definition at line 677 of file AuxBioCro.cpp.
References saturation_vapor_pressure(), TempToDdryA(), TempToLHV(), and TempToSFS().
Referenced by soil_evaporation::do_operation().
soilML()
struct soilML_str soilML (double precipit, double transp, double * cws, double soildepth, double * depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double stefan_boltzman)
Definition at line 745 of file AuxBioCro.cpp.
Referenced by two_layer_soil_profile::do_operation().
sunML()
struct Light_profile sunML (double Idir, double Idiff, double LAI, int nlayers, double cosTheta, double kd, double chil, double absorptivity, double heightf)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
Parameters
[in] Idir Photon flux density for direct light at the top of the canopy (micromol / m^2 / s)
[in] Idiff Photon flux density for diffuse light at the top of the canopy (micromol / m^2 / s)
[in] LAI Leaf area index (LAI) of the entire canopy (dimensionless from m^2 leaf / m^2 ground)
[in] nlayers Integer number of layers in the canopy
[in] cosTheta Cosine of the solar zenith angle (dimensionless)
[in] kd Extinction coefficient for diffuse light (dimensionless)
[in] chil Ratio of average projected areas of canopy elements on horizontal surfaces; for a spherical leaf distribution, chil = 0; for a vertical leaf distribution, chil = 1; for a horizontal leaf distribution, chil approaches infinity (dimensionless from m^2 / m^2)
[in] absorptivity The leaf absorptivity on a quantum basis (dimensionless from mol / mol)
[in] heightf Leaf area density, i.e., LAI per height of canopy (m^-1 from m^2 leaf / m^2 ground / m height)
Returns
An n-layered light profile representing quantities within the canopy, including several photon flux densities and the relative fractions of shaded and sunlit leaves
Note 1: Although the input and output light parameters (e.g. Idir and light_profile.direct_irradiance) are specified as being photon flux densities measured in micromol / m^2 / s, all the calculations within this function are linear in these light parameters. So if the inputs actually represent something else, e.g. irradiance expressed in units of J / m^2 / s, this function can still be used and the outputs will have the same units as the inputs (J / m^2 / s in this example).
Note 2: Nothing in this function is specialized for a specific band of light, so sunML can be used for photosynthetically active photon flux density (PPFD), photosynthetically active radiation (PAR), near-infrared radiation (NIR), etc., as long as the extinction coefficients and absorptivities are appropriately chosen.
Definition at line 193 of file AuxBioCro.cpp.
References Light_profile::diffuse_irradiance, Light_profile::direct_irradiance, Light_profile::height, MAXLAY, Light_profile::scattered_irradiance, Light_profile::shaded_fraction, Light_profile::sunlit_fraction, and Light_profile::total_irradiance.
Referenced by c3CanAC(), CanAC(), newCanAC(), ed_multilayer_canopy_properties::run(), and multilayer_canopy_properties::run().
watstr()
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double phi1, double phi2, double soil_saturation_capacity, double soil_sand_content, double Ks, double air_entry, double b)
Definition at line 745 of file AuxBioCro.cpp.
Referenced by one_layer_soil_profile::do_operation().
WINDprof()
void WINDprof (double WindSpeed, double LAI, int nlayers, double * wind_speed_profile)
RH and Wind profile function.
Preconditions: WindSpeed is non-negative. LAI is non-negative nlayers is at least 1 and at most MAXLAY. wind_speed_profile is an array of at least size nlayers.
Definition at line 280 of file AuxBioCro.cpp.
Referenced by c3CanAC(), CanAC(), newCanAC(), ed_multilayer_canopy_properties::run(), and multilayer_canopy_properties::run().