The BioCro C++ Library: /github/workspace/source/src/R_run_biocro.h File Reference
R_run_biocro.h File Reference
#include <Rinternals.h>
Functions
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Function Documentation
R_run_biocro()
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Definition at line 14 of file R_run_biocro.cpp.
References biocro_simulation::generate_report(), list_from_map(), map_from_list(), map_vector_from_list(), mc_vector_from_list(), parameters, biocro_simulation::run_simulation(), and ed_c4_leaf_photosynthesis_stuff::solver_type.