The BioCro C++ Library: /github/workspace/source/src/R_get_all.cpp File Reference
R_get_all.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "R_helper_functions.h"
#include "module_library/module_wrapper_factory.h"
#include "integrator_library/integrator_factory.h"
#include "se_solver_library/se_solver_factory.h"
Functions
SEXP R_get_all_modules ()
SEXP R_get_all_quantities ()
SEXP R_get_all_integrators ()
SEXP R_get_all_se_solvers ()
Function Documentation
R_get_all_integrators()
SEXP R_get_all_integrators ()
Definition at line 35 of file R_get_all.cpp.
References integrator_factory::get_integrators(), and r_string_vector_from_vector().
R_get_all_modules()
SEXP R_get_all_modules ()
Definition at line 11 of file R_get_all.cpp.
References module_wrapper_factory::get_modules(), and r_string_vector_from_vector().
R_get_all_quantities()
SEXP R_get_all_quantities ()
Definition at line 23 of file R_get_all.cpp.
References module_wrapper_factory::get_all_quantities(), and list_from_map().
R_get_all_se_solvers()
SEXP R_get_all_se_solvers ()
Definition at line 47 of file R_get_all.cpp.
References se_solver_factory::get_solvers(), and r_string_vector_from_vector().