The BioCro C++ Library: /github/workspace/source/src/R_module_library.cpp File Reference
R_module_library.cpp File Reference
#include <string>
#include <unordered_map>
#include <Rinternals.h>
#include <exception>
#include "framework/state_map.h"
#include "framework/R_helper_functions.h"
#include "framework/module_creator.h"
#include "framework/module_factory.h"
#include "module_library/module_library.h"
Typedefs
using library = standardBML::module_library
Functions
SEXP R_module_creators (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_creator object; this function provides a route for creating C++ objects from R strings.
SEXP R_get_all_modules ()
A wrapper for module_factory::get_all_modules() that returns the output as an R vector of R strings.
SEXP R_get_all_quantities ()
A wrapper for module_factory::get_all_quantities() that returns the output as an R list of named R strings.
Typedef Documentation
library
using library = standardBML::module_library
Definition at line 17 of file R_module_library.cpp.
Function Documentation
R_get_all_modules()
SEXP R_get_all_modules ()
A wrapper for module_factory::get_all_modules() that returns the output as an R vector of R strings.
Definition at line 90 of file R_module_library.cpp.
References module_factory< T >::get_all_modules(), and r_string_vector_from_vector().
R_get_all_quantities()
SEXP R_get_all_quantities ()
A wrapper for module_factory::get_all_quantities() that returns the output as an R list of named R strings.
Definition at line 107 of file R_module_library.cpp.
References module_factory< T >::get_all_quantities(), and list_from_map().
R_module_creators()
SEXP R_module_creators (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_creator object; this function provides a route for creating C++ objects from R strings.
See http://www.hep.by/gnu/r-patched/r-exts/R-exts_122.html for more details about R external pointers.
When creating an R external pointer using R_MakeExternalPtr(), it is possible to specify tag and prot arguments for identifying the pointer and protecting its memory. However, it is common to bypass both of these arguments by setting them to R_NilValue (the R null pointer). We follow that route here.
Once an R external pointer has been created, it is also possible to specify a "finalizer" function via R_RegisterFinalizerEx(). This function will be called when garbage is collected and should clear the pointer. By setting the onexit argument of R_RegisterFinalizerEx() to be TRUE, we ensure that the pointer will be cleared when its R session closes.
After its creation, the R external pointer takes ownership of the module_creator object, so there is no need to use smart pointers here.
The output from this function can be converted into a std::vector of module_creator pointers (in other words, an mc_vector) for use in C/C++ code using the mc_vector_from_list() function.
Parameters
[in] module_names The names of the modules for which module_creator objects should be created
Returns
A vector of "R external pointer" objects
Definition at line 53 of file R_module_library.cpp.
References finalize_module_creator(), make_vector(), and module_factory< T >::retrieve().