The BioCro C++ Library: boost_rsnbrk_integrator Class Reference
boost_rsnbrk_integrator Class Reference
#include <boost_integrators.h>
Public Member Functions
boost_rsnbrk_integrator (double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from boost_integrator< boost::numeric::ublas::vector< double > >
boost_integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from integrator
integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~integrator ()
state_vector_map integrate (std::shared_ptr< System > sys)
std::string generate_info_report () const
std::string generate_integrate_report () const
Private Member Functions
void do_boost_integrate (SystemCaller syscall, push_back_state_and_time< boost::numeric::ublas::vector< double >> &observer) override
std::string get_boost_param_info () const override
Additional Inherited Members
Protected Member Functions inherited from boost_integrator< boost::numeric::ublas::vector< double > >
void run_integrate_const (stepper_type stepper, SystemCaller syscall, push_back_state_and_time< boost::numeric::ublas::vector< double > > observer)
Protected Member Functions inherited from integrator
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Detailed Description
Definition at line 211 of file boost_integrators.h.
Constructor & Destructor Documentation
boost_rsnbrk_integrator()
boost_rsnbrk_integrator (double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 214 of file boost_integrators.h.
Member Function Documentation
do_boost_integrate()
void do_boost_integrate (SystemCaller syscall, push_back_state_and_time< boost::numeric::ublas::vector< double >> & observer) override private
Definition at line 3 of file boost_integrators.cpp.
References integrator::get_adaptive_abs_error_tol(), integrator::get_adaptive_rel_error_tol(), and boost_integrator< boost::numeric::ublas::vector< double > >::run_integrate_const().
get_boost_param_info()
std::string get_boost_param_info () const override private virtual
Implements boost_integrator< boost::numeric::ublas::vector< double > >.
Definition at line 18 of file boost_integrators.cpp.
References integrator::get_adaptive_abs_error_tol(), integrator::get_adaptive_max_steps(), and integrator::get_adaptive_rel_error_tol().
The documentation for this class was generated from the following files:
/github/workspace/source/src/integrator_library/boost_integrators.h
/github/workspace/source/src/integrator_library/boost_integrators.cpp