The BioCro C++ Library: module_base Class Reference
module_base Class Reference abstract
Represents one or more equations.
#include <modules.h>
Public Member Functions
module_base (std::string const &module_name, bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Protected Member Functions
virtual void update (double *output_ptr, const double &value) const =0
Private Member Functions
virtual void do_operation () const =0
Private Attributes
std::string const module_name
bool const differential
bool const requires_euler
Detailed Description
Represents one or more equations.
A module can be one of the following subtypes:
direct_module: directly calculates the instantaneous value(s) of one or more quantities
differential_module: a module that calculates the instantaneous rate(s) of change for one or more quantities
A module must also indicate whether or not it requires an Euler ODE solver. Most modules do not. However, a few "legacy" modules require information from previous times and will only work properly with a fixed step size Euler ODE solver.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 29 of file modules.h.
Constructor & Destructor Documentation
module_base()
module_base (std::string const & module_name, bool const & differential, bool const & requires_euler) inline
Definition at line 32 of file modules.h.
~module_base()
~module_base () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 68 of file modules.h.
Member Function Documentation
do_operation()
virtual void do_operation () const private pure virtual
Implemented in thermal_time_development_rate_calculator, soybean_development_rate_calculator, senescence_logistic, senescence_coefficient_logistic, partitioning_growth, partitioning_coefficient_logistic, no_leaf_resp_neg_assim_partitioning_growth_calculator, development_index, base, hyperbola_2d, golden_ratio_hyperbola, ed_rh_to_mole_fraction, ed_penman_monteith_transpiration, ed_penman_monteith_leaf_temperature, ed_nikolov_conductance_free, ed_nikolov_conductance_forced, ed_long_wave_energy_loss, ed_leaf_temperature, ed_gas_concentrations, ed_evapotrans2, ed_collatz_c4_assimilation, ed_canac_leaf, ed_c4photo, ed_boundary_conductance_max, ed_boundary_conductance_quadrature, ed_ball_berry, ed_apply_stomatal_water_stress_via_assimilation, ed_apply_stomatal_water_stress_via_conductance, ed_abc_blc, water_vapor_properties_from_air_temperature, utilization_senescence_calculator, utilization_senescence, utilization_growth_calculator, utilization_growth, two_layer_soil_profile, total_biomass, thermal_time_trilinear, thermal_time_senescence, thermal_time_linear_extended, thermal_time_linear, thermal_time_bilinear, thermal_time_beta, thermal_time_and_frost_senescence, stomata_water_stress_sigmoid, stomata_water_stress_linear_and_aba_response, stomata_water_stress_linear, stomata_water_stress_exponential, song_flowering, solar_position_michalsky, soil_type_selector, soil_evaporation, shortwave_atmospheric_scattering, rue_leaf_photosynthesis, rh_to_mole_fraction, rasmussen_specific_heat, priestley_transpiration, pokhilko_circadian_clock, poincare_clock, phase_clock, penman_monteith_transpiration, penman_monteith_leaf_temperature, partitioning_growth_calculator, partitioning_coefficient_selector, parameter_calculator, oscillator_clock_calculator, one_layer_soil_profile_derivatives, one_layer_soil_profile, nr_ex, no_leaf_resp_partitioning_growth_calculator, night_and_day_trackers, ten_layer_rue_canopy, ten_layer_canopy_properties, ten_layer_canopy_integrator, multilayer_canopy_integrator, ten_layer_c4_canopy, ten_layer_c3_canopy, Module_3, Module_2, Module_1, magic_clock, linear_vmax_from_leaf_n, light_from_solar, leaf_water_stress_exponential, leaf_shape_factor, leaf_gbw_thornley, leaf_gbw_nikolov, incident_shortwave_from_ground_par, harmonic_energy, harmonic_oscillator, grimm_soybean_flowering_calculator, grimm_soybean_flowering, FvCB, fake_solar, empty_senescence, ed_water_vapor_properties, ed_stomata_water_stress_linear, ed_ten_layer_canopy_properties, ed_ten_layer_canopy_integrator, ed_multilayer_canopy_integrator, ed_ten_layer_c4_canopy, c4_leaf_photosynthesis, c4_canopy, c4_assimilation, c3_leaf_photosynthesis, c3_canopy, c3_assimilation, bucket_soil_drainage, buck_swvp, biomass_leaf_n_limitation, ball_berry_module, and aba_decay.
Referenced by run().
get_name()
std::string get_name () const inline
Definition at line 45 of file modules.h.
References module_name.
Referenced by incident_shortwave_from_ground_par::do_operation(), rh_to_mole_fraction::do_operation(), ed_ball_berry::do_operation(), ed_collatz_c4_assimilation::do_operation(), ed_gas_concentrations::do_operation(), ed_leaf_temperature::do_operation(), ed_nikolov_conductance_forced::do_operation(), ed_nikolov_conductance_free::do_operation(), ed_penman_monteith_leaf_temperature::do_operation(), ed_penman_monteith_transpiration::do_operation(), ed_rh_to_mole_fraction::do_operation(), and base::do_operation().
is_differential()
bool is_differential () const inline
Definition at line 46 of file modules.h.
References differential.
requires_euler_ode_solver()
bool requires_euler_ode_solver () const inline
Definition at line 47 of file modules.h.
References requires_euler.
run()
void run () const inline
Definition at line 50 of file modules.h.
References do_operation().
update()
virtual void update (double * output_ptr, const double & value) const protected pure virtual
Implemented in differential_module, and direct_module.
Member Data Documentation
differential
bool const differential private
Definition at line 56 of file modules.h.
Referenced by is_differential().
module_name
std::string const module_name private
Definition at line 55 of file modules.h.
Referenced by get_name().
requires_euler
bool const requires_euler private
Definition at line 57 of file modules.h.
Referenced by requires_euler_ode_solver().
The documentation for this class was generated from the following file:
/github/workspace/source/src/modules.h