The BioCro C++ Library: SteadyModule Class Reference
SteadyModule Class Reference abstract
This class represents a steady state Module.
#include <modules.h>
Inherits Module.
Inherited by multilayer_canopy_photosynthesis< ed_ten_layer_canopy_properties, ed_c4_leaf_photosynthesis4 >, FvCB, Module_1, Module_2, Module_3, ball_berry_module, biomass_leaf_n_limitation, buck_swvp, c3_assimilation, c3_canopy, c3_leaf_photosynthesis, c4_assimilation, c4_canopy, c4_leaf_photosynthesis, ed_abc_blc, ed_apply_stomatal_water_stress_via_assimilation, ed_apply_stomatal_water_stress_via_conductance, ed_ball_berry, ed_boundary_conductance_max, ed_boundary_conductance_quadrature, ed_c4photo, ed_canac_leaf, ed_collatz_c4_assimilation, ed_evapotrans2, ed_gas_concentrations, ed_leaf_temperature, ed_long_wave_energy_loss, ed_multilayer_canopy_integrator, ed_multilayer_canopy_properties, ed_nikolov_conductance_forced, ed_nikolov_conductance_free, ed_penman_monteith_leaf_temperature, ed_penman_monteith_transpiration, ed_rh_to_mole_fraction, ed_stomata_water_stress_linear, ed_water_vapor_properties, fake_solar, golden_ratio_hyperbola, grimm_soybean_flowering_calculator, harmonic_energy, hyperbola_2d, incident_shortwave_from_ground_par, leaf_shape_factor, leaf_water_stress_exponential, light_from_solar, linear_vmax_from_leaf_n, multilayer_canopy_integrator, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >, multilayer_canopy_properties, no_leaf_resp_neg_assim_partitioning_growth_calculator, no_leaf_resp_partitioning_growth_calculator, oscillator_clock_calculator, parameter_calculator, partitioning_coefficient_logistic, partitioning_coefficient_selector, partitioning_growth_calculator, penman_monteith_leaf_temperature, penman_monteith_transpiration, priestley_transpiration, rasmussen_specific_heat, rh_to_mole_fraction, rue_leaf_photosynthesis, base, senescence_coefficient_logistic, shortwave_atmospheric_scattering, soil_evaporation, soil_type_selector, solar_zenith_angle, soybean_development_rate_calculator, stomata_water_stress_exponential, stomata_water_stress_linear, stomata_water_stress_linear_and_aba_response, stomata_water_stress_sigmoid, thermal_time_development_rate_calculator, total_biomass, utilization_growth_calculator, utilization_senescence_calculator, and water_vapor_properties_from_air_temperature.
Public Member Functions
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
virtual ~SteadyModule ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Protected Member Functions
void update (double *output_ptr, const double &value) const
The output parameters of a steady state module are unique, so we can just overwrite the previously stored value.
Detailed Description
This class represents a steady state Module.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 78 of file modules.h.
Constructor & Destructor Documentation
SteadyModule()
SteadyModule (const std::string & module_name, bool adaptive_compatible = true) inline
Definition at line 81 of file modules.h.
~SteadyModule()
~SteadyModule () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 97 of file modules.h.
Member Function Documentation
update()
void update (double * output_ptr, const double & value) const inline protected virtual
The output parameters of a steady state module are unique, so we can just overwrite the previously stored value.
Implements Module.
Definition at line 103 of file modules.h.
Referenced by ball_berry_module::do_operation(), biomass_leaf_n_limitation::do_operation(), buck_swvp::do_operation(), c3_assimilation::do_operation(), c3_canopy::do_operation(), c3_leaf_photosynthesis::do_operation(), c4_assimilation::do_operation(), c4_canopy::do_operation(), c4_leaf_photosynthesis::do_operation(), ed_stomata_water_stress_linear::do_operation(), ed_water_vapor_properties::do_operation(), fake_solar::do_operation(), FvCB::do_operation(), grimm_soybean_flowering_calculator::do_operation(), harmonic_energy::do_operation(), incident_shortwave_from_ground_par::do_operation(), leaf_shape_factor::do_operation(), leaf_water_stress_exponential::do_operation(), light_from_solar::do_operation(), linear_vmax_from_leaf_n::do_operation(), Module_1::do_operation(), Module_2::do_operation(), Module_3::do_operation(), no_leaf_resp_partitioning_growth_calculator::do_operation(), oscillator_clock_calculator::do_operation(), parameter_calculator::do_operation(), partitioning_coefficient_selector::do_operation(), partitioning_growth_calculator::do_operation(), penman_monteith_leaf_temperature::do_operation(), penman_monteith_transpiration::do_operation(), priestley_transpiration::do_operation(), rasmussen_specific_heat::do_operation(), rh_to_mole_fraction::do_operation(), rue_leaf_photosynthesis::do_operation(), shortwave_atmospheric_scattering::do_operation(), soil_evaporation::do_operation(), soil_type_selector::do_operation(), solar_zenith_angle::do_operation(), stomata_water_stress_exponential::do_operation(), stomata_water_stress_linear::do_operation(), stomata_water_stress_linear_and_aba_response::do_operation(), stomata_water_stress_sigmoid::do_operation(), total_biomass::do_operation(), utilization_growth_calculator::do_operation(), utilization_senescence_calculator::do_operation(), water_vapor_properties_from_air_temperature::do_operation(), ed_abc_blc::do_operation(), ed_apply_stomatal_water_stress_via_conductance::do_operation(), ed_apply_stomatal_water_stress_via_assimilation::do_operation(), ed_ball_berry::do_operation(), ed_boundary_conductance_quadrature::do_operation(), ed_boundary_conductance_max::do_operation(), ed_c4photo::do_operation(), ed_canac_leaf::do_operation(), ed_collatz_c4_assimilation::do_operation(), ed_evapotrans2::do_operation(), ed_gas_concentrations::do_operation(), ed_leaf_temperature::do_operation(), ed_long_wave_energy_loss::do_operation(), ed_nikolov_conductance_forced::do_operation(), ed_nikolov_conductance_free::do_operation(), ed_penman_monteith_leaf_temperature::do_operation(), ed_penman_monteith_transpiration::do_operation(), ed_rh_to_mole_fraction::do_operation(), golden_ratio_hyperbola::do_operation(), hyperbola_2d::do_operation(), base::do_operation(), no_leaf_resp_neg_assim_partitioning_growth_calculator::do_operation(), partitioning_coefficient_logistic::do_operation(), senescence_coefficient_logistic::do_operation(), soybean_development_rate_calculator::do_operation(), thermal_time_development_rate_calculator::do_operation(), ed_multilayer_canopy_integrator::run(), ed_multilayer_canopy_properties::run(), multilayer_canopy_integrator::run(), and multilayer_canopy_properties::run().
The documentation for this class was generated from the following file:
/github/workspace/source/src/modules.h