The BioCro C++ Library: integrator Class Reference
integrator Class Reference abstract
#include <integrator.h>
Public Member Functions
integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~integrator ()
state_vector_map integrate (std::shared_ptr< System > sys)
std::string generate_info_report () const
std::string generate_integrate_report () const
Protected Member Functions
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Private Member Functions
virtual state_vector_map do_integrate (std::shared_ptr< System > sys)=0
virtual state_vector_map handle_adaptive_incompatibility (std::shared_ptr< System > sys)
virtual std::string get_param_info () const =0
virtual std::string get_solution_info () const =0
Private Attributes
const std::string integrator_name
const bool check_adaptive_compatible
double output_step_size
double adaptive_rel_error_tol
double adaptive_abs_error_tol
int adaptive_max_steps
bool integrate_method_has_been_called = false
Detailed Description
Definition at line 12 of file integrator.h.
Constructor & Destructor Documentation
integrator()
integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 15 of file integrator.h.
~integrator()
virtual ~integrator () inline virtual
Definition at line 28 of file integrator.h.
Member Function Documentation
do_integrate()
virtual state_vector_map do_integrate (std::shared_ptr< System > sys) private pure virtual
Implemented in homemade_euler_integrator< state_type >, boost_integrator< state_type >, boost_integrator< boost::numeric::ublas::vector< double > >, and auto_integrator< state_type >.
Referenced by integrate().
generate_info_report()
std::string generate_info_report () const inline
Definition at line 32 of file integrator.h.
References get_param_info(), and integrator_name.
generate_integrate_report()
std::string generate_integrate_report () const inline
Definition at line 38 of file integrator.h.
References get_solution_info(), and integrate_method_has_been_called.
get_adaptive_abs_error_tol()
double get_adaptive_abs_error_tol () const inline protected
Definition at line 50 of file integrator.h.
References adaptive_abs_error_tol.
Referenced by boost_rsnbrk_integrator::do_boost_integrate(), boost_rkck54_integrator< state_type >::do_boost_integrate(), boost_rkck54_integrator< state_type >::get_boost_param_info(), and boost_rsnbrk_integrator::get_boost_param_info().
get_adaptive_max_steps()
int get_adaptive_max_steps () const inline protected
Definition at line 51 of file integrator.h.
References adaptive_max_steps.
Referenced by boost_rkck54_integrator< state_type >::get_boost_param_info(), and boost_rsnbrk_integrator::get_boost_param_info().
get_adaptive_rel_error_tol()
double get_adaptive_rel_error_tol () const inline protected
Definition at line 49 of file integrator.h.
References adaptive_rel_error_tol.
Referenced by boost_rsnbrk_integrator::do_boost_integrate(), boost_rkck54_integrator< state_type >::do_boost_integrate(), boost_rkck54_integrator< state_type >::get_boost_param_info(), and boost_rsnbrk_integrator::get_boost_param_info().
get_output_step_size()
double get_output_step_size () const inline protected
Definition at line 48 of file integrator.h.
References output_step_size.
Referenced by boost_integrator< state_type >::get_param_info().
get_param_info()
virtual std::string get_param_info () const private pure virtual
Implemented in homemade_euler_integrator< state_type >, boost_integrator< state_type >, boost_integrator< boost::numeric::ublas::vector< double > >, and auto_integrator< state_type >.
Referenced by generate_info_report().
get_solution_info()
virtual std::string get_solution_info () const private pure virtual
Implemented in homemade_euler_integrator< state_type >, boost_integrator< state_type >, boost_integrator< boost::numeric::ublas::vector< double > >, and auto_integrator< state_type >.
Referenced by generate_integrate_report().
handle_adaptive_incompatibility()
state_vector_map handle_adaptive_incompatibility (std::shared_ptr< System > sys) inline private virtual
Reimplemented in auto_integrator< state_type >.
Definition at line 72 of file integrator.h.
References integrator_name.
Referenced by integrate().
integrate()
state_vector_map integrate (std::shared_ptr< System > sys)
Definition at line 3 of file integrator.cpp.
References check_adaptive_compatible, do_integrate(), handle_adaptive_incompatibility(), and integrate_method_has_been_called.
Member Data Documentation
adaptive_abs_error_tol
double adaptive_abs_error_tol private
Definition at line 59 of file integrator.h.
Referenced by get_adaptive_abs_error_tol().
adaptive_max_steps
int adaptive_max_steps private
Definition at line 60 of file integrator.h.
Referenced by get_adaptive_max_steps().
adaptive_rel_error_tol
double adaptive_rel_error_tol private
Definition at line 58 of file integrator.h.
Referenced by get_adaptive_rel_error_tol().
check_adaptive_compatible
const bool check_adaptive_compatible private
Definition at line 55 of file integrator.h.
Referenced by integrate().
integrate_method_has_been_called
bool integrate_method_has_been_called = false private
Definition at line 62 of file integrator.h.
Referenced by generate_integrate_report(), and integrate().
integrator_name
const std::string integrator_name private
Definition at line 54 of file integrator.h.
Referenced by generate_info_report(), and handle_adaptive_incompatibility().
output_step_size
double output_step_size private
Definition at line 57 of file integrator.h.
Referenced by get_output_step_size().
The documentation for this class was generated from the following files:
/github/workspace/source/src/integrator.h
/github/workspace/source/src/integrator.cpp