The BioCro C++ Library: ten_layer_c4_canopy Class Reference
ten_layer_c4_canopy Class Reference
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Collatz et al. model for C4 photosynthesis; see the c4_leaf_photosynthesis class for more information about this model.
#include <multilayer_c4_canopy.h>
Public Member Functions
ten_layer_c4_canopy (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
multilayer_canopy_photosynthesis (const std::string &module_name, const int &nlayers, state_map const &input_quantities, state_map *output_quantities)
Constructor for a multilayer canopy photosynthesis module, which initializes the leaf module and prepares to pass inputs to it from the canopy module.
Public Member Functions inherited from SteadyModule
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
virtual ~SteadyModule ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
Private Member Functions
void do_operation () const
Static Private Attributes
static int const nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
void run () const
Protected Member Functions inherited from SteadyModule
void update (double *output_ptr, const double &value) const
The output parameters of a steady state module are unique, so we can just overwrite the previously stored value.
Static Protected Member Functions inherited from multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >
static string_vector generate_inputs (int nlayers)
static string_vector generate_outputs (int nlayers)
Detailed Description
Represents a ten layer canopy where leaf-level photosynthesis is calculated using the Collatz et al. model for C4 photosynthesis; see the c4_leaf_photosynthesis class for more information about this model.
More specifically, this is a child class of multilayer_canopy_photosynthesis where:
The canopy module is set to the ten_layer_canopy_properties module
The leaf module is set to the c4_leaf_photosynthesis module
The number of layers is set to 10
Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_photosynthesis.
Definition at line 34 of file multilayer_c4_canopy.h.
Constructor & Destructor Documentation
ten_layer_c4_canopy()
ten_layer_c4_canopy (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 37 of file multilayer_c4_canopy.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements Module.
Definition at line 21 of file multilayer_c4_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::run().
get_inputs()
string_vector get_inputs () static
Definition at line 5 of file multilayer_c4_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_inputs(), and nlayers.
get_outputs()
string_vector get_outputs () static
Definition at line 13 of file multilayer_c4_canopy.cpp.
References multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >::generate_outputs(), and nlayers.
Member Data Documentation
nlayers
int const nlayers = 10 static private
Definition at line 52 of file multilayer_c4_canopy.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following files:
/github/workspace/source/src/module_library/multilayer_c4_canopy.h
/github/workspace/source/src/module_library/multilayer_c4_canopy.cpp