The BioCro C++ Library: differential_module Class Reference
differential_module Class Reference abstract
This class represents a differential module.
#include <modules.h>
Public Member Functions
differential_module (const std::string &module_name, bool requires_euler=false)
virtual ~differential_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (std::string const &module_name, bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Protected Member Functions
void update (double *output_ptr, const double &value) const
The outputs of a differential module represent additive terms in the derivatives of its output quantities, and, in a valid dynamical_system object, it is possible for one derivative to be determined by more than one module; for this reason, the output values should be added to the previously stored values.
Detailed Description
This class represents a differential module.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 120 of file modules.h.
Constructor & Destructor Documentation
differential_module()
differential_module (const std::string & module_name, bool requires_euler = false) inline
Definition at line 123 of file modules.h.
~differential_module()
~differential_module () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 138 of file modules.h.
Member Function Documentation
update()
void update (double * output_ptr, const double & value) const inline protected virtual
The outputs of a differential module represent additive terms in the derivatives of its output quantities, and, in a valid dynamical_system object, it is possible for one derivative to be determined by more than one module; for this reason, the output values should be added to the previously stored values.
See direct_module::update() for a contrasting situation.
Implements module_base.
Definition at line 149 of file modules.h.
Referenced by aba_decay::do_operation(), bucket_soil_drainage::do_operation(), grimm_soybean_flowering::do_operation(), harmonic_oscillator::do_operation(), magic_clock::do_operation(), night_and_day_trackers::do_operation(), nr_ex::do_operation(), one_layer_soil_profile::do_operation(), one_layer_soil_profile_derivatives::do_operation(), phase_clock::do_operation(), poincare_clock::do_operation(), pokhilko_circadian_clock::do_operation(), song_flowering::do_operation(), thermal_time_and_frost_senescence::do_operation(), thermal_time_beta::do_operation(), thermal_time_bilinear::do_operation(), thermal_time_linear::do_operation(), thermal_time_linear_extended::do_operation(), thermal_time_senescence::do_operation(), thermal_time_trilinear::do_operation(), two_layer_soil_profile::do_operation(), utilization_growth::do_operation(), utilization_senescence::do_operation(), development_index::do_operation(), partitioning_growth::do_operation(), and senescence_logistic::do_operation().
The documentation for this class was generated from the following file:
/github/workspace/source/src/modules.h