The BioCro C++ Library: ed_rh_to_mole_fraction Class Reference
ed_rh_to_mole_fraction Class Reference
Just converts relative humidity values from weather data into atmospheric mole fractions of water vapor. Currently only intended for use by Ed.
#include <ed_rh_to_mole_fraction.h>
Public Member Functions
ed_rh_to_mole_fraction (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const override
Private Attributes
const double * atmospheric_pressure_ip
const double * temperature_air_ip
const double * relative_humidity_atmosphere_ip
double * mole_fraction_h2o_atmosphere_op
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Just converts relative humidity values from weather data into atmospheric mole fractions of water vapor. Currently only intended for use by Ed.
Here we just use the definitions of mole fraction and relative humidity:
mole_fraction = partial_pressure / atmospheric_pressure = saturation_water_vapor_pressure * relative_humidity / atmospheric_pressure
Definition at line 21 of file ed_rh_to_mole_fraction.h.
Constructor & Destructor Documentation
ed_rh_to_mole_fraction()
ed_rh_to_mole_fraction (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 24 of file ed_rh_to_mole_fraction.h.
Member Function Documentation
do_operation()
void do_operation () const override private virtual
Implements module.
Definition at line 71 of file ed_rh_to_mole_fraction.h.
References atmospheric_pressure_ip, check_error_conditions(), calculation_constants::eps_zero, get_name(), mole_fraction_h2o_atmosphere_op, relative_humidity_atmosphere_ip, saturation_vapor_pressure(), temperature_air_ip, and direct_module::update().
get_inputs()
string_vector get_inputs () static
Definition at line 55 of file ed_rh_to_mole_fraction.h.
get_name()
static std::string get_name () inline static
Definition at line 40 of file ed_rh_to_mole_fraction.h.
Referenced by do_operation().
get_outputs()
string_vector get_outputs () static
Definition at line 64 of file ed_rh_to_mole_fraction.h.
Member Data Documentation
atmospheric_pressure_ip
const double* atmospheric_pressure_ip private
Definition at line 44 of file ed_rh_to_mole_fraction.h.
Referenced by do_operation().
mole_fraction_h2o_atmosphere_op
double* mole_fraction_h2o_atmosphere_op private
Definition at line 49 of file ed_rh_to_mole_fraction.h.
Referenced by do_operation().
relative_humidity_atmosphere_ip
const double* relative_humidity_atmosphere_ip private
Definition at line 46 of file ed_rh_to_mole_fraction.h.
Referenced by do_operation().
temperature_air_ip
const double* temperature_air_ip private
Definition at line 45 of file ed_rh_to_mole_fraction.h.
Referenced by do_operation().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_rh_to_mole_fraction.h