The BioCro C++ Library: DerivModule Class Reference
DerivModule Class Reference abstract
This class represents a derivative Module.
#include <modules.h>
Public Member Functions
DerivModule (const std::string &module_name, bool adaptive_compatible=true)
virtual ~DerivModule ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Protected Member Functions
void update (double *output_ptr, const double &value) const
Derivative modules calculate terms of a derivative and it is possible for one derivative to be determined by multiple modules; for this reason, the outputs should be added to the previously stored value.
Detailed Description
This class represents a derivative Module.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 116 of file modules.h.
Constructor & Destructor Documentation
DerivModule()
DerivModule (const std::string & module_name, bool adaptive_compatible = true) inline
Definition at line 119 of file modules.h.
~DerivModule()
~DerivModule () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 134 of file modules.h.
Member Function Documentation
update()
void update (double * output_ptr, const double & value) const inline protected virtual
Derivative modules calculate terms of a derivative and it is possible for one derivative to be determined by multiple modules; for this reason, the outputs should be added to the previously stored value.
Implements Module.
Definition at line 141 of file modules.h.
Referenced by aba_decay::do_operation(), bucket_soil_drainage::do_operation(), c3_assimilation::do_operation(), c4_assimilation::do_operation(), grimm_soybean_flowering::do_operation(), harmonic_oscillator::do_operation(), magic_clock::do_operation(), night_and_day_trackers::do_operation(), nr_ex::do_operation(), one_layer_soil_profile::do_operation(), one_layer_soil_profile_derivatives::do_operation(), phase_clock::do_operation(), poincare_clock::do_operation(), pokhilko_circadian_clock::do_operation(), song_flowering::do_operation(), thermal_time_and_frost_senescence::do_operation(), thermal_time_beta::do_operation(), thermal_time_bilinear::do_operation(), thermal_time_linear::do_operation(), thermal_time_linear_extended::do_operation(), thermal_time_senescence::do_operation(), thermal_time_trilinear::do_operation(), two_layer_soil_profile::do_operation(), utilization_growth::do_operation(), utilization_senescence::do_operation(), development_index::do_operation(), partitioning_growth::do_operation(), and senescence_logistic::do_operation().
The documentation for this class was generated from the following file:
/github/workspace/source/src/modules.h