The BioCro C++ Library: ed_c4_leaf_photosynthesis4 Class Reference
ed_c4_leaf_photosynthesis4 Class Reference
Solves a set of modules for the unknown quantities assimilation_net, conductance_stomatal_h2o, and temperature_leaf.
#include <ed_c4_leaf_photosynthesis4.h>
Public Member Functions
ed_c4_leaf_photosynthesis4 (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from base
base (std::string module_name, string_vector sub_module_names, std::string solver_name, int max_iterations, std::vector< double > lower_bounds, std::vector< double > upper_bounds, std::vector< double > absolute_error_tolerances, std::vector< double > relative_error_tolerances, bool should_reorder_guesses, bool return_default_on_failure, state_map const &input_quantities, state_map *output_quantities)
virtual ~base ()=0
A destructor must be defined, and since the default is overwritten when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from SteadyModule
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
virtual ~SteadyModule ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
Private Member Functions
void get_default (std::vector< double > &guess_vec) const override
std::vector< std::vector< double > > get_initial_guesses () const override
Private Attributes
double const & collatz_PAR_flux
double const & StomataWS
double const & collatz_q10
double const & temperature_air
double const & collatz_rd
double const & collatz_k
double const & collatz_vmax
double const & collatz_rubisco_temperature_lower
double const & collatz_rubisco_temperature_upper
double const & mole_fraction_co2_atmosphere
double const & relative_humidity_atmosphere
double const & conductance_stomatal_h2o_min
double const & ball_berry_slope
double const & ball_berry_intercept
Additional Inherited Members
Protected Member Functions inherited from SteadyModule
void update (double *output_ptr, const double &value) const
The output parameters of a steady state module are unique, so we can just overwrite the previously stored value.
Detailed Description
Solves a set of modules for the unknown quantities assimilation_net, conductance_stomatal_h2o, and temperature_leaf.
Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
Definition at line 78 of file ed_c4_leaf_photosynthesis4.h.
Constructor & Destructor Documentation
ed_c4_leaf_photosynthesis4()
ed_c4_leaf_photosynthesis4 (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 81 of file ed_c4_leaf_photosynthesis4.h.
Member Function Documentation
get_default()
void get_default (std::vector< double > & guess_vec) const override private virtual
Reimplemented from base.
Definition at line 151 of file ed_c4_leaf_photosynthesis4.h.
References ball_berry_intercept, ball_berry_slope, collatz_k, collatz_PAR_flux, collatz_q10, collatz_rd, collatz_rubisco_temperature_lower, collatz_rubisco_temperature_upper, collatz_vmax, conductance_stomatal_h2o_min, mole_fraction_co2_atmosphere, relative_humidity_atmosphere, StomataWS, and temperature_air.
Referenced by get_initial_guesses().
get_initial_guesses()
std::vector< std::vector< double > > get_initial_guesses () const override private virtual
Implements base.
Definition at line 212 of file ed_c4_leaf_photosynthesis4.h.
References eclp4_print, and get_default().
get_inputs()
string_vector get_inputs () static
Definition at line 137 of file ed_c4_leaf_photosynthesis4.h.
References se_module::get_se_inputs(), and ed_c4_leaf_photosynthesis4_stuff::sub_module_names.
get_outputs()
string_vector get_outputs () static
Definition at line 142 of file ed_c4_leaf_photosynthesis4.h.
References se_module::get_ncalls_output_name(), se_module::get_nsteps_output_name(), se_module::get_se_outputs(), se_module::get_success_output_name(), ed_c4_leaf_photosynthesis4_stuff::module_name, and ed_c4_leaf_photosynthesis4_stuff::sub_module_names.
Member Data Documentation
ball_berry_intercept
double const& ball_berry_intercept private
Definition at line 131 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
ball_berry_slope
double const& ball_berry_slope private
Definition at line 130 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_k
double const& collatz_k private
Definition at line 123 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_PAR_flux
double const& collatz_PAR_flux private
Definition at line 118 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_q10
double const& collatz_q10 private
Definition at line 120 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_rd
double const& collatz_rd private
Definition at line 122 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_rubisco_temperature_lower
double const& collatz_rubisco_temperature_lower private
Definition at line 125 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_rubisco_temperature_upper
double const& collatz_rubisco_temperature_upper private
Definition at line 126 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
collatz_vmax
double const& collatz_vmax private
Definition at line 124 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
conductance_stomatal_h2o_min
double const& conductance_stomatal_h2o_min private
Definition at line 129 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
mole_fraction_co2_atmosphere
double const& mole_fraction_co2_atmosphere private
Definition at line 127 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
relative_humidity_atmosphere
double const& relative_humidity_atmosphere private
Definition at line 128 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
StomataWS
double const& StomataWS private
Definition at line 119 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
temperature_air
double const& temperature_air private
Definition at line 121 of file ed_c4_leaf_photosynthesis4.h.
Referenced by get_default().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_c4_leaf_photosynthesis4.h