The BioCro C++ Library: ed_c4_leaf_photosynthesis Class Reference
ed_c4_leaf_photosynthesis Class Reference
Solves a set of modules for the unknown quantities assimilation_net, conductance_boundary_h2o_free, conductance_stomatal_h2o, and temperature_leaf. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
#include <ed_c4_leaf_photosynthesis.h>
Public Member Functions
ed_c4_leaf_photosynthesis (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from base
base (std::string module_name, mc_vector sub_mcs, std::string solver_name, int max_iterations, std::vector< double > lower_bounds, std::vector< double > upper_bounds, std::vector< double > absolute_error_tolerances, std::vector< double > relative_error_tolerances, bool should_reorder_guesses, bool return_default_on_failure, state_map const &input_quantities, state_map *output_quantities)
virtual ~base ()=0
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
std::vector< std::vector< double > > get_initial_guesses () const override
Private Attributes
double const & collatz_k
double const & collatz_vmax
double const & collatz_alpha
double const & collatz_PAR_flux
double const & collatz_rd
double const & ball_berry_intercept
double const & ball_berry_slope
double const & nikolov_ce
double const & leafwidth
double const & StomataWS
double const & conductance_stomatal_h2o_min
double const & mole_fraction_co2_atmosphere
double const & relative_humidity_atmosphere
double const & temperature_air
double const & solar_energy_absorbed_leaf
double const & atmospheric_pressure
double const & specific_heat_of_air
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Solves a set of modules for the unknown quantities assimilation_net, conductance_boundary_h2o_free, conductance_stomatal_h2o, and temperature_leaf. Also returns other quantities derived from these. Represents photosynthesis at the leaf level for a c4 plant.
Definition at line 118 of file ed_c4_leaf_photosynthesis.h.
Constructor & Destructor Documentation
ed_c4_leaf_photosynthesis()
ed_c4_leaf_photosynthesis (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 121 of file ed_c4_leaf_photosynthesis.h.
Member Function Documentation
get_initial_guesses()
std::vector< std::vector< double > > get_initial_guesses () const override private virtual
Implements base.
Definition at line 197 of file ed_c4_leaf_photosynthesis.h.
References ed_c4_leaf_photosynthesis::atmospheric_pressure, ed_c4_leaf_photosynthesis::ball_berry_intercept, ed_c4_leaf_photosynthesis::ball_berry_slope, conversion_constants::celsius_to_kelvin, ed_c4_leaf_photosynthesis::collatz_alpha, ed_c4_leaf_photosynthesis::collatz_k, ed_c4_leaf_photosynthesis::collatz_PAR_flux, ed_c4_leaf_photosynthesis::collatz_rd, ed_c4_leaf_photosynthesis::collatz_vmax, ed_c4_leaf_photosynthesis::conductance_stomatal_h2o_min, eclp_print, generate_guess_list(), physical_constants::ideal_gas_constant, ed_c4_leaf_photosynthesis::leafwidth, ed_c4_leaf_photosynthesis_stuff::lower_bounds, physical_constants::molar_mass_of_water, ed_c4_leaf_photosynthesis::mole_fraction_co2_atmosphere, ed_c4_leaf_photosynthesis::nikolov_ce, ed_c4_leaf_photosynthesis_stuff::num_guesses_to_try_educated, ed_c4_leaf_photosynthesis_stuff::num_guesses_to_try_other, ed_c4_leaf_photosynthesis::relative_humidity_atmosphere, saturation_vapor_pressure(), ed_c4_leaf_photosynthesis::solar_energy_absorbed_leaf, ed_c4_leaf_photosynthesis::specific_heat_of_air, ed_c4_leaf_photosynthesis::StomataWS, ed_c4_leaf_photosynthesis::temperature_air, nikolov::temperature_exponent, nikolov::temperature_offset, TempToDdryA(), TempToLHV(), TempToSFS(), nikolov::Tvdiff_factor, and ed_c4_leaf_photosynthesis_stuff::upper_bounds.
get_inputs()
string_vector get_inputs () static
Definition at line 183 of file ed_c4_leaf_photosynthesis.h.
References se_module::get_se_inputs(), and ed_c4_leaf_photosynthesis_stuff::sub_mcs.
get_name()
static std::string get_name () inline static
Definition at line 158 of file ed_c4_leaf_photosynthesis.h.
References ed_c4_leaf_photosynthesis_stuff::module_name.
get_outputs()
string_vector get_outputs () static
Definition at line 188 of file ed_c4_leaf_photosynthesis.h.
References se_module::get_ncalls_output_name(), se_module::get_nsteps_output_name(), se_module::get_se_outputs(), se_module::get_success_output_name(), ed_c4_leaf_photosynthesis_stuff::module_name, and ed_c4_leaf_photosynthesis_stuff::sub_mcs.
Member Data Documentation
atmospheric_pressure
double const& atmospheric_pressure private
Definition at line 177 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
ball_berry_intercept
double const& ball_berry_intercept private
Definition at line 167 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
ball_berry_slope
double const& ball_berry_slope private
Definition at line 168 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
collatz_alpha
double const& collatz_alpha private
Definition at line 164 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
collatz_k
double const& collatz_k private
Definition at line 162 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
collatz_PAR_flux
double const& collatz_PAR_flux private
Definition at line 165 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
collatz_rd
double const& collatz_rd private
Definition at line 166 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
collatz_vmax
double const& collatz_vmax private
Definition at line 163 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
conductance_stomatal_h2o_min
double const& conductance_stomatal_h2o_min private
Definition at line 172 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
leafwidth
double const& leafwidth private
Definition at line 170 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
mole_fraction_co2_atmosphere
double const& mole_fraction_co2_atmosphere private
Definition at line 173 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
nikolov_ce
double const& nikolov_ce private
Definition at line 169 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
relative_humidity_atmosphere
double const& relative_humidity_atmosphere private
Definition at line 174 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
solar_energy_absorbed_leaf
double const& solar_energy_absorbed_leaf private
Definition at line 176 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
specific_heat_of_air
double const& specific_heat_of_air private
Definition at line 178 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
StomataWS
double const& StomataWS private
Definition at line 171 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
temperature_air
double const& temperature_air private
Definition at line 175 of file ed_c4_leaf_photosynthesis.h.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_c4_leaf_photosynthesis.h