The BioCro C++ Library: Module Class Reference
Module Class Reference abstract
Represents a component of a larger system of differential equations.
#include <modules.h>
Public Member Functions
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Protected Member Functions
virtual void update (double *output_ptr, const double &value) const =0
Private Member Functions
virtual void do_operation () const =0
Private Attributes
std::string const module_name
bool const deriv
bool const adaptive_compatible
Detailed Description
Represents a component of a larger system of differential equations.
A module can be one of the following subtypes:
SteadyModule: a "steady state" module that calculates the value(s) of one or more quantities
DerivModule: a "derivative" module that calculates the rate(s) of change for one or more quantities
A module must also indicate whether or not it is compatible with adaptive step size integrators. For most modules, this is the case. However, a few "legacy" modules require information from previous times and will only work properly with a fixed step size Euler integrator.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 29 of file modules.h.
Constructor & Destructor Documentation
Module()
Module (std::string const & module_name, bool const & deriv, bool const & adaptive_compatible) inline
Definition at line 32 of file modules.h.
~Module()
~Module () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 68 of file modules.h.
Member Function Documentation
do_operation()
virtual void do_operation () const private pure virtual
Implemented in thermal_time_development_rate_calculator, soybean_development_rate_calculator, senescence_logistic, senescence_coefficient_logistic, partitioning_growth, partitioning_coefficient_logistic, no_leaf_resp_neg_assim_partitioning_growth_calculator, development_index, base, hyperbola_2d, golden_ratio_hyperbola, ed_rh_to_mole_fraction, ed_penman_monteith_transpiration, ed_penman_monteith_leaf_temperature, ed_nikolov_conductance_free, ed_nikolov_conductance_forced, ed_long_wave_energy_loss, ed_leaf_temperature, ed_gas_concentrations, ed_evapotrans2, ed_collatz_c4_assimilation, ed_canac_leaf, ed_c4photo, ed_boundary_conductance_max, ed_boundary_conductance_quadrature, ed_ball_berry, ed_apply_stomatal_water_stress_via_assimilation, ed_apply_stomatal_water_stress_via_conductance, ed_abc_blc, water_vapor_properties_from_air_temperature, utilization_senescence_calculator, utilization_senescence, utilization_growth_calculator, utilization_growth, two_layer_soil_profile, total_biomass, thermal_time_trilinear, thermal_time_senescence, thermal_time_linear_extended, thermal_time_linear, thermal_time_bilinear, thermal_time_beta, thermal_time_and_frost_senescence, stomata_water_stress_sigmoid, stomata_water_stress_linear_and_aba_response, stomata_water_stress_linear, stomata_water_stress_exponential, song_flowering, solar_zenith_angle, soil_type_selector, soil_evaporation, shortwave_atmospheric_scattering, rue_leaf_photosynthesis, rh_to_mole_fraction, rasmussen_specific_heat, priestley_transpiration, pokhilko_circadian_clock, poincare_clock, phase_clock, penman_monteith_transpiration, penman_monteith_leaf_temperature, partitioning_growth_calculator, partitioning_coefficient_selector, parameter_calculator, oscillator_clock_calculator, one_layer_soil_profile_derivatives, one_layer_soil_profile, nr_ex, no_leaf_resp_partitioning_growth_calculator, night_and_day_trackers, ten_layer_rue_canopy, ten_layer_canopy_properties, ten_layer_canopy_integrator, multilayer_canopy_integrator, ten_layer_c4_canopy, ten_layer_c3_canopy, Module_3, Module_2, Module_1, magic_clock, linear_vmax_from_leaf_n, light_from_solar, leaf_water_stress_exponential, leaf_shape_factor, incident_shortwave_from_ground_par, harmonic_energy, harmonic_oscillator, grimm_soybean_flowering_calculator, grimm_soybean_flowering, FvCB, fake_solar, empty_senescence, ed_water_vapor_properties, ed_stomata_water_stress_linear, ed_ten_layer_canopy_properties, ed_ten_layer_canopy_integrator, ed_multilayer_canopy_integrator, ed_ten_layer_c4_canopy, c4_leaf_photosynthesis, c4_canopy, c4_assimilation, c3_leaf_photosynthesis, c3_canopy, c3_assimilation, bucket_soil_drainage, buck_swvp, biomass_leaf_n_limitation, ball_berry_module, and aba_decay.
Referenced by run().
get_name()
std::string get_name () const inline
Definition at line 45 of file modules.h.
References module_name.
Referenced by incident_shortwave_from_ground_par::do_operation(), rh_to_mole_fraction::do_operation(), ed_ball_berry::do_operation(), ed_collatz_c4_assimilation::do_operation(), ed_gas_concentrations::do_operation(), ed_leaf_temperature::do_operation(), ed_nikolov_conductance_forced::do_operation(), ed_nikolov_conductance_free::do_operation(), ed_penman_monteith_leaf_temperature::do_operation(), ed_penman_monteith_transpiration::do_operation(), ed_rh_to_mole_fraction::do_operation(), and base::do_operation().
is_adaptive_compatible()
bool is_adaptive_compatible () const inline
Definition at line 47 of file modules.h.
References adaptive_compatible.
is_deriv()
bool is_deriv () const inline
Definition at line 46 of file modules.h.
References deriv.
run()
void run () const inline
Definition at line 50 of file modules.h.
References do_operation().
update()
virtual void update (double * output_ptr, const double & value) const protected pure virtual
Implemented in DerivModule, and SteadyModule.
Member Data Documentation
adaptive_compatible
bool const adaptive_compatible private
Definition at line 57 of file modules.h.
Referenced by is_adaptive_compatible().
deriv
bool const deriv private
Definition at line 56 of file modules.h.
Referenced by is_deriv().
module_name
std::string const module_name private
Definition at line 55 of file modules.h.
Referenced by get_name().
The documentation for this class was generated from the following file:
/github/workspace/source/src/modules.h