The BioCro C++ Library: ed_nikolov_conductance_free_solve Class Reference
ed_nikolov_conductance_free_solve Class Reference
Calculates free boundary layer conductance for water according to the model in Nikolov et al. Ecological Modelling 80, 205–235 (1995). Note that this module has conductance_boundary_h2o_free as both an input and an output. Therefore, it can be used by a simultanous_equations object but not a dynamical_system object. Currently only intended for use by Ed.
#include <ed_nikolov_conductance.h>
Public Member Functions
ed_nikolov_conductance_free_solve (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from base
base (std::string module_name, string_vector sub_module_names, std::string solver_name, int max_iterations, std::vector< double > lower_bounds, std::vector< double > upper_bounds, std::vector< double > absolute_error_tolerances, std::vector< double > relative_error_tolerances, bool should_reorder_guesses, bool return_default_on_failure, state_map const &input_quantities, state_map *output_quantities)
virtual ~base ()=0
Public Member Functions inherited from direct_module
direct_module (const std::string &module_name, bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (std::string const &module_name, bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
std::string get_name () const
bool is_differential () const
bool requires_euler_integrator () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
Private Member Functions
void get_default (std::vector< double > &guess_vec) const override
std::vector< std::vector< double > > get_initial_guesses () const override
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Calculates free boundary layer conductance for water according to the model in Nikolov et al. Ecological Modelling 80, 205–235 (1995). Note that this module has conductance_boundary_h2o_free as both an input and an output. Therefore, it can be used by a simultanous_equations object but not a dynamical_system object. Currently only intended for use by Ed.
See the "ed_nikolov_conductance_forced" module for a discussion of conductance units and assumptions about temperature.
Definition at line 324 of file ed_nikolov_conductance.h.
Constructor & Destructor Documentation
ed_nikolov_conductance_free_solve()
ed_nikolov_conductance_free_solve (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 327 of file ed_nikolov_conductance.h.
Member Function Documentation
get_default()
void get_default (std::vector< double > & guess_vec) const override private virtual
Reimplemented from base.
Definition at line 367 of file ed_nikolov_conductance.h.
get_initial_guesses()
std::vector< std::vector< double > > get_initial_guesses () const override private virtual
Implements base.
Definition at line 374 of file ed_nikolov_conductance.h.
get_inputs()
string_vector get_inputs () static
Definition at line 353 of file ed_nikolov_conductance.h.
References se_module::get_se_inputs(), and ed_nikolov_conductance_free_solve_stuff::sub_module_names.
get_outputs()
string_vector get_outputs () static
Definition at line 358 of file ed_nikolov_conductance.h.
References se_module::get_ncalls_output_name(), se_module::get_nsteps_output_name(), se_module::get_se_outputs(), se_module::get_success_output_name(), ed_nikolov_conductance_free_solve_stuff::module_name, and ed_nikolov_conductance_free_solve_stuff::sub_module_names.
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_nikolov_conductance.h