The BioCro C++ Library: boost_integrator< state_type > Class Template Reference
boost_integrator< state_type > Class Template Reference abstract
A class representing a generic boost system integrator.
#include <boost_integrators.h>
Public Member Functions
boost_integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from integrator
integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~integrator ()
state_vector_map integrate (std::shared_ptr< System > sys)
std::string generate_info_report () const
std::string generate_integrate_report () const
Protected Member Functions
template<class stepper_type >
void run_integrate_const (stepper_type stepper, SystemCaller syscall, push_back_state_and_time< state_type > observer)
Protected Member Functions inherited from integrator
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Private Member Functions
state_vector_map do_integrate (std::shared_ptr< System > sys) override
virtual void do_boost_integrate (SystemCaller syscall, push_back_state_and_time< state_type > &observer)=0
std::string get_param_info () const override
virtual std::string get_boost_param_info () const =0
std::string get_solution_info () const override
Private Attributes
std::string boost_error_string
size_t nsteps
state_type state
std::vector< state_type > state_vec
std::vector< double > time_vec
std::string observer_message
Detailed Description
template<class state_type>
class boost_integrator< state_type >
A class representing a generic boost system integrator.
Definition at line 13 of file boost_integrators.h.
Constructor & Destructor Documentation
boost_integrator()
boost_integrator (std::string integrator_name, bool check_adaptive_compatible, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 16 of file boost_integrators.h.
Member Function Documentation
do_boost_integrate()
virtual void do_boost_integrate (SystemCaller syscall, push_back_state_and_time< state_type > & observer) private pure virtual
Implemented in boost_rkck54_integrator< state_type >, boost_rk4_integrator< state_type >, and boost_euler_integrator< state_type >.
do_integrate()
state_vector_map do_integrate (std::shared_ptr< System > sys) override private virtual
Implements integrator.
Definition at line 75 of file boost_integrators.h.
References get_results_from_system().
get_boost_param_info()
virtual std::string get_boost_param_info () const private pure virtual
Implemented in boost_rsnbrk_integrator, boost_rkck54_integrator< state_type >, boost_rk4_integrator< state_type >, and boost_euler_integrator< state_type >.
Referenced by boost_integrator< state_type >::get_param_info().
get_param_info()
std::string get_param_info () const inline override private virtual
Implements integrator.
Definition at line 48 of file boost_integrators.h.
References boost_integrator< state_type >::get_boost_param_info(), and integrator::get_output_step_size().
get_solution_info()
std::string get_solution_info () const inline override private virtual
Implements integrator.
Definition at line 58 of file boost_integrators.h.
References boost_integrator< state_type >::boost_error_string, boost_integrator< state_type >::nsteps, and boost_integrator< state_type >::observer_message.
run_integrate_const()
void run_integrate_const (stepper_type stepper, SystemCaller syscall, push_back_state_and_time< state_type > observer) protected
Definition at line 99 of file boost_integrators.h.
References SystemPointerWrapper::get_ntimes().
Referenced by boost_euler_integrator< state_type >::do_boost_integrate(), boost_rk4_integrator< state_type >::do_boost_integrate(), and boost_rkck54_integrator< state_type >::do_boost_integrate().
Member Data Documentation
boost_error_string
std::string boost_error_string private
Definition at line 38 of file boost_integrators.h.
Referenced by boost_integrator< state_type >::get_solution_info().
nsteps
size_t nsteps private
Definition at line 39 of file boost_integrators.h.
Referenced by boost_integrator< state_type >::get_solution_info().
observer_message
std::string observer_message private
Definition at line 44 of file boost_integrators.h.
Referenced by boost_integrator< state_type >::get_solution_info().
state
state_type state private
Definition at line 41 of file boost_integrators.h.
state_vec
std::vector<state_type> state_vec private
Definition at line 42 of file boost_integrators.h.
time_vec
std::vector<double> time_vec private
Definition at line 43 of file boost_integrators.h.
The documentation for this class was generated from the following file:
/github/workspace/source/src/integrator_library/boost_integrators.h