The BioCro C++ Library: module_wrapper_factory Class Reference
module_wrapper_factory Class Reference
#include <module_wrapper_factory.h>
Static Public Member Functions
static std::unique_ptr< module_wrapper_base > create (std::string const &module_name)
static std::string get_description (std::string const &module_name)
static std::vector< std::string > get_modules ()
static std::unordered_map< std::string, std::vector< std::string > > get_all_quantities ()
Private Types
using module_wrapper_creator = std::unique_ptr< module_wrapper_base >(*)()
using module_wrapper_creator_map = std::map< std::string, module_wrapper_creator >
Static Private Attributes
static module_wrapper_creator_map module_wrapper_creators
Detailed Description
Definition at line 11 of file module_wrapper_factory.h.
Member Typedef Documentation
module_wrapper_creator
using module_wrapper_creator = std::unique_ptr<module_wrapper_base> (*)() private
Definition at line 20 of file module_wrapper_factory.h.
module_wrapper_creator_map
using module_wrapper_creator_map = std::map<std::string, module_wrapper_creator> private
Definition at line 21 of file module_wrapper_factory.h.
Member Function Documentation
create()
std::unique_ptr< module_wrapper_base > create (std::string const & module_name) static
Definition at line 107 of file module_wrapper_factory.cpp.
References ed_c4_leaf_photosynthesis_stuff::module_name, and module_wrapper_creators.
Referenced by define_quantity_map(), find_misordered_modules(), find_strictly_required_inputs(), find_undefined_module_inputs(), find_undefined_module_outputs(), find_unique_module_inputs(), find_unique_module_outputs(), get_all_quantities(), get_defined_quantity_names(), get_module_inputs(), get_module_outputs(), get_module_vector(), R_get_module_info(), R_test_module(), and R_test_standalone_ss().
get_all_quantities()
std::unordered_map< std::string, std::vector< std::string > > get_all_quantities () static
Definition at line 250 of file module_wrapper_factory.cpp.
References create(), get_modules(), and ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by R_get_all_quantities().
get_description()
static std::string get_description (std::string const & module_name) static
get_modules()
std::vector< std::string > get_modules () static
Definition at line 225 of file module_wrapper_factory.cpp.
References module_wrapper_creators.
Referenced by get_all_quantities(), and R_get_all_modules().
Member Data Documentation
module_wrapper_creators
module_wrapper_factory::module_wrapper_creator_map module_wrapper_creators static private
Definition at line 22 of file module_wrapper_factory.h.
Referenced by create(), and get_modules().
The documentation for this class was generated from the following files:
/github/workspace/source/src/module_library/module_wrapper_factory.h
/github/workspace/source/src/module_library/module_wrapper_factory.cpp