The BioCro C++ Library: ed_ten_layer_canopy_properties Class Reference
ed_ten_layer_canopy_properties Class Reference
A child class of ed_multilayer_canopy_properties where the number of layers has been defined.
#include <ed_multilayer_canopy_properties.h>
Public Member Functions
ed_ten_layer_canopy_properties (const std::unordered_map< std::string, double > *input_parameters, std::unordered_map< std::string, double > *output_parameters)
Public Member Functions inherited from ed_multilayer_canopy_properties
ed_multilayer_canopy_properties (std::string const &module_name, int const &nlayers, state_map const *input_parameters, state_map *output_parameters)
Public Member Functions inherited from SteadyModule
SteadyModule (const std::string &module_name, bool adaptive_compatible=true)
Public Member Functions inherited from Module
Module (std::string const &module_name, bool const &deriv, bool const &adaptive_compatible)
virtual ~Module ()=0
std::string get_name () const
bool is_deriv () const
bool is_adaptive_compatible () const
void run () const
Static Public Member Functions
static std::vector< std::string > get_inputs ()
static std::vector< std::string > define_leaf_classes ()
static std::vector< std::string > define_multiclass_multilayer_outputs ()
static std::vector< std::string > define_pure_multilayer_outputs ()
static std::vector< std::string > get_outputs ()
Private Member Functions
void do_operation () const
Static Private Attributes
static const int nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from ed_multilayer_canopy_properties
void run () const
Protected Member Functions inherited from SteadyModule
void update (double *output_ptr, const double &value) const
Protected Member Functions inherited from Module
double get_val_debug (const double *ptr, const std::string name) const
Static Protected Member Functions inherited from ed_multilayer_canopy_properties
static std::vector< std::string > get_inputs (int nlayers)
Define all inputs required by the module.
static std::vector< std::string > define_leaf_classes ()
Define the different leaf classes included by the module.
static std::vector< std::string > define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static std::vector< std::string > define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static std::vector< std::string > get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes.
Static Protected Attributes inherited from Module
static const double eps = 1e-10
Detailed Description
A child class of ed_multilayer_canopy_properties where the number of layers has been defined.
Instances of this class can be created using the module factory.
Definition at line 267 of file ed_multilayer_canopy_properties.h.
Constructor & Destructor Documentation
ed_ten_layer_canopy_properties()
ed_ten_layer_canopy_properties (const std::unordered_map< std::string, double > * input_parameters, std::unordered_map< std::string, double > * output_parameters) inline
Definition at line 270 of file ed_multilayer_canopy_properties.h.
Member Function Documentation
define_leaf_classes()
std::vector< std::string > define_leaf_classes () static
Definition at line 299 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_leaf_classes().
define_multiclass_multilayer_outputs()
std::vector< std::string > define_multiclass_multilayer_outputs () static
Definition at line 304 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_multiclass_multilayer_outputs().
define_pure_multilayer_outputs()
std::vector< std::string > define_pure_multilayer_outputs () static
Definition at line 310 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::define_pure_multilayer_outputs().
do_operation()
void do_operation () const private virtual
Reimplemented from Module.
Definition at line 321 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::run().
get_inputs()
std::vector< std::string > get_inputs () static
Definition at line 294 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::get_inputs(), and nlayers.
get_outputs()
std::vector< std::string > get_outputs () static
Definition at line 316 of file ed_multilayer_canopy_properties.h.
References ed_multilayer_canopy_properties::get_outputs(), and nlayers.
Member Data Documentation
nlayers
const int nlayers = 10 static private
Definition at line 287 of file ed_multilayer_canopy_properties.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_multilayer_canopy_properties.h