The BioCro C++ Library: ed_p_m_temperature_solve Class Reference
ed_p_m_temperature_solve Class Reference
Calculates leaf temperature using the Penman-Monteith equation, where boundary layer conductance is determined using the model from Nikolov et al. Currently only intended for use by Ed.
#include <ed_penman_monteith_leaf_temperature.h>
Public Member Functions
ed_p_m_temperature_solve (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from base
base (std::string module_name, mc_vector sub_mcs, std::string solver_name, int max_iterations, std::vector< double > lower_bounds, std::vector< double > upper_bounds, std::vector< double > absolute_error_tolerances, std::vector< double > relative_error_tolerances, bool should_reorder_guesses, bool return_default_on_failure, state_map const &input_quantities, state_map *output_quantities)
virtual ~base ()=0
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
std::vector< std::vector< double > > get_initial_guesses () const override
Private Attributes
double const & temperature_air
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Calculates leaf temperature using the Penman-Monteith equation, where boundary layer conductance is determined using the model from Nikolov et al. Currently only intended for use by Ed.
Definition at line 176 of file ed_penman_monteith_leaf_temperature.h.
Constructor & Destructor Documentation
ed_p_m_temperature_solve()
ed_p_m_temperature_solve (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 179 of file ed_penman_monteith_leaf_temperature.h.
Member Function Documentation
get_initial_guesses()
std::vector< std::vector< double > > get_initial_guesses () const override private virtual
Implements base.
Definition at line 227 of file ed_penman_monteith_leaf_temperature.h.
References temperature_air, and nikolov::temperature_offset.
get_inputs()
string_vector get_inputs () static
Definition at line 211 of file ed_penman_monteith_leaf_temperature.h.
References se_module::get_se_inputs(), and ed_p_m_temperature_solve_stuff::sub_mcs.
get_name()
static std::string get_name () inline static
Definition at line 201 of file ed_penman_monteith_leaf_temperature.h.
References ed_p_m_temperature_solve_stuff::module_name.
get_outputs()
string_vector get_outputs () static
Definition at line 218 of file ed_penman_monteith_leaf_temperature.h.
References se_module::get_ncalls_output_name(), se_module::get_nsteps_output_name(), se_module::get_se_outputs(), se_module::get_success_output_name(), ed_p_m_temperature_solve_stuff::module_name, and ed_p_m_temperature_solve_stuff::sub_mcs.
Member Data Documentation
temperature_air
double const& temperature_air private
Definition at line 205 of file ed_penman_monteith_leaf_temperature.h.
Referenced by get_initial_guesses().
The documentation for this class was generated from the following file:
/github/workspace/source/src/module_library/ed_penman_monteith_leaf_temperature.h