The BioCro C++ Library: /github/workspace/source/src/framework/utils/module_dependency_utilities.cpp File Reference
module_dependency_utilities.cpp File Reference
#include "module_dependency_utilities.h"
#include <boost/config.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/topological_sort.hpp>
#include "../state_map.h"
Classes
class cycle_detector
A class suitable to use as a visitor for detecting a cycle in a directed graph.
Typedefs
using Graph = boost::adjacency_list< boost::setS, boost::listS, boost::directedS, boost::property< boost::vertex_name_t, module_creator *, boost::property< boost::vertex_index_t, std::size_t > > >
Graph is the type of a directed Boost graph without multi-edges implemented as an adjacency list and having vertex name and vertex index properties. The "name" of a vertex here is actually a pointer to a module wrapper object.
using module_name_map_t = boost::property_map< Graph, boost::vertex_name_t >::type
module_name_map_t is the type for the map mapping Graph vertex descriptors to names.
using index_map_t = boost::property_map< Graph, boost::vertex_index_t >::type
index_map_t is the type for the map mapping Graph vertex descriptors to the vertex index.
using Vertex = boost::graph_traits< Graph >::vertex_descriptor
Vertex is the type of the vertex used by Graph.
using vertex_list = std::list< Vertex >
vertex_list is a std::list containing Vertex objects.
using vertex_iterator = boost::graph_traits< Graph >::vertex_iterator
vertex_iterator is the type of an iterator that may be used to iterate through any container of vertices from a graph of type Graph.
Functions
string_vector get_module_inputs (module_creator *w)
Returns a list (presented as a sorted vector of strings) of all inputs for the module.
string_vector get_module_outputs (module_creator *w)
Returns a list (presented as a sorted vector of strings) of all outputs for the module.
bool depends_on (module_creator *m1, module_creator *m2)
Determines if the module m1 depends on the module m2, returning true if it does and false if not.
Graph get_dependency_graph (mc_vector mcs)
Creates and returns a graph that models the dependency structure of the modules listed in mcs.
bool has_cycle (Graph g)
Given a directed graph g, return true if g has a cycle, false otherwise.
bool has_cyclic_dependency (mc_vector mcs)
Given a list of modules (presented as a vector of module wrapper pointers), determine if the list can be put in a suitable order for evaluating the modules.
bool order_ok (mc_vector mcs)
Determines whether the modules in mcs need to be reordered before evaluation.
vertex_list get_topological_ordering (const Graph &g)
Given a directed acyclic graph g, return a ordered list of the vertices (presented as a vertex_list object) such that for each edge of the graph, the source vertex of the edge occurs in the list before the target vertex of the edge.
mc_vector get_evaluation_order (mc_vector mcs)
Given a list of modules (presented as a vector of pointers to module_creator objects), return the same list in a suitable order for evaluating the modules.
Typedef Documentation
Graph
using Graph = boost::adjacency_list< boost::setS, boost::listS, boost::directedS, boost::property<boost::vertex_name_t, module_creator*, boost::property<boost::vertex_index_t, std::size_t> > >
Graph is the type of a directed Boost graph without multi-edges implemented as an adjacency list and having vertex name and vertex index properties. The "name" of a vertex here is actually a pointer to a module wrapper object.
For more information, see https://www.boost.org/doc/libs/1_71_0/libs/graph/doc/using_adjacency_list.html
Definition at line 31 of file module_dependency_utilities.cpp.
index_map_t
using index_map_t = boost::property_map<Graph, boost::vertex_index_t>::type
index_map_t is the type for the map mapping Graph vertex descriptors to the vertex index.
(We wouldn't need this if we used vecS instead of listS for the VertexList adjacency_list template paramater. But this allows us to use either.)
Definition at line 55 of file module_dependency_utilities.cpp.
module_name_map_t
using module_name_map_t = boost::property_map<Graph, boost::vertex_name_t>::type
module_name_map_t is the type for the map mapping Graph vertex descriptors to names.
In our case, these will be pointers to module wrapper objects.
Definition at line 45 of file module_dependency_utilities.cpp.
Vertex
using Vertex = boost::graph_traits<Graph>::vertex_descriptor
Vertex is the type of the vertex used by Graph.
Definition at line 60 of file module_dependency_utilities.cpp.
vertex_iterator
using vertex_iterator = boost::graph_traits<Graph>::vertex_iterator
vertex_iterator is the type of an iterator that may be used to iterate through any container of vertices from a graph of type Graph.
Definition at line 74 of file module_dependency_utilities.cpp.
vertex_list
using vertex_list = std::list<Vertex>
vertex_list is a std::list containing Vertex objects.
Used for storing the module evaluation order.
Definition at line 67 of file module_dependency_utilities.cpp.
Function Documentation
depends_on()
bool depends_on (module_creator * m1, module_creator * m2)
Determines if the module m1 depends on the module m2, returning true if it does and false if not.
m1 depends on m2 if and only if some input of m1 corresponds to some output of m2.
Parameters
[in] m1 A pointer to a module_creator object.
[in] m2 A pointer to a module_creator object.
Returns
true if the module named by m1 depends upon the module named by m2, false otherwise.
Definition at line 129 of file module_dependency_utilities.cpp.
References get_module_inputs(), and get_module_outputs().
Referenced by get_dependency_graph(), and order_ok().
get_dependency_graph()
Graph get_dependency_graph (mc_vector mcs)
Creates and returns a graph that models the dependency structure of the modules listed in mcs.
There is a directed edge from the vertex for module A to the vertex for module B if A is depended upon by B, that is, if B depends on A.
Parameters
mcs A list (presented as a vector of pointers to module_creator objects) of modules.
Returns
A Graph object modeling the dependency structure of the modules.
Definition at line 158 of file module_dependency_utilities.cpp.
References depends_on().
Referenced by get_evaluation_order(), and has_cyclic_dependency().
get_evaluation_order()
mc_vector get_evaluation_order (mc_vector mcs)
Given a list of modules (presented as a vector of pointers to module_creator objects), return the same list in a suitable order for evaluating the modules.
If no such ordering exists (due to a cyclic dependency), the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
mcs A list (presented as a vector of module wrapper pointers) of modules.
Returns
The same list given in mcs, but ordered so that each module in the list depends only on modules occuring earlier in the list.
Note
Even if the input list mcs is already in a suitable evaluation order, the output list may nevertheless give the modules in a different order.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> Thrown if there is no suitable evaluation order due to a cyclic dependency in the set of modules specified by mcs.
Definition at line 336 of file module_dependency_utilities.cpp.
References get_dependency_graph(), and get_topological_ordering().
Referenced by analyze_system_inputs(), and dynamical_system::dynamical_system().
get_module_inputs()
string_vector get_module_inputs (module_creator * w)
Returns a list (presented as a sorted vector of strings) of all inputs for the module.
Parameters
[in] w A pointer to a module_creator object.
Returns
A list (presented as a sorted vector of strings) of all inputs for the module.
Definition at line 93 of file module_dependency_utilities.cpp.
References module_creator::get_inputs().
Referenced by depends_on().
get_module_outputs()
string_vector get_module_outputs (module_creator * w)
Returns a list (presented as a sorted vector of strings) of all outputs for the module.
Parameters
[in] w A pointer to a module_creator object.
Returns
A list (presented as a sorted vector of strings) of all outputs for the module.
Definition at line 108 of file module_dependency_utilities.cpp.
References module_creator::get_outputs().
Referenced by depends_on().
get_topological_ordering()
vertex_list get_topological_ordering (const Graph & g)
Given a directed acyclic graph g, return a ordered list of the vertices (presented as a vertex_list object) such that for each edge of the graph, the source vertex of the edge occurs in the list before the target vertex of the edge.
If g is not actually a directed acyclic graph, the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
g A Graph object corresponding to a directed acyclic graph.
Returns
A list of the vertices of g (presented as a list of Vertex objects) ordered so the module associated with each vertex in the list depends only on modules associated with vertices occuring earlier in the list.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> if g is not acyclic.
Note
g is passed by (const) reference not merely for efficiency, but so that the returned vertex list will actually be a list of vertices of g, not a list of vertices of a copy of g. This matters when we try to get the names of the vertices in the list.
Definition at line 305 of file module_dependency_utilities.cpp.
Referenced by get_evaluation_order().
has_cycle()
bool has_cycle (Graph g)
Given a directed graph g, return true if g has a cycle, false otherwise.
Parameters
g A graph object of type Graph.
Returns
true if directed graph g has a cycle, false if it is acyclic.
Definition at line 228 of file module_dependency_utilities.cpp.
Referenced by has_cyclic_dependency().
has_cyclic_dependency()
bool has_cyclic_dependency (mc_vector mcs)
Given a list of modules (presented as a vector of module wrapper pointers), determine if the list can be put in a suitable order for evaluating the modules.
Parameters
mcs A list (presented as a vector of module wrapper pointers) of modules.
Returns
true if there is a cyclic dependency among the given modules so that they cannot be suitably ordered; false otherwise.
Definition at line 250 of file module_dependency_utilities.cpp.
References get_dependency_graph(), and has_cycle().
Referenced by analyze_system_inputs(), and validate_dynamical_system_inputs().
order_ok()
bool order_ok (mc_vector mcs)
Determines whether the modules in mcs need to be reordered before evaluation.
Parameters
module_names A list (presented as a vector of strings) of names of direct modules.
Returns
true if the list of modules as given in module_names is a suitable evaluation order, false otherwise.
Definition at line 266 of file module_dependency_utilities.cpp.
References depends_on().
Referenced by analyze_system_inputs().