The BioCro C++ Library: /github/workspace/source/src/utils/module_dependency_utilities.h File Reference
module_dependency_utilities.h File Reference
#include <boost/graph/topological_sort.hpp>
#include "../module_wrapper.h"
Functions
mwp_vector get_evaluation_order (mwp_vector mwps)
Given a list of modules (presented as a vector of pointers to module_wrapper_base objects), return the same list in a suitable order for evaluating the modules.
bool has_cyclic_dependency (mwp_vector mwps)
Given a list of modules (presented as a vector of module wrapper pointers), determine if the list can be put in a suitable order for evaluating the modules.
bool order_ok (mwp_vector mwps)
Determines whether the modules in mwps need to be reordered before evaluation.
Function Documentation
get_evaluation_order()
mwp_vector get_evaluation_order (mwp_vector mwps)
Given a list of modules (presented as a vector of pointers to module_wrapper_base objects), return the same list in a suitable order for evaluating the modules.
If no such ordering exists (due to a cyclic dependency), the function throws an exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>>.
Parameters
mwps A list (presented as a vector of module wrapper pointers) of modules.
Returns
The same list given in mwps, but ordered so that each module in the list depends only on modules occuring earlier in the list.
Note
Even if the input list mwps is already in a suitable evaluation order, the output list may nevertheless give the modules in a different order.
Exceptions
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::not_a_dag>> Thrown if there is no suitable evaluation order due to a cyclic dependency in the set of modules specified by mwps.
Definition at line 336 of file module_dependency_utilities.cpp.
References get_dependency_graph(), and get_topological_ordering().
Referenced by analyze_system_inputs(), and dynamical_system::dynamical_system().
has_cyclic_dependency()
bool has_cyclic_dependency (mwp_vector mwps)
Given a list of modules (presented as a vector of module wrapper pointers), determine if the list can be put in a suitable order for evaluating the modules.
Parameters
mwps A list (presented as a vector of module wrapper pointers) of modules.
Returns
true if there is a cyclic dependency among the given modules so that they cannot be suitably ordered; false otherwise.
Definition at line 250 of file module_dependency_utilities.cpp.
References get_dependency_graph(), and has_cycle().
Referenced by analyze_system_inputs(), and validate_dynamical_system_inputs().
order_ok()
bool order_ok (mwp_vector mwps)
Determines whether the modules in mwps need to be reordered before evaluation.
Parameters
module_names A list (presented as a vector of strings) of names of direct modules.
Returns
true if the list of modules as given in module_names is a suitable evaluation order, false otherwise.
Definition at line 266 of file module_dependency_utilities.cpp.
References depends_on().
Referenced by analyze_system_inputs().