The BioCro C++ Library: se_module Namespace Reference
se_module Namespace Reference
Classes
class base
A general module that solves a set of simultaneous equations.
Functions
std::string get_ncalls_output_name (std::string const &module_name)
Returns the name of an output quantity that describes the number of times the simultaneous equations were evaluated while solving for the unknowns.
std::string get_nsteps_output_name (std::string const &module_name)
Returns the name of an output quantity that describes the number of steps the solver took.
std::string get_success_output_name (std::string const &module_name)
Returns the name of an output quantity that indicates whether the solver was successful in finding a solution.
string_vector get_se_inputs (string_vector module_names)
Returns a sorted list of inputs required by the modules, excluding any unknown quantities.
string_vector get_se_outputs (string_vector module_names)
Returns a sorted list of outputs produced by the modules.
std::unique_ptr< simultaneous_equations > make_se (string_vector module_names)
Make a simultaneous_equations object from the modules.
std::vector< std::vector< double > > reorder_initial_guesses (std::vector< std::vector< double >> initial_guesses, std::unique_ptr< simultaneous_equations > const &se)
Reorders the initial guesses according to their corresponding f_scalar_norm values.
Function Documentation
get_ncalls_output_name()
std::string se_module::get_ncalls_output_name (std::string const & module_name)
Returns the name of an output quantity that describes the number of times the simultaneous equations were evaluated while solving for the unknowns.
Definition at line 21 of file se_module.h.
References ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by ed_c4_leaf_photosynthesis::get_outputs(), ed_c4_leaf_photosynthesis2::get_outputs(), ed_c4_leaf_photosynthesis3::get_outputs(), ed_c4_leaf_photosynthesis4::get_outputs(), ed_nikolov_conductance_free_solve::get_outputs(), and ed_p_m_temperature_solve::get_outputs().
get_nsteps_output_name()
std::string se_module::get_nsteps_output_name (std::string const & module_name)
Returns the name of an output quantity that describes the number of steps the solver took.
Definition at line 30 of file se_module.h.
References ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by ed_c4_leaf_photosynthesis::get_outputs(), ed_c4_leaf_photosynthesis2::get_outputs(), ed_c4_leaf_photosynthesis3::get_outputs(), ed_c4_leaf_photosynthesis4::get_outputs(), ed_nikolov_conductance_free_solve::get_outputs(), and ed_p_m_temperature_solve::get_outputs().
get_se_inputs()
string_vector se_module::get_se_inputs (string_vector module_names)
Returns a sorted list of inputs required by the modules, excluding any unknown quantities.
Definition at line 47 of file se_module.h.
References find_strictly_required_inputs(), get_unknown_quantities(), string_set_to_string_vector(), and string_vector_difference().
Referenced by ed_c4_leaf_photosynthesis::get_inputs(), ed_c4_leaf_photosynthesis2::get_inputs(), ed_c4_leaf_photosynthesis3::get_inputs(), ed_c4_leaf_photosynthesis4::get_inputs(), ed_nikolov_conductance_free_solve::get_inputs(), ed_p_m_temperature_solve::get_inputs(), and make_se().
get_se_outputs()
string_vector se_module::get_se_outputs (string_vector module_names)
Returns a sorted list of outputs produced by the modules.
Definition at line 65 of file se_module.h.
References find_unique_module_outputs(), and string_set_to_string_vector().
Referenced by ed_c4_leaf_photosynthesis::get_outputs(), ed_c4_leaf_photosynthesis2::get_outputs(), ed_c4_leaf_photosynthesis3::get_outputs(), ed_c4_leaf_photosynthesis4::get_outputs(), ed_nikolov_conductance_free_solve::get_outputs(), and ed_p_m_temperature_solve::get_outputs().
get_success_output_name()
std::string se_module::get_success_output_name (std::string const & module_name)
Returns the name of an output quantity that indicates whether the solver was successful in finding a solution.
Definition at line 39 of file se_module.h.
References ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by ed_c4_leaf_photosynthesis::get_outputs(), ed_c4_leaf_photosynthesis2::get_outputs(), ed_c4_leaf_photosynthesis3::get_outputs(), ed_c4_leaf_photosynthesis4::get_outputs(), ed_nikolov_conductance_free_solve::get_outputs(), and ed_p_m_temperature_solve::get_outputs().
make_se()
std::unique_ptr<simultaneous_equations> se_module::make_se (string_vector module_names)
Make a simultaneous_equations object from the modules.
Definition at line 73 of file se_module.h.
References get_se_inputs(), and get_unknown_quantities().
reorder_initial_guesses()
std::vector<std::vector<double> > se_module::reorder_initial_guesses (std::vector< std::vector< double >> initial_guesses, std::unique_ptr< simultaneous_equations > const & se)
Reorders the initial guesses according to their corresponding f_scalar_norm values.
Definition at line 93 of file se_module.h.
References f_scalar_norm_from_f_vec(), and se_module_print.
Referenced by base::do_operation().