The BioCro C++ Library: se_solver_rand Namespace Reference
se_solver_rand Namespace Reference
Functions
std::mt19937 eng (rd())
std::uniform_real_distribution< double > uniform_real_dist (0, std::nextafter(1, std::numeric_limits< double >::max()))
std::normal_distribution< double > normal_real_dist (0.0, 1.0)
double rand_01 ()
A function that returns a double between 0 and 1 chosen from a uniform distribution.
double normal_rand ()
A function that returns a double chosen from a normal distribution with a mean of 0 and a standard deviation of 1.
std::vector< double > random_vector_on_n_dimensional_sphere (size_t n)
A function that returns a random vector on the surface of an n-dimensional sphere.
Variables
std::random_device rd
Function Documentation
eng()
std::mt19937 se_solver_rand::eng (rd())
Referenced by normal_rand(), and rand_01().
normal_rand()
double normal_rand ()
A function that returns a double chosen from a normal distribution with a mean of 0 and a standard deviation of 1.
Definition at line 35 of file se_solver_helper_functions.cpp.
References eng(), and normal_real_dist().
Referenced by random_vector_on_n_dimensional_sphere().
normal_real_dist()
std::normal_distribution<double> se_solver_rand::normal_real_dist (0. 0, 1. 0)
Referenced by normal_rand().
rand_01()
double rand_01 ()
A function that returns a double between 0 and 1 chosen from a uniform distribution.
Definition at line 25 of file se_solver_helper_functions.cpp.
References eng(), and uniform_real_dist().
Referenced by adjust_bad_guess_random().
random_vector_on_n_dimensional_sphere()
std::vector< double > random_vector_on_n_dimensional_sphere (size_t n)
A function that returns a random vector on the surface of an n-dimensional sphere.
Here each component is chosen from a normal distribution, and then the vector is normalized to the unit sphere. See section 4 of "Three Different Algorithms for Generating Uniformly Distributed Random Points on the N-Sphere" by Jan Poland (Oct 24, 2000). May be available at https://www-alg.ist.hokudai.ac.jp/~jan/randsphere.pdf.
Definition at line 47 of file se_solver_helper_functions.cpp.
References calculation_constants::eps_zero, and normal_rand().
Referenced by generate_guess_list().
uniform_real_dist()
std::uniform_real_distribution<double> se_solver_rand::uniform_real_dist (0 , std::nextafter(1, std::numeric_limits< double >::max()))
Referenced by rand_01().
Variable Documentation
rd
std::random_device rd
Definition at line 11 of file se_solver_helper_functions.cpp.