The BioCro C++ Library: /github/workspace/source/src/se_solver_helper_functions.h File Reference
se_solver_helper_functions.h File Reference
#include <vector>
#include <cmath>
#include <numeric>
#include "constants.h"
#include <Rinternals.h>
Namespaces
se_solver_rand
Functions
double rand_01 ()
A function that returns a double between 0 and 1 chosen from a uniform distribution.
double normal_rand ()
A function that returns a double chosen from a normal distribution with a mean of 0 and a standard deviation of 1.
std::vector< double > random_vector_on_n_dimensional_sphere (size_t n)
A function that returns a random vector on the surface of an n-dimensional sphere. Here each component is chosen from a normal distribution, and then the vector is normalized to the unit sphere. See section 4 of "Three Different Algorithms for Generating Uniformly Distributed Random Points on the N-Sphere" by Jan Poland (Oct 24, 2000). May be available at https://www-alg.ist.hokudai.ac.jp/~jan/randsphere.pdf.
template<typename equation_ptr_type , typename vector_type >
bool adjust_bad_guess_random (equation_ptr_type const &se, vector_type const &lower_bounds, vector_type const &upper_bounds, vector_type &bad_guess, vector_type &difference_vector_at_bad_guess)
Determines a new guess from a bad one by randomly replacing bad elements.
template<typename equation_ptr_type , typename vector_type >
bool adjust_bad_guess_limits (equation_ptr_type const &se, vector_type const &lower_bounds, vector_type const &upper_bounds, vector_type &bad_guess, vector_type &difference_vector_at_bad_guess)
Determines a new guess from a bad one by replacing bad elements with the nearest bound.
template<typename vector_type >
std::vector< bool > is_outside_bounds (vector_type const &vec_to_test, vector_type const &lower_bounds, vector_type const &upper_bounds)
Checks whether the elements of vec_to_test lie outside the bounds.
template<typename vector_type >
std::vector< bool > has_not_converged_abs (vector_type const &difference_vector, vector_type const &tolerances)
Checks whether the difference vector elements are close to zero using an absolute threshold.
template<typename vector_type >
std::vector< bool > has_not_converged_rel (vector_type const &difference_vector, vector_type const &guess, vector_type const &tolerances)
Checks whether the difference vector elements are close to zero using a relative threshold.
template<typename vector_type >
double f_scalar_from_f_vec (vector_type F_vec)
Calculates f_scalar = 0.5 * |F_vec|^2 from a vector F_vec.
template<typename vector_type >
double f_scalar_norm_from_f_vec (vector_type F_vec, vector_type F_vec_norm)
Calculates f_scalar_norm = |F_vec/F_norm|^2 from a vector F_vec and a normalization vector F_norm.
std::vector< std::vector< double > > generate_guess_list (std::vector< double > const &central_guess, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > const &scale_factors, int num_guesses)
Determines a set of multiple initial guesses distributed around a central guess. The resulting output will include the central guess and an additional num_guesses new guesses.
Variables
const bool seshf_print = false
Function Documentation
adjust_bad_guess_limits()
bool adjust_bad_guess_limits (equation_ptr_type const & se, vector_type const & lower_bounds, vector_type const & upper_bounds, vector_type & bad_guess, vector_type & difference_vector_at_bad_guess)
Determines a new guess from a bad one by replacing bad elements with the nearest bound.
Parameters
[in] bad_guess a vector that produces a bad output when used as an input to get_next_guess, i.e., the next guess based on this one lies outside the acceptable bounds
[in] lower_bounds a vector indicating the lower bound for each unknown quantity
[in] upper_bounds a vector indicating the upper bound for each unknown quantity
Returns
a new guess
The new guess is determined by modifying all elements of bad_guess that lie outside the bounds.
Any value below its lower bound will be replaced by the lower bound, and any value above its upper bound will be replaced by the upper bound.
As far as I know, there is no guarantee that this method will help find a good solution. [EBL]
Definition at line 87 of file se_solver_helper_functions.h.
References ed_c4_leaf_photosynthesis_stuff::lower_bounds, and ed_c4_leaf_photosynthesis_stuff::upper_bounds.
Referenced by fixed_point::get_next_guess(), and newton_raphson_boost::get_next_guess().
adjust_bad_guess_random()
bool adjust_bad_guess_random (equation_ptr_type const & se, vector_type const & lower_bounds, vector_type const & upper_bounds, vector_type & bad_guess, vector_type & difference_vector_at_bad_guess)
Determines a new guess from a bad one by randomly replacing bad elements.
Parameters
[in] bad_guess a vector that produces a bad output when used as an input to get_next_guess, i.e., the next guess based on this one lies outside the acceptable bounds
[in] lower_bounds a vector indicating the lower bound for each unknown quantity
[in] upper_bounds a vector indicating the upper bound for each unknown quantity
Returns
a new guess
The new guess is determined by modifying all elements of bad_guess that lie outside the bounds.
For each such "bad element," a new value is chosen randomly from the range of acceptable values.
As far as I know, there is no guarantee that this method will help find a good solution. [EBL]
Definition at line 39 of file se_solver_helper_functions.h.
References is_outside_bounds(), ed_c4_leaf_photosynthesis_stuff::lower_bounds, se_solver_rand::rand_01(), and ed_c4_leaf_photosynthesis_stuff::upper_bounds.
f_scalar_from_f_vec()
double f_scalar_from_f_vec (vector_type F_vec)
Calculates f_scalar = 0.5 * |F_vec|^2 from a vector F_vec.
Definition at line 226 of file se_solver_helper_functions.h.
Referenced by newton_raphson_line_search_boost().
f_scalar_norm_from_f_vec()
double f_scalar_norm_from_f_vec (vector_type F_vec, vector_type F_vec_norm)
Calculates f_scalar_norm = |F_vec/F_norm|^2 from a vector F_vec and a normalization vector F_norm.
Definition at line 236 of file se_solver_helper_functions.h.
References calculation_constants::eps_zero.
Referenced by se_module::reorder_initial_guesses().
generate_guess_list()
std::vector<std::vector<double> > generate_guess_list (std::vector< double > const & central_guess, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > const & scale_factors, int num_guesses)
Determines a set of multiple initial guesses distributed around a central guess. The resulting output will include the central guess and an additional num_guesses new guesses.
For an N-dimensional central guess, each new guess will be determined by first generating a random vector on the N-dimensional unit sphere: X. Then new_guess[i] = central_guess[i] + X[i] * radius[i], where radius[i] is set by the minimum of scale_factors[i], 0.95 * |central_guess[i] - upper_bounds[i]|, and 0.95 * |central_guess[i] - lower_bounds[i]|. This should ensure that each guess lies within the range of acceptable values.
Definition at line 87 of file se_solver_helper_functions.cpp.
References ed_c4_leaf_photosynthesis_stuff::lower_bounds, se_solver_rand::random_vector_on_n_dimensional_sphere(), and ed_c4_leaf_photosynthesis_stuff::upper_bounds.
Referenced by ed_c4_leaf_photosynthesis::get_initial_guesses().
has_not_converged_abs()
std::vector<bool> has_not_converged_abs (vector_type const & difference_vector, vector_type const & tolerances)
Checks whether the difference vector elements are close to zero using an absolute threshold.
Parameters
[in] difference_vector
[in] tolerances
Returns
a vector of bools where true indicates that the corresponding element of the input vectors has not met the convergence criteria.
Definition at line 153 of file se_solver_helper_functions.h.
References seshf_print.
Referenced by se_solver::solve().
has_not_converged_rel()
std::vector<bool> has_not_converged_rel (vector_type const & difference_vector, vector_type const & guess, vector_type const & tolerances)
Checks whether the difference vector elements are close to zero using a relative threshold.
Parameters
[in] difference_vector
[in] guess
[in] tolerances
Returns
a vector of bools where true indicates that the corresponding element of the input vectors has not met the convergence criteria.
Definition at line 190 of file se_solver_helper_functions.h.
References calculation_constants::eps_zero, and seshf_print.
Referenced by se_solver::solve().
is_outside_bounds()
std::vector<bool> is_outside_bounds (vector_type const & vec_to_test, vector_type const & lower_bounds, vector_type const & upper_bounds)
Checks whether the elements of vec_to_test lie outside the bounds.
Parameters
[in] vec_to_test
[in] lower_bounds
[in] upper_bounds
Returns
a vector of bools where true indicates that the corresponding element of vec_to_test lies outside the range set by the corresponding elements of lower_bounds and upper_bounds.
Definition at line 128 of file se_solver_helper_functions.h.
References ed_c4_leaf_photosynthesis_stuff::lower_bounds, and ed_c4_leaf_photosynthesis_stuff::upper_bounds.
Referenced by adjust_bad_guess_random().
Variable Documentation
seshf_print
const bool seshf_print = false
Definition at line 9 of file se_solver_helper_functions.h.
Referenced by has_not_converged_abs(), and has_not_converged_rel().