The BioCro C++ Library: /github/workspace/source/src/framework_ed/simultaneous_equations.h File Reference
simultaneous_equations.h File Reference
#include "../framework/state_map.h"
#include "../framework/module.h"
#include "../framework/validate_dynamical_system.h"
Classes
class simultaneous_equations
Defines a set of simultaneous equations.
Functions
bool validate_simultaneous_equations_inputs (std::string &message, state_map const &known_quantities, string_vector const &unknown_quantities, mc_vector const &direct_mcs)
Checks over a group of quantities and modules to ensure they can be used to create a valid set of simultaneous equations.
std::string analyze_simultaneous_equations_inputs (mc_vector const &direct_mcs)
Provides information about a set of simultaneous_equations inputs that is not strictly required to check validity.
string_vector get_unknown_quantities (mc_vector mcs)
Finds the unknown quantities defined by the set of modules.
template<typename in_vector_type , typename time_type , typename out_vector_type >
void evaluate_equations (std::unique_ptr< simultaneous_equations > const &se, in_vector_type const &x, time_type, out_vector_type &y)
Define evaluation behavior for a set of equations defined by a simultaneous_equations object. This is required to use calculate_jacobian() with a simultaneous_equations object.
Function Documentation
analyze_simultaneous_equations_inputs()
std::string analyze_simultaneous_equations_inputs (mc_vector const & direct_mcs)
Provides information about a set of simultaneous_equations inputs that is not strictly required to check validity.
The following information is reported:
A list of all quantities required by the modules as inputs
A list of all quantities produced by the modules as outputs
A list of all unknown quantities specified by the modules
Definition at line 115 of file simultaneous_equations.cpp.
References create_message(), find_strictly_required_inputs(), find_unique_module_outputs(), and get_unknown_quantities().
Referenced by R_validate_simultaneous_equations().
evaluate_equations()
void evaluate_equations (std::unique_ptr< simultaneous_equations > const & se, in_vector_type const & x, time_type , out_vector_type & y)
Define evaluation behavior for a set of equations defined by a simultaneous_equations object. This is required to use calculate_jacobian() with a simultaneous_equations object.
Parameters
[in] sys a shared pointer to a simultaneous_equations object
[in] x a vector to be passed to the simultaneous_equations as an input. Since we are evaluating simultaneous equations, x contains values of the unknown variables.
[in] t an unused parameter included here to produce the same function signature as when evaluating a dynamical_system.
[out] y the vector output. Since we are evaluating simultaneous equations, y contains the change in the value of each unknown variable produced by running the modules.
Definition at line 168 of file simultaneous_equations.h.
get_unknown_quantities()
string_vector get_unknown_quantities (mc_vector mcs)
Finds the unknown quantities defined by the set of modules.
Returns
A sorted list of quantity names
Definition at line 236 of file simultaneous_equations.cpp.
References find_strictly_required_inputs(), find_unique_module_outputs(), and string_set_to_string_vector().
Referenced by analyze_simultaneous_equations_inputs(), se_module::get_se_inputs(), se_module::make_se(), and validate_simultaneous_equations_inputs().
validate_simultaneous_equations_inputs()
bool validate_simultaneous_equations_inputs (std::string & message, state_map const & known_quantities, string_vector const & unknown_quantities, mc_vector const & direct_mcs)
Checks over a group of quantities and modules to ensure they can be used to create a valid set of simultaneous equations.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
When discussing a simultaneous_equations object, it is helpful to define several terms as follows:
We consider a quantity to have been "specified" (or "defined") if it is a key in known_quantities or if it is an output variable of one of the direct modules listed in direct_mcs.
We consider a quantity to be strictly required as a module input if (i) a module requires it as an input and (ii) it has not been produced as the output of a previous module. Thus the set of strictly required inputs depends on the order of the modules.
If a quantity is (i) strictly required as an input and (ii) is produced as the output of a module, it is said to be an "unknown quantity" since its value will be determined by the set of simultaneous equations that this class represents. Thus the set of unknown quantities also depends on the order of the modules.
While constructing a simultaneous_equations object, the following criteria determine the validity of the inputs:
1. Each quantity is specified only once.
2. All module inputs are specified.
3. Each quantity name in unknown_quantities is an unknown quantity.
4. Each unknown quantity is included in unknown_quantities.
Definition at line 37 of file simultaneous_equations.cpp.
References create_message(), find_duplicate_quantity_definitions(), find_undefined_module_inputs(), get_defined_quantity_names(), get_unknown_quantities(), and string_vector_difference().
Referenced by R_validate_simultaneous_equations(), and simultaneous_equations::simultaneous_equations().