The BioCro C++ Library: /github/workspace/source/src/framework/validate_dynamical_system.cpp File Reference
validate_dynamical_system.cpp File Reference
#include <algorithm>
#include <memory>
#include "state_map.h"
#include "module.h"
#include "utils/module_dependency_utilities.h"
#include "validate_dynamical_system.h"
Functions
bool validate_dynamical_system_inputs (std::string &message, state_map initial_values, state_map params, state_vector_map drivers, mc_vector const &direct_mcs, mc_vector const &differential_mcs)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
std::string analyze_system_inputs (state_map initial_values, state_map params, state_vector_map drivers, mc_vector const &direct_mcs, mc_vector const &differential_mcs)
Provides information about a set of system inputs that is not strictly required to check validity.
state_map define_quantity_map (std::vector< state_map > state_maps, mc_vector mcs)
Assembles a "master" state_map from a group of state_maps and a list of modules.
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
Finds quantities that are defined multiple times in a vector of strings.
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< mc_vector > mc_vectors)
Finds quantities that are required by modules but are not defined by quantity_names. The output includes the module associated with each undefined input.
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< mc_vector > mc_vectors)
Finds quantities that are output by modules but are not defined by quantity_names. The output includes the module associated with each undefined output.
string_set find_unique_module_inputs (std::vector< mc_vector > mc_vectors)
Returns a set containing all unique inputs to the modules.
string_set find_unique_module_outputs (mc_vector mcs)
Returns a set containing all unique outputs produced by the modules.
string_set find_strictly_required_inputs (mc_vector mcs)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< mc_vector > mc_vectors)
Returns parameters in the state maps that are not used as inputs to the modules.
string_vector find_static_output_parameters (state_map quantities, mc_vector mcs)
Returns quantities in the state map that are not provided as outputs from the modules.
string_vector find_euler_requirements (mc_vector mcs)
Returns modules that require a fixed step size Euler ode_solver.
string_vector find_mischaracterized_modules (mc_vector mcs, bool is_differential)
Returns mischaracterized modules, i.e., direct modules in the differential module list or vice-versa.
module_vector get_module_vector (mc_vector mcs, state_map const &input_quantities, state_map *output_quantities)
Returns a vector of unique_ptrs to module objects.
string_vector get_module_names (mc_vector mcs)
Generates a vector of module names from a vector of module wrapper pointers.
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
Adds an indented line to a message.
void insert_quantity_name_if_new (std::string quantity_name, string_vector &target_vector, string_vector &duplicates)
Inserts quantity_name into target_vector if it is not already there. In the case of a duplicate, quantity_name is inserted into duplicates.
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector &undefined_module_names)
If param_name is not included in defined_quantity_names, a new entry is inserted into undefined_module_names that includes param_name and its associated module_name.
string_vector string_set_to_string_vector (string_set ss)
Converts a string_set to a string_vector.
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
Function Documentation
add_indented_line()
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
Adds an indented line to a message.
Parameters
[in] message The message being added to.
[in] text_to_add The text being appended to message.
[in] num_spaces The number of spaces of indentation for the appended text.
Returns
A string consisting of the input message followed num_spaces space characters followed by text_to_add.
Definition at line 611 of file validate_dynamical_system.cpp.
Referenced by create_message().
analyze_system_inputs()
std::string analyze_system_inputs (state_map initial_values, state_map params, state_vector_map drivers, mc_vector const & direct_mcs, mc_vector const & differential_mcs)
Provides information about a set of system inputs that is not strictly required to check validity.
The following information is reported:
A list of all quantities required by the modules as inputs
A list of unused quantities in the invariant parameter list
A list of unused quantities in the drivers list
A list of quantities in the initial values that lack derivatives
A list of quantities whose derivatives have terms calculated by multiple modules
Definition at line 136 of file validate_dynamical_system.cpp.
References at(), create_message(), find_duplicate_quantity_definitions(), find_euler_requirements(), find_mischaracterized_modules(), find_static_output_parameters(), find_unique_module_inputs(), find_unused_input_parameters(), get_defined_quantity_names(), get_evaluation_order(), get_module_names(), has_cyclic_dependency(), and order_ok().
Referenced by R_validate_dynamical_system_inputs().
define_quantity_map()
state_map define_quantity_map (std::vector< state_map > state_maps, mc_vector mcs)
Assembles a "master" state_map from a group of state_maps and a list of modules.
The resulting state_map will essentially be the union of all the maps in parameter state_maps and an additional map formed by taking as keys all of the output variables from the modules in mcs and setting the corresponding values to zero.
The set of keys in the maps in state_maps should not overlap with one another and should be distinct from the module output variable names.
Parameters
state_maps A list (presented as a std::vector) of state_maps.
mcs A list of modules (presented as a std::vector of pointers to module_creator objects).
Returns
a state_map which is the union of all maps in state_maps together with a map whose keys are all the output parameters of modules in mcs and whose values are all zero.
Definition at line 289 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system(), and simultaneous_equations::simultaneous_equations().
find_duplicate_quantity_definitions()
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
Finds quantities that are defined multiple times in a vector of strings.
Parameters
quantity_names A list (presented as a vector of strings) of names of quantities. Generally these will be names of state variables, environment variables ("varying parameters"), system constants ("invariant parameters"), or derived quantites (outputs of direct modules).
Returns
A alphabetized list (presented as a vector of strings) of all quantities appearing more than once in the input list.
Definition at line 325 of file validate_dynamical_system.cpp.
References insert_quantity_name_if_new().
Referenced by analyze_system_inputs(), validate_dynamical_system_inputs(), and validate_simultaneous_equations_inputs().
find_euler_requirements()
string_vector find_euler_requirements (mc_vector mcs)
Returns modules that require a fixed step size Euler ode_solver.
Definition at line 507 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_mischaracterized_modules()
string_vector find_mischaracterized_modules (mc_vector mcs, bool is_differential)
Returns mischaracterized modules, i.e., direct modules in the differential module list or vice-versa.
Definition at line 540 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_static_output_parameters()
string_vector find_static_output_parameters (state_map quantities, mc_vector mcs)
Returns quantities in the state map that are not provided as outputs from the modules.
Definition at line 486 of file validate_dynamical_system.cpp.
References find_unique_module_outputs(), insert_quantity_if_undefined(), and keys().
Referenced by analyze_system_inputs().
find_strictly_required_inputs()
string_set find_strictly_required_inputs (mc_vector mcs)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
Definition at line 432 of file validate_dynamical_system.cpp.
References insert_quantity_if_undefined(), and string_vector_to_string_set().
Referenced by analyze_simultaneous_equations_inputs(), se_module::get_se_inputs(), and get_unknown_quantities().
find_undefined_module_inputs()
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< mc_vector > mc_vectors)
Finds quantities that are required by modules but are not defined by quantity_names. The output includes the module associated with each undefined input.
Definition at line 344 of file validate_dynamical_system.cpp.
References insert_module_param_if_undefined(), and ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by validate_dynamical_system_inputs(), and validate_simultaneous_equations_inputs().
find_undefined_module_outputs()
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< mc_vector > mc_vectors)
Finds quantities that are output by modules but are not defined by quantity_names. The output includes the module associated with each undefined output.
Definition at line 372 of file validate_dynamical_system.cpp.
References insert_module_param_if_undefined(), and ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by validate_dynamical_system_inputs().
find_unique_module_inputs()
string_set find_unique_module_inputs (std::vector< mc_vector > mc_vectors)
Returns a set containing all unique inputs to the modules.
Definition at line 398 of file validate_dynamical_system.cpp.
Referenced by analyze_system_inputs(), find_euler_requirements(), find_mischaracterized_modules(), and find_unused_input_parameters().
find_unique_module_outputs()
string_set find_unique_module_outputs (mc_vector mcs)
Returns a set containing all unique outputs produced by the modules.
Definition at line 416 of file validate_dynamical_system.cpp.
Referenced by analyze_simultaneous_equations_inputs(), dynamical_system::dynamical_system(), find_euler_requirements(), find_mischaracterized_modules(), find_static_output_parameters(), se_module::get_se_outputs(), get_unknown_quantities(), and simultaneous_equations::simultaneous_equations().
find_unused_input_parameters()
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< mc_vector > mc_vectors)
Returns parameters in the state maps that are not used as inputs to the modules.
Definition at line 452 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), insert_quantity_if_undefined(), keys(), and parameters.
Referenced by analyze_system_inputs().
get_module_names()
string_vector get_module_names (mc_vector mcs)
Generates a vector of module names from a vector of module wrapper pointers.
Definition at line 588 of file validate_dynamical_system.cpp.
Referenced by analyze_system_inputs().
get_module_vector()
module_vector get_module_vector (mc_vector mcs, state_map const & input_quantities, state_map * output_quantities)
Returns a vector of unique_ptrs to module objects.
Definition at line 572 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system(), find_euler_requirements(), find_mischaracterized_modules(), and simultaneous_equations::simultaneous_equations().
insert_module_param_if_undefined()
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector & undefined_module_names)
If param_name is not included in defined_quantity_names, a new entry is inserted into undefined_module_names that includes param_name and its associated module_name.
Definition at line 652 of file validate_dynamical_system.cpp.
References ed_c4_leaf_photosynthesis_stuff::module_name.
Referenced by find_undefined_module_inputs(), and find_undefined_module_outputs().
insert_quantity_name_if_new()
void insert_quantity_name_if_new (std::string quantity_name, string_vector & target_vector, string_vector & duplicates)
Inserts quantity_name into target_vector if it is not already there. In the case of a duplicate, quantity_name is inserted into duplicates.
Parameters
[in] quantity_name A string (the name of a quantity).
[in/out] target_vector A vector of strings. If quantity_name wasn't in the list to begin with, it will be appended.
[in/out] duplicates A vector of strings. If quantity_name was already in target_vector, it will be appended to duplicates.
Definition at line 635 of file validate_dynamical_system.cpp.
Referenced by find_duplicate_quantity_definitions().
string_set_to_string_vector()
string_vector string_set_to_string_vector (string_set ss)
Converts a string_set to a string_vector.
Definition at line 666 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system(), se_module::get_se_inputs(), se_module::get_se_outputs(), get_unknown_quantities(), and simultaneous_equations::simultaneous_equations().
string_vector_difference()
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
Definition at line 688 of file validate_dynamical_system.cpp.
References insert_quantity_if_undefined().
Referenced by se_module::get_se_inputs(), and validate_simultaneous_equations_inputs().
string_vector_to_string_set()
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
Definition at line 679 of file validate_dynamical_system.cpp.
Referenced by find_strictly_required_inputs().
validate_dynamical_system_inputs()
bool validate_dynamical_system_inputs (std::string & message, state_map initial_values, state_map params, state_vector_map drivers, mc_vector const & direct_mcs, mc_vector const & differential_mcs)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
The following criteria are used to determine validity:
Each quantity is specified only once.
All module inputs are specified.
Derivatives are calculated only for quantities in the initial values.
Direct modules can be ordered in such a way that inputs are calculated before they are accessed.
We consider a quantity to have been "specified" (or "defined") if it is a key in one of the maps initial_values, params, or drivers, or, if it is an output variable of one of the direct modules listed in direct_module_names.
Criterion 2 and criterion 4 are related: Criterion 2 requires merely that each input to a direct or differential module is either a variable in the initial values, is one of the parameters, or is an output of some direct module. Criterion 4 goes further for the case of a direct module where an input quantity is provided by the output of some other direct module: It requires that the direct modules can be ordered in such a way that each of a module's input quantities that is neither a parameter or a quantity in the initial values be provided by the output of a module earlier in the list.
Notably absent from these criteria is a requirement that a derivative be calculated for every value given in the initial values. Values in the initial values that are not outputs of any differential module are assumed to have a derivative of zero, that is, they are assumed to be constant.
Definition at line 43 of file validate_dynamical_system.cpp.
References at(), create_marked_message(), find_duplicate_quantity_definitions(), find_undefined_module_inputs(), find_undefined_module_outputs(), get_defined_quantity_names(), has_cyclic_dependency(), and keys().
Referenced by dynamical_system::dynamical_system(), and R_validate_dynamical_system_inputs().