The BioCro C++ Library: /github/workspace/source/src/R_dynamical_system.cpp File Reference
R_dynamical_system.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "R_helper_functions.h"
#include "state_map.h"
#include "validate_dynamical_system.h"
#include "dynamical_system.h"
#include "module_wrapper.h"
Functions
SEXP R_validate_dynamical_system_inputs (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mwp_vec, SEXP differential_mwp_vec, SEXP verbose)
Function Documentation
R_validate_dynamical_system_inputs()
SEXP R_validate_dynamical_system_inputs (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mwp_vec, SEXP differential_mwp_vec, SEXP verbose)
Definition at line 12 of file R_dynamical_system.cpp.
References analyze_system_inputs(), map_from_list(), map_vector_from_list(), mw_vector_from_list(), parameters, r_logical_from_boolean(), and validate_dynamical_system_inputs().