The BioCro C++ Library: /github/workspace/source/src/R_helper_functions.cpp File Reference
R_helper_functions.cpp File Reference
#include <memory>
#include <stdexcept>
#include <Rinternals.h>
#include "modules.h"
#include "R_helper_functions.h"
Functions
state_map map_from_list (SEXP const &list)
state_vector_map map_vector_from_list (SEXP const &list)
vector< string > make_vector (SEXP const &r_string_vector)
SEXP r_string_vector_from_vector (vector< string > const &v)
SEXP list_from_map (state_map const &m)
SEXP list_from_map (state_vector_map const &m)
SEXP list_from_map (std::unordered_map< string, vector< string >> const &m)
SEXP list_from_module_info (std::string const &module_name, state_map const &module_inputs, state_map const &module_outputs, bool const &is_differential, bool const &requires_euler_ode_solver, std::string const &creation_error_message)
SEXP vector_from_map (state_map const &m)
SEXP r_logical_from_boolean (bool b)
void output_map (state_map const &m)
void output_list (SEXP const &list)
Function Documentation
list_from_map() [1/3]
SEXP list_from_map (state_map const & m)
Definition at line 101 of file R_helper_functions.cpp.
Referenced by list_from_module_info(), R_evaluate_module(), R_get_all_quantities(), R_run_biocro(), R_solve_simultaneous_equations(), R_system_derivatives(), and R_test_simultaneous_equations().
list_from_map() [2/3]
SEXP list_from_map (state_vector_map const & m)
Definition at line 116 of file R_helper_functions.cpp.
list_from_map() [3/3]
SEXP list_from_map (std::unordered_map< string, vector< string >> const & m)
Definition at line 140 of file R_helper_functions.cpp.
list_from_module_info()
SEXP list_from_module_info (std::string const & module_name, state_map const & module_inputs, state_map const & module_outputs, bool const & is_differential, bool const & requires_euler_ode_solver, std::string const & creation_error_message)
Definition at line 163 of file R_helper_functions.cpp.
References list_from_map(), and output_list().
Referenced by R_module_info().
make_vector()
vector<string> make_vector (SEXP const & r_string_vector)
Definition at line 79 of file R_helper_functions.cpp.
Referenced by R_evaluate_module(), R_module_info(), R_run_biocro(), R_solve_simultaneous_equations(), R_system_derivatives(), R_test_simultaneous_equations(), R_validate_dynamical_system_inputs(), and R_validate_simultaneous_equations().
map_from_list()
state_map map_from_list (SEXP const & list)
Definition at line 48 of file R_helper_functions.cpp.
Referenced by R_evaluate_module(), R_run_biocro(), R_solve_simultaneous_equations(), R_system_derivatives(), R_test_simultaneous_equations(), R_validate_dynamical_system_inputs(), and R_validate_simultaneous_equations().
map_vector_from_list()
state_vector_map map_vector_from_list (SEXP const & list)
Definition at line 60 of file R_helper_functions.cpp.
Referenced by R_run_biocro(), R_system_derivatives(), and R_validate_dynamical_system_inputs().
output_list()
void output_list (SEXP const & list)
Definition at line 265 of file R_helper_functions.cpp.
Referenced by list_from_module_info().
output_map()
void output_map (state_map const & m)
Definition at line 249 of file R_helper_functions.cpp.
r_logical_from_boolean()
SEXP r_logical_from_boolean (bool b)
Definition at line 241 of file R_helper_functions.cpp.
Referenced by R_validate_dynamical_system_inputs(), and R_validate_simultaneous_equations().
r_string_vector_from_vector()
SEXP r_string_vector_from_vector (vector< string > const & v)
Definition at line 90 of file R_helper_functions.cpp.
Referenced by R_get_all_modules(), R_get_all_ode_solvers(), and R_get_all_se_solvers().
vector_from_map()
SEXP vector_from_map (state_map const & m)
Definition at line 225 of file R_helper_functions.cpp.