The BioCro C++ Library: /github/workspace/source/src/R_simultaneous_equations.cpp File Reference
R_simultaneous_equations.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include <boost/numeric/ublas/matrix.hpp>
#include "framework/R_helper_functions.h"
#include "framework/state_map.h"
#include "framework/numerical_jacobian.h"
#include "framework_ed/simultaneous_equations.h"
#include "framework_ed/se_solver.h"
#include "framework_ed/se_solver_library/se_solver_factory.h"
Functions
SEXP R_solve_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP lower_bounds, SEXP upper_bounds, SEXP abs_error_tols, SEXP rel_error_tols, SEXP direct_mc_vec, SEXP solver_type, SEXP max_it, SEXP silent)
SEXP R_validate_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP direct_mc_vec, SEXP silent)
SEXP R_test_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP direct_mc_vec)
Function Documentation
R_solve_simultaneous_equations()
SEXP R_solve_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP lower_bounds, SEXP upper_bounds, SEXP abs_error_tols, SEXP rel_error_tols, SEXP direct_mc_vec, SEXP solver_type, SEXP max_it, SEXP silent)
Definition at line 14 of file R_simultaneous_equations.cpp.
References se_solver_factory::create(), format_se_solver_results(), keys(), list_from_map(), map_from_list(), and mc_vector_from_list().
R_test_simultaneous_equations()
SEXP R_test_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP direct_mc_vec)
Definition at line 154 of file R_simultaneous_equations.cpp.
References keys(), list_from_map(), map_from_list(), and mc_vector_from_list().
R_validate_simultaneous_equations()
SEXP R_validate_simultaneous_equations (SEXP known_quantities, SEXP unknown_quantities, SEXP direct_mc_vec, SEXP silent)
Definition at line 109 of file R_simultaneous_equations.cpp.
References analyze_simultaneous_equations_inputs(), make_vector(), map_from_list(), mc_vector_from_list(), r_logical_from_boolean(), and validate_simultaneous_equations_inputs().