The BioCro C++ Library: se_solver Class Reference
se_solver Class Reference abstract
An abstract class for a generic simultaneous equation solver. Its solve member function provides a uniform interface for all derived solvers, and its constructor defines inputs that are common to all solvers.
#include <se_solver.h>
Public Member Functions
se_solver (std::string solver_name, int max_it)
virtual ~se_solver ()=0
template<typename observer_type >
bool solve (std::unique_ptr< simultaneous_equations > const &se, std::vector< double > const &initial_guess_for_root, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > const &absolute_error_tolerances, std::vector< double > const &relative_error_tolerances, std::vector< double > &final_value_for_root, observer_type observer)
Tries to find a root, starting at the initial guess and staying within the bounds.
bool solve (std::unique_ptr< simultaneous_equations > const &se, std::vector< double > const &initial_guess_for_root, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > const &absolute_error_tolerances, std::vector< double > const &relative_error_tolerances, std::vector< double > &final_value_for_root)
std::string generate_info_report () const
Returns a string describing the se_solver's basic properties.
std::string generate_solve_report () const
Returns a string describing what happened during the most recent attempt to find a root.
int get_nsteps () const
Private Member Functions
virtual bool get_next_guess (std::unique_ptr< simultaneous_equations > const &se, std::vector< double > const &lower_bounds, std::vector< double > const &upper_bounds, std::vector< double > const &input_guess, std::vector< double > const &difference_vector_at_input_guess, std::vector< double > &output_guess, std::vector< double > &difference_vector_at_output_guess)=0
Private Attributes
const std::string solver_name
const int max_iterations
bool solve_method_has_been_called = false
bool converged_abs
bool converged_rel
int num_iterations
Detailed Description
An abstract class for a generic simultaneous equation solver. Its solve member function provides a uniform interface for all derived solvers, and its constructor defines inputs that are common to all solvers.
Definition at line 29 of file se_solver.h.
Constructor & Destructor Documentation
se_solver()
se_solver (std::string solver_name, int max_it) inline
Definition at line 32 of file se_solver.h.
~se_solver()
~se_solver () inline pure virtual
Definition at line 91 of file se_solver.h.
Member Function Documentation
generate_info_report()
std::string generate_info_report () const
Returns a string describing the se_solver's basic properties.
Definition at line 9 of file se_solver.cpp.
References max_iterations, and solver_name.
generate_solve_report()
std::string generate_solve_report () const
Returns a string describing what happened during the most recent attempt to find a root.
Definition at line 19 of file se_solver.cpp.
References converged_abs, converged_rel, num_iterations, and solve_method_has_been_called.
get_next_guess()
virtual bool get_next_guess (std::unique_ptr< simultaneous_equations > const & se, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > const & input_guess, std::vector< double > const & difference_vector_at_input_guess, std::vector< double > & output_guess, std::vector< double > & difference_vector_at_output_guess) private pure virtual
Implemented in newton_raphson_boost, newton_raphson_backtrack_boost, and fixed_point.
Referenced by solve().
get_nsteps()
int get_nsteps () const inline
Definition at line 68 of file se_solver.h.
References num_iterations.
solve() [1/2]
bool solve (std::unique_ptr< simultaneous_equations > const & se, std::vector< double > const & initial_guess_for_root, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > const & absolute_error_tolerances, std::vector< double > const & relative_error_tolerances, std::vector< double > & final_value_for_root) inline
Definition at line 51 of file se_solver.h.
References solve().
solve() [2/2]
bool solve (std::unique_ptr< simultaneous_equations > const & se, std::vector< double > const & initial_guess_for_root, std::vector< double > const & lower_bounds, std::vector< double > const & upper_bounds, std::vector< double > const & absolute_error_tolerances, std::vector< double > const & relative_error_tolerances, std::vector< double > & final_value_for_root, observer_type observer)
Tries to find a root, starting at the initial guess and staying within the bounds.
Parameters
[in] se
[in] initial_guess_for_root
[in] lower_bounds
[in] upper_bounds
[in] absolute_error_tolerances
[in] relative_error_tolerances
[out] final_value_for_root
[in] observer an object with an operator()(std::vector<double> const& uq, bool adjustment_made) method. This method will be called at each step of the solution process.
Returns
indicates whether or not the procedure was successful in finding a root.
The solver proceeds by steps, in which the current guess is checked to determine whether it is a root. If the guess is not sufficiently close to a root, a new guess is determined using the get_next_guess method, which must be implemented by derived classes. When a new guess is found, it is first checked to see if it lies within the acceptable bounds. If it lies outside the bounds, it is adjusted with the adjust_bad_guess method, which has a default behavior but can be overridden by derived classes.
Each guess is checked according to absolute and relative criteria, and a root is found when both tests are passed.
If the number of iterations exceeds a threshold value without finding a root, the loop ends and a failure is indicated.
Definition at line 130 of file se_solver.h.
References converged_abs, converged_rel, get_next_guess(), has_not_converged_abs(), has_not_converged_rel(), max_iterations, num_iterations, and solve_method_has_been_called.
Referenced by solve().
Member Data Documentation
converged_abs
bool converged_abs private
Definition at line 76 of file se_solver.h.
Referenced by generate_solve_report(), and solve().
converged_rel
bool converged_rel private
Definition at line 77 of file se_solver.h.
Referenced by generate_solve_report(), and solve().
max_iterations
const int max_iterations private
Definition at line 73 of file se_solver.h.
Referenced by generate_info_report(), and solve().
num_iterations
int num_iterations private
Definition at line 78 of file se_solver.h.
Referenced by generate_solve_report(), get_nsteps(), and solve().
solve_method_has_been_called
bool solve_method_has_been_called = false private
Definition at line 75 of file se_solver.h.
Referenced by generate_solve_report(), and solve().
solver_name
const std::string solver_name private
Definition at line 71 of file se_solver.h.
Referenced by generate_info_report().
The documentation for this class was generated from the following files:
/github/workspace/source/src/framework_ed/se_solver.h
/github/workspace/source/src/framework_ed/se_solver.cpp