The BioCro C++ Library: /github/workspace/source/src/dynamical_system_helper_functions.h File Reference
dynamical_system_helper_functions.h File Reference
#include <vector>
#include <set>
#include <unordered_map>
#include <string>
#include <memory>
#include "validate_dynamical_system.h"
#include "constants.h"
Functions
template<typename name_list_type , typename value_type_1 , typename value_type_2 >
std::vector< std::pair< value_type_1 *, const value_type_2 * > > get_pointer_pairs (name_list_type quantity_names, std::unordered_map< std::string, value_type_1 > &map_1, const std::unordered_map< std::string, value_type_2 > &map_2)
Returns pairs of pointers that each point to the same named quantity in each of the two input maps.
template<typename name_list_type , typename value_type >
std::vector< value_type * > get_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > &map)
Returns a vector of pointers that point to elements of a map whose targets are specified by quantity_names.
template<typename name_list_type , typename value_type >
std::vector< const value_type * > get_const_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > const &map)
Returns a vector of pointers that point to elements of a map whose targets are specified by quantity_names.
bool check_euler_requirement (module_vector const &modules_to_check)
Checks whether the collection of modules requires an Euler integrator.
Function Documentation
check_euler_requirement()
bool check_euler_requirement (module_vector const & modules_to_check)
Checks whether the collection of modules requires an Euler integrator.
Definition at line 6 of file dynamical_system_helper_functions.cpp.
Referenced by dynamical_system::requires_euler_integrator().
get_const_pointers()
std::vector<const value_type*> get_const_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > const & map)
Returns a vector of pointers that point to elements of a map whose targets are specified by quantity_names.
Here it is essential that the map is passed by reference; otherwise the pointers will be useless
Definition at line 65 of file dynamical_system_helper_functions.h.
Referenced by simultaneous_equations::simultaneous_equations().
get_pointer_pairs()
std::vector<std::pair<value_type_1*, const value_type_2*> > get_pointer_pairs (name_list_type quantity_names, std::unordered_map< std::string, value_type_1 > & map_1, const std::unordered_map< std::string, value_type_2 > & map_2)
Returns pairs of pointers that each point to the same named quantity in each of the two input maps.
Here it is essential that map_1 and map_2 are passed by reference; otherwise the pointers will be useless.
Definition at line 20 of file dynamical_system_helper_functions.h.
Referenced by dynamical_system::dynamical_system(), and simultaneous_equations::simultaneous_equations().
get_pointers()
std::vector<value_type*> get_pointers (name_list_type quantity_names, std::unordered_map< std::string, value_type > & map)
Returns a vector of pointers that point to elements of a map whose targets are specified by quantity_names.
Here it is essential that the map is passed by reference; otherwise the pointers will be useless
Definition at line 44 of file dynamical_system_helper_functions.h.
Referenced by simultaneous_equations::simultaneous_equations().