The BioCro C++ Library: /github/workspace/source/src/modules.cpp File Reference
modules.cpp File Reference
#include "modules.h"
Functions
void run_module_list (std::vector< std::unique_ptr< Module >> const &modules)
Runs each module in the input list.
Function Documentation
run_module_list()
void run_module_list (std::vector< std::unique_ptr< Module >> const & modules)
Runs each module in the input list.
Parameters
[in] modules A vector of unique pointers to module objects
Definition at line 8 of file modules.cpp.
Referenced by System::reset(), System::run_derivative_modules(), and System::update().