The BioCro C++ Library: /github/workspace/source/src/modules.h File Reference
modules.h File Reference
#include <vector>
#include <memory>
#include "module_helper_functions.h"
Classes
class module_base
Represents one or more equations.
class direct_module
This class represents a direct module.
class differential_module
This class represents a differential module.
Functions
void run_module_list (std::vector< std::unique_ptr< module_base >> const &modules)
Runs each module in the input list.
Function Documentation
run_module_list()
void run_module_list (std::vector< std::unique_ptr< module_base >> const & modules)
Runs each module in the input list.
Parameters
[in] modules A vector of unique pointers to module objects
Definition at line 8 of file modules.cpp.
Referenced by dynamical_system::reset(), dynamical_system::run_differential_modules(), and dynamical_system::update_all_quantities().