The BioCro C++ Library: /github/workspace/source/src/framework/state_map.h File Reference
state_map.h File Reference
#include <unordered_map>
#include <vector>
#include <set>
#include <string>
#include <stdexcept>
#include <algorithm>
Classes
struct bad_state_vector_map_index
Exception thrown when the at function tries access the state in a state_vector_map using an out-of-range index.
Typedefs
using string_vector = std::vector< std::string >
string_vector serves as an alias for a type widely used to hold lists of module names or lists of module parameters.
using string_set = std::set< std::string >
string_set serves as an alias for a type widely used to hold lists of module names or lists of module parameters.
using state_vector_map = std::unordered_map< std::string, std::vector< double > >
A state_vector_map represents a chronologically-ordered sequence of states of a system over some period of time.
using state_map = std::unordered_map< std::string, double >
A state_map represents the state of a system.
Functions
template<typename map_with_string_key_type >
string_vector keys (map_with_string_key_type const &map)
Given a map, return a sorted list of its keys.
state_map at (const state_vector_map &vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
template<typename name_list_type >
state_map state_map_from_names (name_list_type names)
Given a list of names, create a state_map object whose keys are precisely those names and whose values are all zero.
state_map abs (state_map x)
Typedef Documentation
state_map
using state_map = std::unordered_map<std::string, double>
A state_map represents the state of a system.
It maps names of system quantities to the values they have at some particular time.
Definition at line 56 of file state_map.h.
state_vector_map
using state_vector_map = std::unordered_map<std::string, std::vector<double> >
A state_vector_map represents a chronologically-ordered sequence of states of a system over some period of time.
The keys of the map are quantities of the system; each value is a vector representing the sequence of values of one of those quantities as it changes over time. To be a valid representation, each of the mapped-to vectors should be of the same length.
Definition at line 40 of file state_map.h.
string_set
using string_set = std::set<std::string>
string_set serves as an alias for a type widely used to hold lists of module names or lists of module parameters.
Formally, it is simply a std::set of std::strings. It differs from a string_vector because its elements are automatically sorted and are guaranteed to be unique.
Definition at line 29 of file state_map.h.
string_vector
using string_vector = std::vector<std::string>
string_vector serves as an alias for a type widely used to hold lists of module names or lists of module parameters.
Formally, it is simply a std::vector of std::strings. It differs from a string_set because its elements are not necessarily sorted and are not required to be unique.
Definition at line 19 of file state_map.h.
Function Documentation
abs()
state_map abs (state_map x)
at()
state_map at (const state_vector_map & vector_map, std::vector< double >::size_type n)
Given a sequence of states (presented as a state_vector_map) and an index n, return the n'th state in the sequence (counting from 0) in the form of a state_map.
Parameters
vector_map A sequence of states represented as a state_vector_map.
n An index into the sequence of states given by vector_map.
Returns
The n'th state (counting from 0) of the sequence of states represented by vector_map.
Exceptions
bad_state_vector_map_index if n is not a valid index for some or all the vector values of the map.
Definition at line 24 of file state_map.cpp.
Referenced by analyze_system_inputs(), dynamical_system::dynamical_system(), dynamical_system::get_output_quantity_names(), and validate_dynamical_system_inputs().
keys()
string_vector keys (map_with_string_key_type const & map)
Given a map, return a sorted list of its keys.
Parameters
map A map having keys of type std::string.
Returns
A vector containing all of the keys of the map.
Note
The minimal requirement on the "map" argument is that it be a "range" or "sequence" of objects that have a "first" member function yielding a string, what we are considering to be the "key" of the object.
Definition at line 71 of file state_map.h.
Referenced by dynamical_system::dynamical_system(), find_static_output_parameters(), find_unused_input_parameters(), dynamical_system::get_differential_quantity_names(), insert_key_names(), R_module_info(), R_solve_simultaneous_equations(), R_test_simultaneous_equations(), simultaneous_equations::simultaneous_equations(), and validate_dynamical_system_inputs().
state_map_from_names()
state_map state_map_from_names (name_list_type names)
Given a list of names, create a state_map object whose keys are precisely those names and whose values are all zero.
Definition at line 89 of file state_map.h.