var hierarchy =
[
    [ "base", null, [
      [ "ed_c4_leaf_photosynthesis", "classstandard_b_m_l_1_1ed__c4__leaf__photosynthesis.html", null ],
      [ "ed_c4_leaf_photosynthesis2", "classstandard_b_m_l_1_1ed__c4__leaf__photosynthesis2.html", null ],
      [ "ed_c4_leaf_photosynthesis3", "classstandard_b_m_l_1_1ed__c4__leaf__photosynthesis3.html", null ],
      [ "ed_c4_leaf_photosynthesis4", "classstandard_b_m_l_1_1ed__c4__leaf__photosynthesis4.html", null ],
      [ "ed_nikolov_conductance_free_solve", "classstandard_b_m_l_1_1ed__nikolov__conductance__free__solve.html", null ],
      [ "ed_p_m_temperature_solve", "classstandard_b_m_l_1_1ed__p__m__temperature__solve.html", null ]
    ] ],
    [ "c3_str", "structc3__str.html", null ],
    [ "c4_str", "structc4__str.html", null ],
    [ "Can_Str", "struct_can___str.html", null ],
    [ "collatz_result", "structcollatz__result.html", null ],
    [ "crop_phenology", "structcrop__phenology.html", null ],
    [ "dbp_str", "structdbp__str.html", null ],
    [ "differential_module", null, [
      [ "aba_decay", "classstandard_b_m_l_1_1aba__decay.html", null ],
      [ "bucket_soil_drainage", "classstandard_b_m_l_1_1bucket__soil__drainage.html", null ],
      [ "development_index", "classstandard_b_m_l_1_1development__index.html", null ],
      [ "example_model_partitioning", "classstandard_b_m_l_1_1example__model__partitioning.html", null ],
      [ "grimm_soybean_flowering", "classstandard_b_m_l_1_1grimm__soybean__flowering.html", null ],
      [ "harmonic_oscillator", "classstandard_b_m_l_1_1harmonic__oscillator.html", null ],
      [ "magic_clock", "classstandard_b_m_l_1_1magic__clock.html", null ],
      [ "night_and_day_trackers", "classstandard_b_m_l_1_1night__and__day__trackers.html", null ],
      [ "nr_ex", "classstandard_b_m_l_1_1nr__ex.html", null ],
      [ "one_layer_soil_profile", "classstandard_b_m_l_1_1one__layer__soil__profile.html", null ],
      [ "one_layer_soil_profile_derivatives", "classstandard_b_m_l_1_1one__layer__soil__profile__derivatives.html", null ],
      [ "partitioning_growth", "classstandard_b_m_l_1_1partitioning__growth.html", null ],
      [ "phase_clock", "classstandard_b_m_l_1_1phase__clock.html", null ],
      [ "poincare_clock", "classstandard_b_m_l_1_1poincare__clock.html", null ],
      [ "pokhilko_circadian_clock", "classstandard_b_m_l_1_1pokhilko__circadian__clock.html", null ],
      [ "senescence_logistic", "classstandard_b_m_l_1_1senescence__logistic.html", null ],
      [ "song_flowering", "classstandard_b_m_l_1_1song__flowering.html", null ],
      [ "thermal_time_and_frost_senescence", "classstandard_b_m_l_1_1thermal__time__and__frost__senescence.html", null ],
      [ "thermal_time_beta", "classstandard_b_m_l_1_1thermal__time__beta.html", null ],
      [ "thermal_time_bilinear", "classstandard_b_m_l_1_1thermal__time__bilinear.html", null ],
      [ "thermal_time_linear", "classstandard_b_m_l_1_1thermal__time__linear.html", null ],
      [ "thermal_time_linear_extended", "classstandard_b_m_l_1_1thermal__time__linear__extended.html", null ],
      [ "thermal_time_senescence", "classstandard_b_m_l_1_1thermal__time__senescence.html", null ],
      [ "thermal_time_trilinear", "classstandard_b_m_l_1_1thermal__time__trilinear.html", null ],
      [ "two_layer_soil_profile", "classstandard_b_m_l_1_1two__layer__soil__profile.html", null ],
      [ "utilization_growth", "classstandard_b_m_l_1_1utilization__growth.html", null ],
      [ "utilization_senescence", "classstandard_b_m_l_1_1utilization__senescence.html", null ]
    ] ],
    [ "direct_module", null, [
      [ "multilayer_canopy_photosynthesis< ed_ten_layer_canopy_properties, ed_c4_leaf_photosynthesis4 >", "classstandard_b_m_l_1_1multilayer__canopy__photosynthesis.html", [
        [ "ed_ten_layer_c4_canopy", "classstandard_b_m_l_1_1ed__ten__layer__c4__canopy.html", null ]
      ] ],
      [ "FvCB", "classstandard_b_m_l_1_1_fv_c_b.html", null ],
      [ "Module_1", "classstandard_b_m_l_1_1_module__1.html", null ],
      [ "Module_2", "classstandard_b_m_l_1_1_module__2.html", null ],
      [ "Module_3", "classstandard_b_m_l_1_1_module__3.html", null ],
      [ "ball_berry_module", "classstandard_b_m_l_1_1ball__berry__module.html", null ],
      [ "biomass_leaf_n_limitation", "classstandard_b_m_l_1_1biomass__leaf__n__limitation.html", null ],
      [ "buck_swvp", "classstandard_b_m_l_1_1buck__swvp.html", null ],
      [ "c3_assimilation", "classstandard_b_m_l_1_1c3__assimilation.html", null ],
      [ "c3_canopy", "classstandard_b_m_l_1_1c3__canopy.html", null ],
      [ "c3_leaf_photosynthesis", "classstandard_b_m_l_1_1c3__leaf__photosynthesis.html", null ],
      [ "c4_assimilation", "classstandard_b_m_l_1_1c4__assimilation.html", null ],
      [ "c4_canopy", "classstandard_b_m_l_1_1c4__canopy.html", null ],
      [ "c4_leaf_photosynthesis", "classstandard_b_m_l_1_1c4__leaf__photosynthesis.html", null ],
      [ "ed_abc_blc", "classstandard_b_m_l_1_1ed__abc__blc.html", null ],
      [ "ed_apply_stomatal_water_stress_via_assimilation", "classstandard_b_m_l_1_1ed__apply__stomatal__water__stress__via__assimilation.html", null ],
      [ "ed_apply_stomatal_water_stress_via_conductance", "classstandard_b_m_l_1_1ed__apply__stomatal__water__stress__via__conductance.html", null ],
      [ "ed_ball_berry", "classstandard_b_m_l_1_1ed__ball__berry.html", null ],
      [ "ed_boundary_conductance_max", "classstandard_b_m_l_1_1ed__boundary__conductance__max.html", null ],
      [ "ed_boundary_conductance_quadrature", "classstandard_b_m_l_1_1ed__boundary__conductance__quadrature.html", null ],
      [ "ed_c4photo", "classstandard_b_m_l_1_1ed__c4photo.html", null ],
      [ "ed_canac_leaf", "classstandard_b_m_l_1_1ed__canac__leaf.html", null ],
      [ "ed_collatz_c4_assimilation", "classstandard_b_m_l_1_1ed__collatz__c4__assimilation.html", null ],
      [ "ed_evapotrans2", "classstandard_b_m_l_1_1ed__evapotrans2.html", null ],
      [ "ed_gas_concentrations", "classstandard_b_m_l_1_1ed__gas__concentrations.html", null ],
      [ "ed_leaf_temperature", "classstandard_b_m_l_1_1ed__leaf__temperature.html", null ],
      [ "ed_long_wave_energy_loss", "classstandard_b_m_l_1_1ed__long__wave__energy__loss.html", null ],
      [ "ed_multilayer_canopy_integrator", "classstandard_b_m_l_1_1ed__multilayer__canopy__integrator.html", [
        [ "ed_ten_layer_canopy_integrator", "classstandard_b_m_l_1_1ed__ten__layer__canopy__integrator.html", null ]
      ] ],
      [ "ed_multilayer_canopy_properties", "classstandard_b_m_l_1_1ed__multilayer__canopy__properties.html", [
        [ "ed_ten_layer_canopy_properties", "classstandard_b_m_l_1_1ed__ten__layer__canopy__properties.html", null ]
      ] ],
      [ "ed_nikolov_conductance_forced", "classstandard_b_m_l_1_1ed__nikolov__conductance__forced.html", null ],
      [ "ed_nikolov_conductance_free", "classstandard_b_m_l_1_1ed__nikolov__conductance__free.html", null ],
      [ "ed_penman_monteith_leaf_temperature", "classstandard_b_m_l_1_1ed__penman__monteith__leaf__temperature.html", null ],
      [ "ed_penman_monteith_transpiration", "classstandard_b_m_l_1_1ed__penman__monteith__transpiration.html", null ],
      [ "ed_rh_to_mole_fraction", "classstandard_b_m_l_1_1ed__rh__to__mole__fraction.html", null ],
      [ "ed_stomata_water_stress_linear", "classstandard_b_m_l_1_1ed__stomata__water__stress__linear.html", null ],
      [ "ed_water_vapor_properties", "classstandard_b_m_l_1_1ed__water__vapor__properties.html", null ],
      [ "example_model_mass_gain", "classstandard_b_m_l_1_1example__model__mass__gain.html", null ],
      [ "fake_solar", "classstandard_b_m_l_1_1fake__solar.html", null ],
      [ "golden_ratio_hyperbola", "classstandard_b_m_l_1_1golden__ratio__hyperbola.html", null ],
      [ "grimm_soybean_flowering_calculator", "classstandard_b_m_l_1_1grimm__soybean__flowering__calculator.html", null ],
      [ "harmonic_energy", "classstandard_b_m_l_1_1harmonic__energy.html", null ],
      [ "hyperbola_2d", "classstandard_b_m_l_1_1hyperbola__2d.html", null ],
      [ "incident_shortwave_from_ground_par", "classstandard_b_m_l_1_1incident__shortwave__from__ground__par.html", null ],
      [ "leaf_gbw_nikolov", "classstandard_b_m_l_1_1leaf__gbw__nikolov.html", null ],
      [ "leaf_gbw_thornley", "classstandard_b_m_l_1_1leaf__gbw__thornley.html", null ],
      [ "leaf_shape_factor", "classstandard_b_m_l_1_1leaf__shape__factor.html", null ],
      [ "leaf_water_stress_exponential", "classstandard_b_m_l_1_1leaf__water__stress__exponential.html", null ],
      [ "light_from_solar", "classstandard_b_m_l_1_1light__from__solar.html", null ],
      [ "linear_vmax_from_leaf_n", "classstandard_b_m_l_1_1linear__vmax__from__leaf__n.html", null ],
      [ "multilayer_canopy_integrator", "classstandard_b_m_l_1_1multilayer__canopy__integrator.html", [
        [ "ten_layer_canopy_integrator", "classstandard_b_m_l_1_1ten__layer__canopy__integrator.html", null ]
      ] ],
      [ "multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >", "classstandard_b_m_l_1_1multilayer__canopy__photosynthesis.html", [
        [ "ten_layer_c3_canopy", "classstandard_b_m_l_1_1ten__layer__c3__canopy.html", null ],
        [ "ten_layer_c4_canopy", "classstandard_b_m_l_1_1ten__layer__c4__canopy.html", null ],
        [ "ten_layer_rue_canopy", "classstandard_b_m_l_1_1ten__layer__rue__canopy.html", null ]
      ] ],
      [ "multilayer_canopy_properties", "classstandard_b_m_l_1_1multilayer__canopy__properties.html", [
        [ "ten_layer_canopy_properties", "classstandard_b_m_l_1_1ten__layer__canopy__properties.html", null ]
      ] ],
      [ "no_leaf_resp_neg_assim_partitioning_growth_calculator", "classstandard_b_m_l_1_1no__leaf__resp__neg__assim__partitioning__growth__calculator.html", null ],
      [ "no_leaf_resp_partitioning_growth_calculator", "classstandard_b_m_l_1_1no__leaf__resp__partitioning__growth__calculator.html", null ],
      [ "oscillator_clock_calculator", "classstandard_b_m_l_1_1oscillator__clock__calculator.html", null ],
      [ "parameter_calculator", "classstandard_b_m_l_1_1parameter__calculator.html", null ],
      [ "partitioning_coefficient_logistic", "classstandard_b_m_l_1_1partitioning__coefficient__logistic.html", null ],
      [ "partitioning_coefficient_selector", "classstandard_b_m_l_1_1partitioning__coefficient__selector.html", null ],
      [ "partitioning_growth_calculator", "classstandard_b_m_l_1_1partitioning__growth__calculator.html", null ],
      [ "penman_monteith_leaf_temperature", "classstandard_b_m_l_1_1penman__monteith__leaf__temperature.html", null ],
      [ "penman_monteith_transpiration", "classstandard_b_m_l_1_1penman__monteith__transpiration.html", null ],
      [ "priestley_transpiration", "classstandard_b_m_l_1_1priestley__transpiration.html", null ],
      [ "rasmussen_specific_heat", "classstandard_b_m_l_1_1rasmussen__specific__heat.html", null ],
      [ "rh_to_mole_fraction", "classstandard_b_m_l_1_1rh__to__mole__fraction.html", null ],
      [ "rue_leaf_photosynthesis", "classstandard_b_m_l_1_1rue__leaf__photosynthesis.html", null ],
      [ "senescence_coefficient_logistic", "classstandard_b_m_l_1_1senescence__coefficient__logistic.html", null ],
      [ "shortwave_atmospheric_scattering", "classstandard_b_m_l_1_1shortwave__atmospheric__scattering.html", null ],
      [ "soil_evaporation", "classstandard_b_m_l_1_1soil__evaporation.html", null ],
      [ "solar_position_michalsky", "classstandard_b_m_l_1_1solar__position__michalsky.html", null ],
      [ "soybean_development_rate_calculator", "classstandard_b_m_l_1_1soybean__development__rate__calculator.html", null ],
      [ "stomata_water_stress_exponential", "classstandard_b_m_l_1_1stomata__water__stress__exponential.html", null ],
      [ "stomata_water_stress_linear", "classstandard_b_m_l_1_1stomata__water__stress__linear.html", null ],
      [ "stomata_water_stress_linear_and_aba_response", "classstandard_b_m_l_1_1stomata__water__stress__linear__and__aba__response.html", null ],
      [ "stomata_water_stress_sigmoid", "classstandard_b_m_l_1_1stomata__water__stress__sigmoid.html", null ],
      [ "thermal_time_development_rate_calculator", "classstandard_b_m_l_1_1thermal__time__development__rate__calculator.html", null ],
      [ "total_biomass", "classstandard_b_m_l_1_1total__biomass.html", null ],
      [ "utilization_growth_calculator", "classstandard_b_m_l_1_1utilization__growth__calculator.html", null ],
      [ "utilization_senescence_calculator", "classstandard_b_m_l_1_1utilization__senescence__calculator.html", null ],
      [ "water_vapor_properties_from_air_temperature", "classstandard_b_m_l_1_1water__vapor__properties__from__air__temperature.html", null ]
    ] ],
    [ "ET_Str", "struct_e_t___str.html", null ],
    [ "frostParms", "structfrost_parms.html", null ],
    [ "Light_model", "struct_light__model.html", null ],
    [ "Light_profile", "struct_light__profile.html", null ],
    [ "crop_phenology::minerals1", "structcrop__phenology_1_1minerals1.html", null ],
    [ "module_library", "classstandard_b_m_l_1_1module__library.html", null ],
    [ "nitroParms", "structnitro_parms.html", null ],
    [ "rd_str", "structrd__str.html", null ],
    [ "rue_str", "structrue__str.html", null ],
    [ "seqRD_str", "structseq_r_d__str.html", null ],
    [ "soilML_str", "structsoil_m_l__str.html", null ],
    [ "ws_str", "structws__str.html", null ]
];