The BioCro C++ Library: /github/workspace/src/R_dynamical_system.h File Reference
R_dynamical_system.h File Reference
#include <Rinternals.h>
Functions
SEXP R_validate_dynamical_system_inputs (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP verbose)
Function Documentation
R_validate_dynamical_system_inputs()
SEXP R_validate_dynamical_system_inputs (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_mc_vec, SEXP differential_mc_vec, SEXP verbose)
Definition at line 14 of file R_dynamical_system.cpp.
References analyze_system_inputs(), map_from_list(), map_vector_from_list(), mc_vector_from_list(), r_logical_from_boolean(), and validate_dynamical_system_inputs().