The BioCro C++ Library: /github/workspace/src/R_modules.cpp File Reference
R_modules.cpp File Reference
#include <string>
#include <exception>
#include <Rinternals.h>
#include <memory>
#include "framework/R_helper_functions.h"
#include "framework/state_map.h"
#include "framework/module_creator.h"
#include "framework/module.h"
#include "R_modules.h"
Functions
SEXP R_module_info (SEXP mw_ptr_vec, SEXP verbose)
Determines vital information about a single module.
SEXP R_evaluate_module (SEXP mw_ptr_vec, SEXP input_quantities)
Determines the values of a module's output quantities from the supplied values of its input quantities.
Function Documentation
R_evaluate_module()
SEXP R_evaluate_module (SEXP mw_ptr_vec, SEXP input_quantities)
Determines the values of a module's output quantities from the supplied values of its input quantities.
Parameters
[in] mw_ptr_vec A single-element vector containing one R external pointer pointing to a module_creator object, typically produced by the R_module_creators() function. If the vector has more than one element, only the first will be used.
[in] input_quantities A list of named numeric elements where the name of each element corresponds to one of the module's input quantities. Any element whose name does not correspond to one of the module's input quantities will be ignored by the module.
Returns
A list of named numeric elements where the name of each element corresponds to the one of the module's output quantities
Definition at line 161 of file R_modules.cpp.
References module_creator::create_module(), module_creator::get_outputs(), list_from_map(), map_from_list(), and mc_vector_from_list().
R_module_info()
SEXP R_module_info (SEXP mw_ptr_vec, SEXP verbose)
Determines vital information about a single module.
Parameters
[in] mw_ptr_vec A single-element vector containing one R external pointer pointing to a module_creator object, typically produced by the R_module_creators() function. If the vector has more than one element, only the first will be used.
[in] verbose When verbose is TRUE, print information to the R console
Returns
An R list containing several named elements that describe the module. See list_from_module_info() for more details.
Definition at line 28 of file R_modules.cpp.
References module_creator::create_module(), module_creator::get_inputs(), module_creator::get_name(), module_creator::get_outputs(), keys(), list_from_module_info(), and mc_vector_from_list().