The BioCro C++ Library: /github/workspace/src/framework/quadratic_root.h File Reference
quadratic_root.h File Reference
Enumerations
enum quadratic_root_type { plus , minus , larger , smaller }
Functions
double quadratic_root (double a, double b, double c, quadratic_root_type root_type)
Computes one of the roots of a quadratic equation.
double quadratic_root_plus (double a, double b, double c)
A wrapper for quadratic_root() that returns the "plus" root.
double quadratic_root_minus (double a, double b, double c)
A wrapper for quadratic_root() that returns the "minus" root.
double quadratic_root_max (double a, double b, double c)
A wrapper for quadratic_root() that returns the larger root.
double quadratic_root_min (double a, double b, double c)
A wrapper for quadratic_root() that returns the smaller root.
Enumeration Type Documentation
quadratic_root_type
enum quadratic_root_type
Enumerator
plus
minus
larger
smaller
Definition at line 4 of file quadratic_root.h.
Function Documentation
quadratic_root()
double quadratic_root (double a, double b, double c, quadratic_root_type root_type)
Computes one of the roots of a quadratic equation.
In general, an equation of the type
\[ a \cdot x^2 + b \cdot x + c = 0 \]
[Equation (1)]
has two solutions given by
\[ x = \frac{-b \pm \sqrt{b^2 - 4 \cdot a \cdot c}}{2 \cdot a} \]
. [Equation (2)]
These are referred to as the roots of a quadratic equation. Here, we refer to the separate roots as \(x_{plus} = (-b + \sqrt{b^2 - 4ac}) / (2a) \) and \(x_{minus} = (-b - \sqrt{b^2 - 4ac}) / (2a) \).
In the special case where \(a = 0 \), Equation (1) reduces to
\[ b \cdot x + c = 0 \]
, [Equation (3)]
which has a single solution given by \(x_{single} = -c / b \).
Another special case is where \(b^2 - 4 a c < 0\). In this case, the two roots are imaginary. Usually this is considered an error in BioCro, so this function will throw an error in that case.
If \(a = 0 \), this function returns \(x_{single} \). Otherwise, it returns either \(x_{plus} \) or \(x_{minus} \) depending on the value of the root_type input argument:
When root_type is plus, \(x_{plus} \) is returned.
When root_type is minus, \(x_{minus} \) is returned.
When root_type is larger, the larger root is returned.
When root_type is smaller, the smaller root is returned.
Convenience functions are also provided that fix root_type to a particular value:
quadratic_root_plus() sets root_type to plus.
quadratic_root_minus() sets root_type to minus.
quadratic_root_max() sets root_type to larger.
quadratic_root_min() sets root_type to smaller.
Parameters
[in] a The value of \(a \).
[in] b The value of \(b \).
[in] c The value of \(c \).
[in] root_type A switch that determines the return value (see above).
Returns
One of the roots of \(a \cdot x^2 + b \cdot x + c = 0 \).
Definition at line 64 of file quadratic_root.cpp.
References abs(), calculation_constants::eps_zero, larger, minus, plus, and smaller.
Referenced by quadratic_root_max(), quadratic_root_min(), quadratic_root_minus(), and quadratic_root_plus().
quadratic_root_max()
double quadratic_root_max (double a, double b, double c) inline
A wrapper for quadratic_root() that returns the larger root.
Definition at line 34 of file quadratic_root.h.
References larger, and quadratic_root().
quadratic_root_min()
double quadratic_root_min (double a, double b, double c) inline
A wrapper for quadratic_root() that returns the smaller root.
Definition at line 42 of file quadratic_root.h.
References quadratic_root(), and smaller.
quadratic_root_minus()
double quadratic_root_minus (double a, double b, double c) inline
A wrapper for quadratic_root() that returns the "minus" root.
Definition at line 26 of file quadratic_root.h.
References minus, and quadratic_root().
quadratic_root_plus()
double quadratic_root_plus (double a, double b, double c) inline
A wrapper for quadratic_root() that returns the "plus" root.
Definition at line 18 of file quadratic_root.h.
References plus, and quadratic_root().