The BioCro C++ Library: /github/workspace/src/module_library/ball_berry_gs.h File Reference
ball_berry_gs.h File Reference
#include "stomata_outputs.h"
Functions
stomata_outputs ball_berry_gs (double assimilation, double ambient_c, double ambient_rh, double bb_offset, double bb_slope, double gbw, double leaf_temperature, double ambient_air_temperature)
Calculates steady-state stomatal conductance to water vapor using the Ball-Berry model.
Function Documentation
ball_berry_gs()
stomata_outputs ball_berry_gs (double assimilation, double ambient_c, double ambient_rh, double bb_offset, double bb_slope, double gbw, double leaf_temperature, double ambient_air_temperature)
Calculates steady-state stomatal conductance to water vapor using the Ball-Berry model.
The Ball-Berry is a simple empirical model for the steady-state response of stomata to external conditions and was first described in Ball and Berry (1987). The main idea is that stomata open in response to brighter light or low CO2 availability, and close in response to low humidity (to limit water losses from transpiration). This idea can be expressed mathematically as
\[ g_{sw} = b_0 + b_1 \cdot \frac{ A_n \cdot h_s}{C_s} \quad \text{if} \; A_n \geq 0, \qquad \text{(1)} \]
where \(g_{sw} \) is the stomatal conductance to water vapor diffusion, \(A_n \) is the net CO2 assimilation rate, \(b_0 \) and \(b_1 \) are the Ball-Berry intercept and slope, \(h_s \) is the relative humidity at the leaf surface, and \(C_s \) is the CO2 concentration at the leaf surface. When \(A_n < 0 \), \(g_{sw} = b_0 \).
When using this model in the context of a crop growth simulation, it is necessary to determine \(h_s \) and \(C_s \) from the CO2 concentration and relative humidity in the ambient air surrounding the crop. This can be accomplished using the following equations:
\[ C_s = C_a - \frac{A_n \cdot 1.37}{g_{bw}} \qquad \text{(2)} \]
and
\[ h_s = \frac{-b + \sqrt{b^2 - 4 \cdot a \cdot c}}{2 \cdot a}, \qquad \text{(3)} \]
where
\[ a = b_1 \cdot \frac{A_n}{C_s}, \]
\[ b = b_0 + g_{bw} - b_1 \cdot \frac{A_n}{C_s}, \]
and
\[ c = - \left(g_{bw} \cdot h_a \cdot \frac{P_{w,sat}(T_a)}{P_{w,sat}(T_l)} + b_0 \right) \]
.
See the "Using the Ball-Berry Model in Crop Growth Simulations" vignette for more information about this model and these equations.
References:
[Ball, Woodrow, and Berry. "A Model Predicting Stomatal Conductance and its Contribution to the Control of Photosynthesis under Different Environmental Conditions" (1987)] (https://doi.org/10.1007/978-94-017-0519-6_48)
Parameters
[in] assimilation Net CO2 assimilation rate \(A_n \) in units of mol / m^2 / s.
[in] ambient_c Ambient CO2 concentration \(C_a \) in units of mol / mol.
[in] ambient_rh Ambient relative humidity \(h_a \) expressed as a fraction between 0 and 1 (dimensionless from Pa / Pa).
[in] bb_offset Ball-Berry offset \(b_0 \) in units of mol / m^2 / s.
[in] bb_slope Ball-Berry slope \(b_1 \) (dimensionless from [mol / m^2 / s] / [mol / m^2 / s]).
[in] gbw Boundary layer conductance to water vapor diffusion \(g_{bw} \) in units of mol / m^2 / s. For an isolated leaf, this should be the leaf boundary layer conductance; for a leaf within a canopy, this should be the total conductance including the leaf and canopy boundary layer conductances.
[in] leaf_temperature \(T_l \) in units of degrees C.
[in] ambient_air_temperature \(T_a \) in units of degrees C.
Returns
Stomatal conductance to water vapor diffusion \(g_{sw} \) in units of mmol / m^2 / s
Definition at line 97 of file ball_berry_gs.cpp.
References stomata_outputs::cs, and saturation_vapor_pressure().
Referenced by c3photoC(), c4photoC(), and rue_photo().