The BioCro C++ Library: /github/workspace/src/module_library/c4photo.cpp File Reference
c4photo.cpp File Reference
#include <cmath>
#include "ball_berry_gs.h"
#include "conductance_limited_assim.h"
#include "../framework/constants.h"
#include "../framework/quadratic_root.h"
#include "c4photo.h"
Functions
photosynthesis_outputs c4photoC (double const Qp, double const leaf_temperature, double const ambient_temperature, double const relative_humidity, double const vmax, double const alpha, double const kparm, double const theta, double const beta, double const Rd, double const bb0, double const bb1, double const Gs_min, double const StomaWS, double const Ca, double const atmospheric_pressure, double const upperT, double const lowerT, double const gbw)
Function Documentation
c4photoC()
photosynthesis_outputs c4photoC (double const Qp, double const leaf_temperature, double const ambient_temperature, double const relative_humidity, double const vmax, double const alpha, double const kparm, double const theta, double const beta, double const Rd, double const bb0, double const bb1, double const Gs_min, double const StomaWS, double const Ca, double const atmospheric_pressure, double const upperT, double const lowerT, double const gbw)
Definition at line 11 of file c4photo.cpp.
References photosynthesis_outputs::Assim, ball_berry_gs(), conductance_limited_assim(), stomata_outputs::cs, stomata_outputs::gsw, and stomata_outputs::hs.
Referenced by CanAC().