The BioCro C++ Library: /github/workspace/src/module_library/FvCB_assim.cpp File Reference
FvCB_assim.cpp File Reference
#include <algorithm>
#include <limits>
#include "FvCB_assim.h"
Functions
FvCB_outputs FvCB_assim (double Ci, double Gstar, double J, double Kc, double Ko, double Oi, double Rd, double TPU, double Vcmax, double alpha_TPU, double electrons_per_carboxylation, double electrons_per_oxygenation)
Computes the net CO2 assimilation rate (and other values) using the Farquhar-von-Caemmerer-Berry model for C3 photosynthesis.
Variables
double inf = std::numeric_limits<double>::infinity()
Function Documentation
FvCB_assim()
FvCB_outputs FvCB_assim (double Ci, double Gstar, double J, double Kc, double Ko, double Oi, double Rd, double TPU, double Vcmax, double alpha_TPU, double electrons_per_carboxylation, double electrons_per_oxygenation)
Computes the net CO2 assimilation rate (and other values) using the Farquhar-von-Caemmerer-Berry model for C3 photosynthesis.
Here we use the model equations as described in Lochocki & McGrath (2023; in preparation). In this formulation, the net CO2 assimilation rate \(A_n \) is given by
\[ A_n = \left(1 - \Gamma^* / C \right) \cdot V_c - R_d, \qquad \text{(1)} \]
where \(\Gamma^* \) is the CO2 compensation point in the absence of day respiration, \(C \) is the concentration of CO2 in the vicinity of Rubisco, \(V_c \) is the RuBP carboxylation rate, and \(R_d \) is the rate of day respiration. The RuBP carboxylation rate is taken to be the smallest of three potential carboxylation rates:
\[ V_c = \text{min} \{ W_c, W_j, W_p \}. \qquad \text{(2)} \]
Here, \(W_c \), \(W_j \), and \(W_p \) are the Rubisco-limited, RuBP-regeneration-limited, and triose-phosphate-utilization (TPU)-limited RuBP carboxylation rates, respectively. These rates are defined as follows:
\[ W_c = \frac{V_{c,max} \cdot C}{C + K_C \cdot \left(1 + O / K_O \right)}, \qquad \text{(3)} \]
\[ W_j = \frac{J \cdot C}{e_c \cdot C + 2 \cdot e_o \cdot \Gamma^*}, \qquad \text{(4)} \]
and
\[ W_p = \frac{3 \cdot C \cdot T_p}{C - \Gamma^* \cdot \left(1 + 3 \cdot \alpha \right)}, \qquad \text{(5)} \]
where \(V_{c,max} \) is the maximum Rubisco carboxylation rate, \(K_C \) and \(K_O \) are Michaelis-Menten constants for cabroxylation and oxygenation by Rubisco, \(O \) is the O2 concentration in the vicinity of Rubisco, \(J \) is the RuBP regeneration rate, \(e_c \) is the number of electrons per carboxylation, \(e_o \) is the number of electrons per oxygenation, \(T_p \) is the maximum rate of triose phosphate utilization, and \(\alpha \) is the fraction of glycolate carbon not returned to the chloroplast. Note that Equation (5) is only applicable when \(C > \Gamma^* \cdot (1 + 3 \cdot \alpha) \); for smaller values of \(C \), \(W_p = \infty \).
Finally, it is also possible to use Equations (1, 3-5) to calculate the net CO2 assimilation rates that would occur when carboxylation is determined by either of the three potential rates:
\[ A_c = \left(1 - \Gamma^* / C \right) \cdot W_c - R_d, \qquad \text{(6)} \]
\[ A_j = \left(1 - \Gamma^* / C \right) \cdot W_j - R_d, \qquad \text{(7)} \]
and
\[ A_p = \left(1 - \Gamma^* / C \right) \cdot W_p - R_d. \qquad \text{(8)} \]
Note that the limits of the expressions for \(A_c \) and \(A_j \) in Equations (6) and (7) as \(C \rightarrow 0 \) are finite even when \(1 - \Gamma^* / C \rightarrow -\infty \). So these net CO2 assimilation rates can be calculated even for \(C = 0 \). As discussed above, TPU cannot limit carboxylation or determine the net CO2 assimilation rate when \(C = 0 \).
Parameters
[in] Ci The value of \(C \) in units of micromol / mol.
[in] Gstar The value of \(\Gamma^* \) in units of micromol / mol.
[in] J The value of \(J \) in units of micromol / m^2 / s.
[in] Kc The value of \(K_C \) in units of micromol / mol.
[in] Ko The value of \(K_O \) in units of mmol / mol.
[in] Oi The value of \(O \) in units of mmol / mol.
[in] Rd The value of \(R_d \) in units of micromol / m^2 / s.
[in] TPU The value of \(T_p \) in units of micromol / m^2 / s.
[in] Vcmax The value of \(V_{c,max} \) in units of micromol / m^2 / s.
[in] alpha_TPU The value of \(0 \leq \alpha \leq 1 \) (dimensionless).
[in] electrons_per_carboxylation The value of \(e_c \).
[in] electrons_per_oxygenation The value of \(e_o \).
Returns
A structure containing values of \(A_n \), \(A_c \), \(A_j \), \(A_p \), \(W_c \), \(W_j \), \(W_p \), in units of micromol / m^2 / s.
Definition at line 115 of file FvCB_assim.cpp.
References FvCB_outputs::Ac, FvCB_outputs::Aj, FvCB_outputs::An, FvCB_outputs::Ap, inf, FvCB_outputs::Vc, FvCB_outputs::Wc, FvCB_outputs::Wj, and FvCB_outputs::Wp.
Referenced by c3photoC(), and FvCB::do_operation().
Variable Documentation
inf
double inf = std::numeric_limits<double>::infinity()
Definition at line 5 of file FvCB_assim.cpp.
Referenced by FvCB_assim().