The BioCro C++ Library: direct_module Class Reference
direct_module Class Reference abstract
This class represents a direct module.
#include <module.h>
Inherits module.
Inherited by FvCB, Module_1, Module_2, Module_3, ball_berry, biomass_leaf_n_limitation, buck_swvp, c3_assimilation, c3_canopy, c3_leaf_photosynthesis, c4_assimilation, c4_canopy, c4_leaf_photosynthesis, example_model_mass_gain, fake_solar, golden_ratio_hyperbola, grimm_soybean_flowering_calculator, harmonic_energy, hyperbola_2d, incident_shortwave_from_ground_par, leaf_gbw_nikolov, leaf_gbw_thornley, leaf_shape_factor, leaf_water_stress_exponential, light_from_solar, linear_vmax_from_leaf_n, litter_cover, multilayer_canopy_integrator, multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >, multilayer_canopy_properties, no_leaf_resp_neg_assim_partitioning_growth_calculator, no_leaf_resp_partitioning_growth_calculator, oscillator_clock_calculator, parameter_calculator, partitioning_coefficient_logistic, partitioning_coefficient_selector, partitioning_growth_calculator, penman_monteith_leaf_temperature, penman_monteith_transpiration, priestley_transpiration, rasmussen_specific_heat, rh_to_mole_fraction, rue_leaf_photosynthesis, senescence_coefficient_logistic, shortwave_atmospheric_scattering, soil_evaporation, soil_sunlight, solar_position_michalsky, soybean_development_rate_calculator, stomata_water_stress_exponential, stomata_water_stress_linear, stomata_water_stress_linear_and_aba_response, stomata_water_stress_sigmoid, thermal_time_development_rate_calculator, total_biomass, varying_Jmax25, and water_vapor_properties_from_air_temperature.
Public Member Functions
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Protected Member Functions
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
virtual void update (double *output_ptr, const double &value) const =0
Detailed Description
This class represents a direct module.
This class has a pure virtual destructor to designate it as being intentionally abstract.
Definition at line 87 of file module.h.
Constructor & Destructor Documentation
direct_module()
direct_module (bool requires_euler = false) inline
Definition at line 90 of file module.h.
~direct_module()
~direct_module () inline pure virtual
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Definition at line 105 of file module.h.
Member Function Documentation
update()
void update (double * output_ptr, const double & value) const inline protected virtual
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
See differential_module::update() for a contrasting situation.
Implements module.
Definition at line 115 of file module.h.
Referenced by ball_berry::do_operation(), biomass_leaf_n_limitation::do_operation(), buck_swvp::do_operation(), c3_assimilation::do_operation(), c3_canopy::do_operation(), c3_leaf_photosynthesis::do_operation(), c4_assimilation::do_operation(), c4_canopy::do_operation(), c4_leaf_photosynthesis::do_operation(), example_model_mass_gain::do_operation(), fake_solar::do_operation(), FvCB::do_operation(), grimm_soybean_flowering_calculator::do_operation(), harmonic_energy::do_operation(), incident_shortwave_from_ground_par::do_operation(), leaf_gbw_nikolov::do_operation(), leaf_gbw_thornley::do_operation(), leaf_shape_factor::do_operation(), leaf_water_stress_exponential::do_operation(), light_from_solar::do_operation(), linear_vmax_from_leaf_n::do_operation(), litter_cover::do_operation(), Module_1::do_operation(), Module_2::do_operation(), Module_3::do_operation(), no_leaf_resp_partitioning_growth_calculator::do_operation(), oscillator_clock_calculator::do_operation(), parameter_calculator::do_operation(), partitioning_coefficient_selector::do_operation(), partitioning_growth_calculator::do_operation(), penman_monteith_leaf_temperature::do_operation(), penman_monteith_transpiration::do_operation(), priestley_transpiration::do_operation(), rasmussen_specific_heat::do_operation(), rh_to_mole_fraction::do_operation(), rue_leaf_photosynthesis::do_operation(), shortwave_atmospheric_scattering::do_operation(), soil_evaporation::do_operation(), soil_sunlight::do_operation(), solar_position_michalsky::do_operation(), stomata_water_stress_exponential::do_operation(), stomata_water_stress_linear::do_operation(), stomata_water_stress_linear_and_aba_response::do_operation(), stomata_water_stress_sigmoid::do_operation(), total_biomass::do_operation(), varying_Jmax25::do_operation(), water_vapor_properties_from_air_temperature::do_operation(), golden_ratio_hyperbola::do_operation(), hyperbola_2d::do_operation(), no_leaf_resp_neg_assim_partitioning_growth_calculator::do_operation(), partitioning_coefficient_logistic::do_operation(), senescence_coefficient_logistic::do_operation(), soybean_development_rate_calculator::do_operation(), thermal_time_development_rate_calculator::do_operation(), multilayer_canopy_integrator::run(), and multilayer_canopy_properties::run().
The documentation for this class was generated from the following file:
/github/workspace/src/framework/module.h