The BioCro C++ Library: water_vapor_properties_from_air_temperature Class Reference
water_vapor_properties_from_air_temperature Class Reference
#include <water_vapor_properties_from_air_temperature.h>
Public Member Functions
water_vapor_properties_from_air_temperature (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Private Attributes
double const & temp
double const & rh
double const & specific_heat_of_air
double * latent_heat_vaporization_of_water_op
double * slope_water_vapor_op
double * saturation_water_vapor_pressure_op
double * water_vapor_pressure_op
double * vapor_density_deficit_op
double * psychrometric_parameter_op
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
virtual void update (double *output_ptr, const double &value) const =0
Detailed Description
Definition at line 13 of file water_vapor_properties_from_air_temperature.h.
Constructor & Destructor Documentation
water_vapor_properties_from_air_temperature()
water_vapor_properties_from_air_temperature (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 16 of file water_vapor_properties_from_air_temperature.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements module.
Definition at line 78 of file water_vapor_properties_from_air_temperature.h.
References conversion_constants::celsius_to_kelvin, physical_constants::ideal_gas_constant, water_vapor_properties_from_air_temperature::latent_heat_vaporization_of_water_op, physical_constants::molar_mass_of_water, water_vapor_properties_from_air_temperature::psychrometric_parameter_op, water_vapor_properties_from_air_temperature::rh, saturation_vapor_pressure(), water_vapor_properties_from_air_temperature::saturation_water_vapor_pressure_op, water_vapor_properties_from_air_temperature::slope_water_vapor_op, water_vapor_properties_from_air_temperature::specific_heat_of_air, water_vapor_properties_from_air_temperature::temp, TempToDdryA(), TempToLHV(), TempToSFS(), direct_module::update(), water_vapor_properties_from_air_temperature::vapor_density_deficit_op, and water_vapor_properties_from_air_temperature::water_vapor_pressure_op.
get_inputs()
string_vector get_inputs () static
Definition at line 57 of file water_vapor_properties_from_air_temperature.h.
get_name()
static std::string get_name () inline static
Definition at line 37 of file water_vapor_properties_from_air_temperature.h.
get_outputs()
string_vector get_outputs () static
Definition at line 66 of file water_vapor_properties_from_air_temperature.h.
Member Data Documentation
latent_heat_vaporization_of_water_op
double* latent_heat_vaporization_of_water_op private
Definition at line 46 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
psychrometric_parameter_op
double* psychrometric_parameter_op private
Definition at line 51 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
rh
double const& rh private
Definition at line 42 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
saturation_water_vapor_pressure_op
double* saturation_water_vapor_pressure_op private
Definition at line 48 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
slope_water_vapor_op
double* slope_water_vapor_op private
Definition at line 47 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
specific_heat_of_air
double const& specific_heat_of_air private
Definition at line 43 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
temp
double const& temp private
Definition at line 41 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
vapor_density_deficit_op
double* vapor_density_deficit_op private
Definition at line 50 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
water_vapor_pressure_op
double* water_vapor_pressure_op private
Definition at line 49 of file water_vapor_properties_from_air_temperature.h.
Referenced by water_vapor_properties_from_air_temperature::do_operation().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/water_vapor_properties_from_air_temperature.h