The BioCro C++ Library: /github/workspace/src/framework/dynamical_system.h File Reference
dynamical_system.h File Reference
#include <vector>
#include <string>
#include <stdexcept>
#include <memory>
#include <utility>
#include "state_map.h"
#include "module_creator.h"
#include "module.h"
#include "validate_dynamical_system.h"
#include "dynamical_system_helper_functions.h"
Classes
class dynamical_system
Defines a dynamical system which can be solved using an ode_solver.
class push_back_state_and_time< vector_type >
An observer class used to store state and time values during a simulation.
Functions
template<typename vector_type , typename time_type >
state_vector_map get_results_from_system (std::shared_ptr< dynamical_system > sys, const vector< vector_type > &x_vec, const vector< time_type > &times)
Calculates values for all of the system's output quantities based on a list of differential quantity values and their associated times.
template<typename vector_type , typename time_type >
void evaluate_equations (std::shared_ptr< dynamical_system > const &sys, vector_type const &x, time_type t, vector_type &y)
Define evaluation behavior for a set of equations defined by a dynamical_system object. This is required to use calculate_jacobian() with a dynamical_system object.
Function Documentation
evaluate_equations()
void evaluate_equations (std::shared_ptr< dynamical_system > const & sys, vector_type const & x, time_type t, vector_type & y)
Define evaluation behavior for a set of equations defined by a dynamical_system object. This is required to use calculate_jacobian() with a dynamical_system object.
Parameters
[in] sys a shared pointer to a dynamical_system object.
[in] x a vector to be passed to the dynamical_system as an input. Since we are evaluating a dynamical_system, x contains values of the dynamical_system's differential quantities.
[in] t a time to be passed to the dynamical_system as an input.
[out] y the vector output. Since we are evaluating a dynamical_system object, y contains the time derivative of each differential quantity.
Definition at line 470 of file dynamical_system.h.
Referenced by calculate_jacobian(), calculate_jacobian_and_time_derivative(), and calculate_time_derivative().
get_results_from_system()
state_vector_map get_results_from_system (std::shared_ptr< dynamical_system > sys, const vector< vector_type > & x_vec, const vector< time_type > & times)
Calculates values for all of the system's output quantities based on a list of differential quantity values and their associated times.
Definition at line 416 of file dynamical_system.h.
Referenced by boost_ode_solver< state_type >::do_integrate().