The BioCro C++ Library: /github/workspace/src/module_library/sunML.cpp File Reference
sunML.cpp File Reference
#include "sunML.h"
Functions
double thin_layer_absorption (double R, double T, double I_0)
Computes absorbed light from incident light for a thin layer of material.
double thick_layer_absorption (double R, double T, double I_0)
Computes absorbed light from incident light for a thick layer of material.
double absorbed_shortwave_from_incident_ppfd (double incident_ppfd, double par_energy_content, double par_energy_fraction, double leaf_reflectance, double leaf_transmittance)
Computes total absorbed shortwave radiation from the photosynthetically active photon flux density (PPFD) incident on a leaf.
Light_profile sunML (double ambient_ppfd_beam, double ambient_ppfd_diffuse, double lai, int nlayers, double cosine_zenith_angle, double kd, double chil, double absorptivity, double heightf, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
Function Documentation
absorbed_shortwave_from_incident_ppfd()
double absorbed_shortwave_from_incident_ppfd (double incident_ppfd, double par_energy_content, double par_energy_fraction, double leaf_reflectance, double leaf_transmittance)
Computes total absorbed shortwave radiation from the photosynthetically active photon flux density (PPFD) incident on a leaf.
The total absorbed shortwave radiation is determined using the following steps:
determine the incident photosynthetically active radiation (PAR) using the energy content of PAR
determine the incident near-infrared radiation (NIR) from the incident PAR using the PAR energy fraction
determine the total incident radiation by adding the incident PAR and NIR
determine the total absorbed radiation using the leaf's reflection and transmission coefficients
Parameters
[in] incident_ppfd Photosynthetically active photon flux density (PPFD) incident on a leaf expressed in micromol / m^2 / s
[in] par_energy_content The energy content of PPFD expressed in J / micromol
[in] par_energy_fraction The fraction of total shortwave energy contained in the PAR band expressed as a real number between 0 and 1
[in] leaf_reflectance The fractional amount of shortwave radiation reflected by the leaf (weighted across all shortwave radiation)
[in] leaf_transmittance The fractional amount of shortwave radiation transmitted through the leaf (weighted across all shortwave radiation)
Returns
The total shortwave radiation absorbed by the leaf expressed in J / m^2 / s
Definition at line 122 of file sunML.cpp.
References thick_layer_absorption().
Referenced by sunML().
sunML()
Light_profile sunML (double ambient_ppfd_beam, double ambient_ppfd_diffuse, double lai, int nlayers, double cosine_zenith_angle, double kd, double chil, double absorptivity, double heightf, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
Parameters
[in] ambient_ppfd_beam Photosynthetically active photon flux density (PPFD) for beam light passing through a surface perpendicular to the beam direction at the top of the canopy; this represents direct sunlight for a plant in a field (micromol / (m^2 beam) / s)
[in] ambient_ppfd_diffuse Photosynthetically active photon flux density (PPFD) for diffuse light at the top of the canopy; this represents diffuse light scattered out of the solar beam by the Earth's atmosphere for a plant in a field; as a diffuse flux density, this represents the flux through any surface (micromol / m^2 / s)
[in] lai Leaf area index (LAI) of the entire canopy, which represents the leaf area per unit of ground area (dimensionless from m^2 leaf / m^2 ground)
[in] nlayers Integer number of layers in the canopy
[in] cosine_zenith_angle Cosine of the solar zenith angle (dimensionless)
[in] kd Extinction coefficient for diffuse light (dimensionless)
[in] chil Ratio of average projected areas of canopy elements on horizontal surfaces; for a spherical leaf distribution, chil = 0; for a vertical leaf distribution, chil = 1; for a horizontal leaf distribution, chil approaches infinity (dimensionless from m^2 / m^2)
[in] absorptivity The leaf absorptivity on a quantum basis (dimensionless from mol / mol)
[in] heightf Leaf area density, i.e., LAI per height of canopy (m^-1 from m^2 leaf / m^2 ground / m height)
Returns
An n-layered light profile representing quantities within the canopy, including several photon flux densities and the relative fractions of shaded and sunlit leaves
Definition at line 188 of file sunML.cpp.
References absorbed_shortwave_from_incident_ppfd(), Light_profile::average_absorbed_shortwave, Light_profile::average_incident_ppfd, Light_profile::canopy_direct_transmission_fraction, Light_profile::height, Light_profile::incident_ppfd_scattered, MAXLAY, Light_profile::shaded_absorbed_ppfd, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, and thin_layer_absorption().
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
thick_layer_absorption()
double thick_layer_absorption (double R, double T, double I_0)
Computes absorbed light from incident light for a thick layer of material.
Suppose light of intensity I_0 (representing a flux density of photons or energy, expressed in units of photons per area per time, or energy per area per time) is incident on an infinitely thick layer of a material that reflects, absorbs, and transmits light. If R and T represent the fractions of light reflected by and transmitted through a thin layer of the material, then we can calculate the light absorbed by an infinitely thick layer of the material (I_abs) as follows:
I_abs = I_0 * (1 - R - T) / (1 - T) [Equation (1)]
In this equation, the factor (1 - R - T) / (1 - T) represents the fraction of light absorbed by the thick layer. See the "Light Absorption by a Thick Layer" vignette for more information about this equation.
Parameters
[in] R The fractional amount of light reflected by a thin layer of the material in the appropriate wavelength band; note that this reflectance is not necessary the same as would be measured from a thin layer in isolation.
[in] T The fractional amount of light transmitted by a thin layer of the material in the appropriate wavelength band; note that this transmittance is not necessary the same as would be measured from a thin layer in isolation.
[in] I_0 The amount of light incident on the material, perhaps restricted to a particular wavelength band; for quantum fluxes, the units will typically be micromol / m^2 / s; for energy fluxes, the units will typically be J / m^2 / s.
Returns
The amount of radiation absorbed by the material expressed in the same units as I_0.
Definition at line 79 of file sunML.cpp.
Referenced by absorbed_shortwave_from_incident_ppfd(), and SoilEvapo().
thin_layer_absorption()
double thin_layer_absorption (double R, double T, double I_0)
Computes absorbed light from incident light for a thin layer of material.
Suppose light of intensity I_0 (representing a flux density of photons or energy, expressed in units of photons per area per time, or energy per area per time) is incident on a thin layer of a material that reflects, absorbs, and transmits light. If R and T represent the fractions of light reflected by and transmitted through the layer, then we can calculate the light absorbed by the layer (I_abs) as follows:
I_abs = I_0 * (1 - R - T) [Equation (1)]
In this equation, the factor (1 - R - T) represents the fraction of light absorbed by the layer. In BioCro, this equation is often used to calculate the light absorbed by a leaf or a thin layer of leaf material.
Parameters
[in] R The fractional amount of light reflected by a thin layer of the material in the appropriate wavelength band.
[in] T The fractional amount of light transmitted by a thin layer of the material in the appropriate wavelength band.
[in] I_0 The amount of light incident on the material, perhaps restricted to a particular wavelength band; for quantum fluxes, the units will typically be micromol / m^2 / s; for energy fluxes, the units will typically be J / m^2 / s.
Returns
The amount of radiation absorbed by the material expressed in the same units as I_0.
Definition at line 34 of file sunML.cpp.
Referenced by sunML().